### ISSUE TITLE
wal-r 

### ISSUE THREAD

**Issue by zh0kx** [dylanaraps/pywal#100]
On iterm2 wal -r generates {spaces}%, so on every new terminal tab I have this output. How to solve it?

**Comment by dylanaraps** [comment]
Can I see a screenshot?

**Comment by zh0kx** [comment]
<img width="688" alt="captura de pantalla 2017-09-09 a las 10 53 39" src="https://user-images.githubusercontent.com/20535054/30238730-300cc924-954d-11e7-8202-d586779dbfaa.png">

**Comment by dylanaraps** [comment]
@aeikenberry can you reproduce this at all? (*I can't test on macOS*)

**Comment by zh0kx** [comment]
I found a temporal solution: `printf $(wal -r)`

**Comment by linuxunil** [comment]
@dylanaraps when running wal -r in the terminal it happens, but if you run $(wal -r) it works fine.

**Comment by nmwalsh** [comment]
Getting this same issue with the spacing. Here's a screenshot with my more default-looking terminal, hopefully it helps diagnose it. It started happening as soon as I added `$(wal -r)` to my .bashrc file.

![screen shot 2017-10-17 at 3 25 13 pm](https://user-images.githubusercontent.com/10050819/31692675-9c0571ce-b34f-11e7-9356-a21ab0c2bdc3.png)

**Comment by yoyostile** [comment]
As mentioned by @zh0kx above, using `printf` did the trick for me as well.
```
(printf $(wal -r) &)
```

¯\_(ツ)_/¯

**Comment by dylanaraps** [comment]
This should be fixed in the next release.

`wal -r` has been replaced with `cat ~/.cache/wal/sequences`.

(if not, just reopen this)
