### ISSUE TITLE
Wrong argument in wiki

### ISSUE THREAD

**Issue by ranisalt** [dylanaraps/pywal#101]
The getting started page on wiki states the following:

```
# Add this to your .xinitrc or whatever file starts programs on startup.
# -R restores the last colorscheme that was in use.
wal -R
```

But `-R` is not a valid argument

```
usage: wal [-h] [-a "alpha"] [-b background] [-c] [-i "/path/to/img.jpg"]
           [-f "/path/to/colorscheme/file"] [-n] [-o "script_name"] [-q] [-r]
           [-t] [-v]
wal: error: unrecognized arguments: -R
```

I see on other places that `wal -r` might work, but it doesn't; i3wm still has the same old colors. Manually running `wal -i /path/to/wallpaper.png` works, though.

**Comment by dylanaraps** [comment]
Are you using the latest version of `pywal`?

**Comment by ranisalt** [comment]
No, I was using 0.5.9 and just checked out 0.6.9, thanks!
