### ISSUE TITLE
Unittests fail on MacOS

### ISSUE THREAD

**Issue by linuxunil** [dylanaraps/pywal#102]
When you run the unittests on MacOS they fail due to the special escape sequences for iTerm.  I can work on cleaning up the tests, but I'm not the greatest at unit tests.  I attached the output of `python -m unittest discover`

[https://gist.github.com/linuxunil/5c6529c09879b417e33783264f7f5612](url)

**Comment by dylanaraps** [comment]
I'll add 2 macOS VMs to Travis and I'll slowly fix them in a separate PR.

**Comment by linuxunil** [comment]
I have grabbed your branch and am working on this too.  I also wondered if we could start a thread for cleaning up and writing documentation.  There are a few things in the tests and the color generation that I'm having a hard time understanding what there trying to accomplish.

**Comment by dylanaraps** [comment]
Yes, feel free! I’m not near a PC atm so I can’t create a new issue. But I
can comment.

**Comment by linuxunil** [comment]
Just found out I'll be gone for a week so I might not get much done.

**Comment by dylanaraps** [comment]
That test tests that the colors inside the dict are in the correct order. In Python <3.6 dicts are unordered so in the port to Python 3.5 this test was added. Looking at it now it does seem pointless as I don't think it's possible for this to fail. I'll remove it.
