### ISSUE TITLE
Poor contrast recently

### ISSUE THREAD

**Issue by Iambecomeroot** [dylanaraps/pywal#106]
Recently, I have noticed that certain panels (in vim and tmux, for example) have very poor contrast. I can only attribute this to a recent pywal update.

Here is an old screenshot showing a tmux panel and a vim panel:
![image](https://user-images.githubusercontent.com/8503756/30218837-8cf2f95a-9490-11e7-927b-b5481c8898f1.png)
As you can see, the `1 zsh` and `NORMAL` are clearly legible. 

Here is a current screenshot:
![image](https://user-images.githubusercontent.com/8503756/30378645-4a66b7c4-986a-11e7-98f5-42365ca051ae.png)

I am using the latest version (0.6.0) and I have reproduced the issue with multiple terminal emulators.

**Comment by kotajacob** [comment]
Not the maintainer, but have you tried installing an older version of pywal to verify that if actually is the new update that broke the contrast for you?

If you installed with pip I believe the command would be something like `pip3 install pywal==0.4.0` after you've uninstalled the current version.

**Comment by dylanaraps** [comment]
Can you also confirm that the issue occurs with the same image as the source in the latest version `0.6.9` and in the last version it worked in?

**Comment by Iambecomeroot** [comment]
Here it is the same image in the current version: 
![image](https://user-images.githubusercontent.com/8503756/30407192-34ead944-98cd-11e7-982d-479b75180f7f.png)
Sorry, I meant to put that one initially but I wrote the issue right quick before leaving work. I did see the same issue with image I know used to work or I wouldn't have opened the issue. Here is the image too if that helps: 
![prapwqd](https://user-images.githubusercontent.com/8503756/30407234-6810914c-98cd-11e7-8f6d-a42113179cfa.jpg). This image isn't so bad as the first one but I think the blue bar is supposed to be the same colour as the background, no?

I am checking older versions now.

**Comment by dylanaraps** [comment]
>  the blue bar is supposed to be the same colour as the background, no?

Yup!

Have you updated the vim colorscheme to the latest version? This doesn't occur on my system.

**Comment by dylanaraps** [comment]
scrot:

 ![2017-09-14-10-59-58](https://user-images.githubusercontent.com/6799467/30407338-0fcf5ed2-993b-11e7-9699-22e17e220a66.png)

**Comment by Iambecomeroot** [comment]
I think I have the latest version. I am no expert with Plug. I cd-ed into `~/.vim/plugged/wal` and git pull says `Everything up-to-date.`. And I ran `PlugUpdate`. Also, the poor contrast in tmux suggested to me that it was not a wal.vim issue.

**Comment by dylanaraps** [comment]
I took a look at your `vimrc` and noticed that you're using the old vim colorscheme. The colorscheme that `pywal` uses is separate from the old `wal` repo. 

Try the new colorscheme (This should fix the vim issue):

```vim
Plug 'dylanaraps/wal.vim'
```

**Comment by dylanaraps** [comment]
Also!

`pywal` no longer uses nor defines color `66`. Instead `pywal` uses the default value of color `232` to get the same result. There were issues in some terminal emulators when `pywal` defined color `66` so using it was removed.

These most recent comments should fix both of the issues. I'll also make notes of these in the wiki somewhere.

**Comment by Iambecomeroot** [comment]
That fixed it. Thanks. I thought there might be a new colourscheme for pywal but the repo name looked familiar so I assumed it didn't change. Changing `66` to `232` in `tmux.conf` fixed the tmux issue. Thanks a bunch!
