### ISSUE TITLE
ranger resets to default colorscheme in terminator

### ISSUE THREAD

**Issue by jpprime** [dylanaraps/pywal#107]
It seems that every time ranger does something that updates the whole window in terminator, it resets the whole terminal to the default colorscheme (the one that was set in your configs, ignoring pywal's colorscheme).

The steps to reproduce this issue are quite simple:

* Open up ranger through the command;
* Do anything that updates all of the terminal window, for example, in the gif, I opened up vim (I've tested with commands such as `:shell pandoc ...` and `:shell git ...` that, while executing, update the whole window, and for things like the the S mapping in ranger, that takes me to my shell `map S shell zsh -c "cd %d; zsh"`).

Or, if you open up ranger with a custom mapping (for example, I have $mod+r on i3wm), ranger will not get the custom colorscheme from the start.

Expected is you would have your custom colorscheme, but what happens is that ranger sets the default colorscheme back. That might have not been clear in the gif because the custom colorscheme and the default were very alike. In the end, when I open up two different terminals, the left one is terminator and the right one is URxvt. The right one is with the custom colorscheme, but terminator reverted back to the default colorscheme - and it affects the whole terminal window - so if I leave ranger, the terminal doesn't have the custom colorscheme set anymore.

I should also mention, If I haven't yet, that this doesn't happen on URxvt, neither the ranger issue, nor the mouse thing (maybe because it uses Xresources). I can't say about other terminals, but I can say that it happens in terminator, which is the one I recorded on (it might even be a terminator issue, but I haven't got the time to test on different emulators).

I'm sorry if it was not clear what was happening. And thank you for your patience and willingness to resolve these little issues.

Here's the above mentioned gif:

**Comment by heartb1t** [comment]
https://gfycat.com/gifs/detail/OrderlyUnsightlyFlicker

**Comment by balbooaaa17** [comment]
I too also use terminator as a daily terminal, but i think this issue belongs to terminator. The problem is even if i lose focus for a sec from the main window of terminator the cholorschemes are back to default(whether its ranger,cmus,htop, u name it. Same issue goes with neofetch, where the image dissapear everytime u lose focus of the window. Ive tried with urxvt, gnome-terminal, xfce4-terminal it works. 

So i'm guessing its more a terminator issue than a pywal.

**Comment by balbooaaa17** [comment]
So here i'am, i went to terminator home page and got the last version and compiled from source and installed it, last version is 1.91. Opened two terminator windows, in one window i opened ranger, in the other one i ran the command "wal -i /pathtoimages" and wollaaa, it worked, colors changed automatically and fast af, i could switch between windows and no default mode anymore. Anyway bro i suggest you to give it a try.

First download and install this https://launchpad.net/ubuntu/xenial/i386/intltool/0.51.0-2  &&

 Here's the link to the lastest version  https://launchpad.net/terminator/gtk3/1.91, just extract it and run sudo python ./setup.py install and it will work (tested on ubuntu).

**Comment by heartb1t** [comment]
All right! I'll give it a try. Though I have version 1.91 installed through pacman (on Arch Linux), and it still doesn't work, but I'll test compiling it from source.

**Comment by Sacmanxman2** [comment]
What worked for me is making a shell script to launch Ranger like this. It runs the command to update termites' color scheme right before ranger:
#!/bin/bash
(wal -r &)
ranger
