### ISSUE TITLE
Wallpaper not changed on Manjaro cinnamon

### ISSUE THREAD

**Issue by Xunius** [dylanaraps/pywal#108]
Hi,

I installed pywal from the AUR, I tried both the 'python-pywal' and 'python-pywal-git'. They both installed OK and the terminal color do change, but the wallpaper doesn't change for some reason.

The pywal version I got is 0.6.9.

Output from command line:
```
wal -t -i train_road_smoke_79239_1920x1080.jpg 
image: Using image /home/guangzhi/Pictures/wallpapers/train_road_smoke_79239_1920x1080.jpg
colors: Found cached colorscheme.
colors: Set terminal colors.
wallpaper: Set the new wallpaper.
export: Exported all files.
reload: Reloaded environment.
```
So it saids wallpaper is changed but in fact not.

Another minor suggestion is: in the installation guide you listed a few dependencies, the line `xfce, gnome, cinnamon, mate` is supported DEs, I assume. Then the following line I assume is for wallpaper setting softwares. I think there is some ambiguity that it could mean any one of `feh, nitrogen, bgs, hsetroot, habak`, following the DE logic, or all of them. I've installed all of them already.

Please help.

**Comment by Xunius** [comment]
After bit of messing around, I think the code section relevant to wallpaper setting in cinnamon is in 'wallpaper.py':
```
elif "muffin" in desktop or "cinnamon" in desktop:
    util.disown(["gsettings", "set", "org.cinnamon.desktop.background", "picture-uri", "file://"+urllib.parse.quote(img)])
```
I tried to run that command manually in terminal:

```
gsettings set org.cinnamon.desktop.background picture-uri file:///home/guangzhi/Pictures/wallpapers/train_road_smoke_79239_1920x1080.jpg
```
And `gsettings` complained that `libselinux.so.1` is not found. I installed that from AUR, and now I got this:

```
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```
Please help

**Comment by Xunius** [comment]
The real dirty hack I use is to comment out the "desktop" and let it fall back directly to "set_wm_wallpaper()" function:

```
def change(img):
    """Set the wallpaper."""
    if not os.path.isfile(img):
        return

    desktop = get_desktop_env()

    if OS == "Darwin":
        set_mac_wallpaper(img)

    elif OS == "Windows":
        set_win_wallpaper(img)

    #elif desktop:
        #set_desktop_wallpaper(desktop, img)

    else:
        set_wm_wallpaper(img)
```

**Comment by dylanaraps** [comment]
This sounds like an issue with your cinnamon install and not with `pywal`'s wallpaper handling.
