### ISSUE TITLE
Ranger not changing color by keyboard shortcut in gnome-terminal

### ISSUE THREAD

**Issue by Xunius** [dylanaraps/pywal#109]
Hi,

Firstly I need to make it clear that ranger does change color if I launch wal outside ranger, but not within ranger using a keyboard shortcut, in gnome-terminal.

The keyboard shortcut in ranger to issue wal on an image is:

```
map bg shell wal -t -c -i %f
```
And I noticed that about 80% of the time the colorscheme is not changed after launching that, other opened terminals do pick up the new colorscheme though. When failed, ranger just falls back to its default scheme.

If I issue wal from a seperate terminal, everything (opened terminals and opened ranger) got the change.

I tried opening ranger in xterm, the keyboard shortcut worked as expected, so it might be another gnome-terminal specific issue.

**Comment by Xunius** [comment]
update: I noticed that after hitting the shortcut in ranger, if I spawn a new terminal and ranger's colorscheme will update.

**Comment by dylanaraps** [comment]
I can reproduce this but there's no way for me to fix it due to how `ranger`'s `shell` function works.
