### ISSUE TITLE
Travis-CI pylint and flake8 on MacOS

### ISSUE THREAD

**Issue by linuxunil** [dylanaraps/pywal#110]
I can get both flake8 and pylint to pass locally but the travis-ci vm's spit out some errors when ever you run it there.   Any solutions I have tried have killed the linux vm's ability to run them as well.  From what I can see this still stems from travis-ci's inability to properly install python on the MacOS vm.  

Example failing build is [travis-ci](https://travis-ci.org/linuxunil/pywal/jobs/279142906)

**Comment by dylanaraps** [comment]
I've fixed the linting errors in the macOS VMs, now only the tests fail.
