### ISSUE TITLE
tmux and pywal

### ISSUE THREAD

**Issue by phen0type** [dylanaraps/pywal#118]
Just wondering how you apply pywal to tmux?  When I load it up it sources my original Xresources file rather than wal on restart.

**Comment by dylanaraps** [comment]
`tmux` works fine for me, it uses the `pywal` colors automatically. Can you elaborate and maybe send a screenshot showing the issue? Your `tmux` config and terminal emulator would be helpful too.

**Comment by RorixRebel** [comment]
Are you importing wal on your shell?
i got this on my zshrc and it works regardless of the terminal app

```
# Import colorscheme from 'wal'
(wal -r -t &)
```
