### ISSUE TITLE
Possible to have pywal only generate files and not automatically change terminal colors?

### ISSUE THREAD

**Issue by YamiFrankc** [dylanaraps/pywal#119]
I would like to have pywal to only generate color files so I can source them for other configs.
I know there is an option to not xrdb so urxvt keeps my own colors, but already open instances do change colors.
Is there a way to change this behaviour?

**Comment by MLGSinon** [comment]
@YamiFrankc You can find colours genrated by wal in $HOME/.cache/wal/colors.yml file.

**Comment by dylanaraps** [comment]
Fixed. https://github.com/dylanaraps/pywal/commit/6b0d4a36de821b9838f32465d0c510cfe27afa56
