### ISSUE TITLE
When reloading with wal -R the transparency setting disappears

### ISSUE THREAD

**Issue by mhham** [dylanaraps/pywal#120]
I first launch `wal -i "\path\to\wallpaper" - a "60" ` in URxvt and transparency works great.

However if I logout and launch `wal -R` from URxvt, the previous session is correctly restored except transparency which is not taken into account.

**Comment by dylanaraps** [comment]
I can reproduce this, I'll have to rewrite how `-R` works to fix this. Thanks for finding it!

**Comment by mhham** [comment]
Hi there, I could help in this rewrite. Could you give me some insight on how `-R` works currently ?

**Comment by dylanaraps** [comment]
This issue has been finally fixed. Sorry for the delay, I was just trying to come up with the best fix possible and I found a viable solution this morning.
