### ISSUE TITLE
Rofi resets config after reboot

### ISSUE THREAD

**Issue by Sacmanxman2** [dylanaraps/pywal#122]
Pywal changes Rofi's colors when I run it, but after reboot rofi resets to the default colors. I didn't see anything in the configuration instructions to make it permanent, it seems to say it should just work automatically.

**Comment by dylanaraps** [comment]
Are you running `wal -R` on boot? Rofi's colors persist on my machine.

**Comment by JoshuaRLi** [comment]
`rofi` coloring persists on my machine as well, with a fresh wal 0.6.9 install.

**Comment by Sacmanxman2** [comment]
My mistake, I had wal -R in my .xinit stuff, but I guess it wasn't running properly. I've added it to my i3 config. Thank you!
