### ISSUE TITLE
Apply generated scheme to Fuzzyfinder

### ISSUE THREAD

**Issue by ltgouvea** [dylanaraps/pywal#124]
Hello everyone,
I've been able to get this working inside VIM with those settings on my `.vimrc`

```let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```
However I'm not getting the generated colorscheme to work when running fuzzy finder from the terminal (I'm currently using Termite). Does anyone know how to define the `FZF_DEFAULT_OPTS` variable so that the colorscheme follows the colors generated by pywal?

**Comment by dylanaraps** [comment]
I've pushed an update to `pywal` that makes it set the FZF colors when you source the `colors.sh` file. This also makes the colors work in `vim` so there's no need for anything in your `vimrc`.

Example setup:

```sh
# In your .bashrc

# Source the pywal colors.
source ~/.cache/wal/colors.sh
```

(This will be available next release.)
