### ISSUE TITLE
Terminal slow startup / Strange behavior from Pywal

### ISSUE THREAD

**Issue by Zyrophr** [dylanaraps/pywal#125]
Hi !
I've been using pywal since a while now, and today after I tried to set a binding key which will execute pywal, I've been having some strange bugs.
I'm using i3-gaps, Tilix/urxvt/Terminator and bash/oh-my-zsh on Fedora 26.

Now, my i3 config for focused colors won't even work anymore like it did yesterday : 
`
set $unfocused_border ${xrdb:color2}
set $focused_border ${xrdb:color7}
`

And even more horrible, my terminal is taking a looong time to apply the theme by wal. I'm using `(wal -t -r &)`

It wasn't doing this this morning, and I can't find any solution on the internet. It does it on every terminal / bash I have !

Could you please help me ? 

thanks !

**Comment by Zyrophr** [comment]
Update : It seems like... It's broken... I mean, I uninstalled/installed pywal from git or pip several times, and it seems that i have some file that keep applying to Pywal.

And also, it seems that it doesn't "save" the theme, because, for example, when I launch NCMPCPP, it use the pywal theme, but if I unfocus the window it reset to the default flashy theme.

I don't know where to search now ...

**Comment by dylanaraps** [comment]
In the next version `wal -r` has been replaced by `(cat ~/.cache/wal/sequences &)` which is instant and bypasses the slow startup time of python.

**Comment by Bendodroid** [comment]
@Zyrophr Did you fix the issue with ncmpcpp not using the correct theme?

**Comment by AFAgarap** [comment]
Still slow startup time with kitty
