### ISSUE TITLE
Turn into general color scheme manager

### ISSUE THREAD

**Issue by opatut** [dylanaraps/pywal#13]
This tool has the potential to be more generic, and I love generic tools :stuck_out_tongue_winking_eye: 

I'd love for wal to be able to read some generic colorscheme format (e.g. simple text based hex or something), without the "need" to generate them from an image. I actually consider this two separate parts of wal currently, and I am more interested in the former.

Use case: I sometimes sit outside with my laptop and switch my vim and terminal to a black-on-white color scheme for contrast. I have do this manually for each program. I don't bother with all the others. It would be awesome to define a few colorschemes somewhere (or download them from somewhere) and then just apply them for ALL the programs :)

Currently, wal does a pretty good job already supporting many different programs. I just can't invoke it without generating from an image.

Shouldn't be too hard, technically, right? :)

**Comment by dylanaraps** [comment]
Closed (https://github.com/dylanaraps/pywal/issues/14)
