### ISSUE TITLE
vim lightline support?

### ISSUE THREAD

**Issue by indeedwatson** [dylanaraps/pywal#130]
I know pywal has airline support but I recently moved away from it in favor of something more minimal: https://github.com/itchyny/lightline.vim

**Comment by dylanaraps** [comment]
Done!

Update the vim colorscheme and let me know if you're satisfied. :)

**Comment by indeedwatson** [comment]
I tried with about 10 wallpapers and it looks fantastic, you're awesome, thanks!

**Comment by mdnghtt** [comment]
Hey so ik this is very late but im having the same issue 
everything is working accept that lightline colors arent changing
so what should be the colorscheme name in `let g:lightline = {'colorscheme': 'colorscheme_name'}`


my vimrc
```
call plug#begin()
Plug 'dylanaraps/wal.vim'
Plug 'itchyny/lightline.vim'
call plug#end()

syntax on
set pastetoggle=<F3>
set number
set laststatus=2
colorscheme wal
let g:lightline = {'colorscheme': 'wal'}
```
