### ISSUE TITLE
Error: colors: Imagemagick couldn't generate a 16 color palette, trying a larger palette size 17

### ISSUE THREAD

**Issue by pycebs** [dylanaraps/pywal#131]
Hey.

My wal isn't able to create new color schemes anymore.

ERROR:
colors: Imagemagick couldn't generate a 16 color palette, trying a larger palette size 17
colors: Imagemagick couldn't generate a 16 color palette, trying a larger palette size 18
colors: Imagemagick couldn't generate a 16 color palette, trying a larger palette size 19

It then loops up to "...palette size 37" and exits.

wal version: 0.7.1
convert/IM version: 6.9.9-21 Q16
Running Arch x64, installation via (sudo) pip

Maybe some compatibility problem with convert/IM?

**Comment by dylanaraps** [comment]
Can you send me the image you're trying to generate a scheme for?

**Comment by pycebs** [comment]
This happens with literally every image I try. Even the ones it previously worked with. I cleared the cache and tried it again. And the above mentioned error occurs.

**Comment by oulakal** [comment]
I'm having the same problem. It started happening after I used a json file to generate a scheme.

**Comment by pycebs** [comment]
@oulakal What's your wal and imagemagick version?

**Comment by Clyybber** [comment]
Oh well. Now its happening for me too.

**Comment by Clyybber** [comment]
I knew i had that problem before, but I dont remember how or if i even fixed it.

**Comment by pycebs** [comment]
The update to IM 6.9.9.22-1 just came through on arch and the error still persists.

**Comment by HeatedTea** [comment]
I also had this issue with 6.9.9.22-1 on Arch.
Fixed it by installing imagemagick-git on the AUR.

**Comment by dylanaraps** [comment]
Closing this as the issue seems to have solved itself(?)

**Comment by PrismaPhonic** [comment]
Why do you close issues that aren't actually resolved?  I see tons of issues like this.  One person claims they fixed it on their setup and you close the entire ticket?

**Comment by PrismaPhonic** [comment]
That's not true because if I use a different backend option it definitely works.  Also, this post is referring to a version of ImageMagick that I definitely don't have.  I have the most recent version - and it only fails in this way if I use the wal backend.  colorthief backend leverages imagemagick with no issues - so it's an issue with wal, not imagemagick

**Comment by Clyybber** [comment]
Sry, I'm out of ideas then.
