### ISSUE TITLE
Transparency out of xrdb colors?

### ISSUE THREAD

**Issue by Trollwut** [dylanaraps/pywal#132]
Hi folks!

I think you all know that pywal is awesome.

I use polybar and therefore also use the colors out of xrdb to be used there. E.g.:

    background = ${xrdb:color2}

Is there a possibility to have some alpha channel on these colors? Before `wal`, I used `background = #00222222` (transparent color) and looked for wallpapers that fit to that. But as I now use `wal`, not every wallpaper is capable of having a transparent color and therefore text might not be readable.

I don't want to have a solid color, as this makes the polybar a bit too much distracting, but a half-transparent background color would be a good compromise.

**Comment by dylanaraps** [comment]
You can workaround this like so:

```sh
# .bashrc

# source wal colors.
source ~/.cache/wal/colors.sh

# export envar with alpha set.
export color0_alpha="#22${color0/'#'}"
```

```
; polybar/config

[bar/top]
background = ${env:color0_alpha}
```

**Comment by dylanaraps** [comment]
Also, see: https://github.com/dylanaraps/pywal/pull/142

**Comment by Tarch1** [comment]
HI,
I've a proble whit obliviusly the transparency of polybar, when bspwm start whit this config:
`#! /bin/sh
sxhkd &
chmod a+w /sys/class/backlight/intel_backlight/brightness &
setxkbmap -layout it &
numlockx &
xsetroot -cursor_name left_ptr &
#feh --bg-fill --randomize ~/.wallpapers/* &
xautolock -time 5 -locker "gllock" &
./.config/low-battery.sh -n &
wal -i ~/.wallpapers/ &
./.config/polybar/launch.sh &
picom --experimental-backends &
bspc monitor -d I II III IV V'

and the polybar relative colors
`[colors]
background = ${env:color0_alpha}
;background = ${xrdb:color1:#222}
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color3:#222}
alert = ${xrdb:color5:#222}
`
polybar set the background color to black whitout the transparency, but if I use this script 
`./.config/polybar/launch.sh`
 in a terminal after the bar is started transparency is working.
I don't know if this is the right place to post but for now i try here :)

**Comment by marssaljr** [comment]
I know it's closed, but maybe you can try this:
```
# polybar/config

[bar/top]
color = ${xrdb:color0}
background = "#00${color}"
```
or
```
# polybar/config

[bar/top]
background = "#00${xrdb:color0}"
```
