### ISSUE TITLE
wal -r does not work when using alacritty + tmux

### ISSUE THREAD

**Issue by Sh4d1** [dylanaraps/pywal#135]
Hey :) 

My issue is when I write `(wal -r &)` in my `.zshrc` it does not reload the config when I use alacritty and tmux. 
If I launch alacritty, it works. If I launch tmux from alacritty, it works. However when I launch `alacritty -e tmux`, it does not work. And the only working solution from there is `wal -R`. Not sure the issue is with pywal but it's worth a shot :) 

Thank you!

**Comment by dylanaraps** [comment]
This sounds like a quirk of `-e` instead of an issue with `pywal`. It's nothing I can fix.

**Comment by konez2k** [comment]
```
alacritty -e $HOME/.bin/tmuxdd &
```

Inside tmuxdd:

```
#!/bin/sh
wal -R
tmux -2 a || tmux
```

**Comment by gibranlp** [comment]
I am still having this issue when launching alacritty from qtile shortcut the terminal does not respect the palette generated before

**Comment by gibranlp** [comment]
This also happens on st

**Comment by ogabriel** [comment]
this will also work if you need to start alacritty with tmux

```yaml
shell:
  program: /bin/zsh
  args:
  - -l
  - -c
  - "(cat ~/.cache/wal/sequences &) && tmux"
```
