### ISSUE TITLE
Issue with old AMD GPU

### ISSUE THREAD

**Issue by JustPauL** [dylanaraps/pywal#136]
When I run the wal command, I get the following output:
`amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.`
Is there any way around this, or there is no support for old hardware? GPU is AMD 6850.

**Comment by JustPauL** [comment]
Fixed by installing imagemagic package. Close.

**Comment by xlpiao** [comment]
@JustPauL 
How did you fix it? Could you tell me the exact steps?
