### ISSUE TITLE
Sway

### ISSUE THREAD

**Issue by PlayLucky** [dylanaraps/pywal#137]
colors-sway defines colors like this:
`set $color1 "#rrggbb"`
Sway only accepts variables without quotation marks.
The correct definition should look like this:
`set $color1 #rrggbb`
If I change colors-sway to use this definition it works fine.

[sway template file](https://github.com/dylanaraps/pywal/blob/master/pywal/templates/colors-sway)

**Comment by dylanaraps** [comment]
Fixed.
