### ISSUE TITLE
color8 to color15 always the same as color0 to color7

### ISSUE THREAD

**Issue by Traveled** [dylanaraps/pywal#138]
Hi, 
maybe it's me that as missunderstood the 16 color scheme generation,
but is it normal that for every image I try, pywal generate 16 color but only 8 are different.

Thx

**Comment by boardfish** [comment]
Which version are you running? Use `wal -v` to find this out.

**Comment by Traveled** [comment]
Hi,
wal -v tell, I have wal 0.7.1
I have installed it trough AUR python-pywal-git.

**Comment by dylanaraps** [comment]
`wal` generates 16 colors but only `9` are used. Not all of the generated colors are suitable for a colorscheme.

**Comment by sonjiku** [comment]
I know this is old, but my [fork](https://github.com/sonjiku/pywal), for which I have also made a pull request #601, adds this functionality/
