### ISSUE TITLE
"Special" color setting

### ISSUE THREAD

**Issue by Lundmore** [dylanaraps/pywal#139]
Having some issues with wal.. I can't get it to generate background, foreground and cursor lines in the colors.Xresources file.

EDIT:
Please close/delete, lets put it down to sleep deprevation..

**Comment by Lundmore** [comment]
On another note, I seem to have the same issue as [#138](https://github.com/dylanaraps/pywal/issues/138) also. I was too busy focusing on the special snippet.

**Comment by boardfish** [comment]
@dylanaraps 👀
