### ISSUE TITLE
polybar doesn't load the colors in i3 startup script

### ISSUE THREAD

**Issue by MrHuds0n** [dylanaraps/pywal#140]
My apologies if this is just usage error but I spent a few days trying to figure this out and I'm at a loss.

```sh
# .config/polybar/startup.sh
#!/bin/zsh
killall -q polybar

while pgrep -x polybar >/dev/null; do sleep 1; done

PBMONITOR=$(polybar -m | tail -1 | sed -e 's/:.*$//g')

echo $PBMONITOR

if [ "$PBMONITOR" = "DVI-I-0" ]
then
	polybar left &
	polybar right &
fi

if [ "$PBMONITOR" = "eDP1" ]
then
	polybar laptop &
fi
```

```sh
# .config/i3/config 
# ...
# polybar
exec_always --no-startup-id $HOME/.config/polybar/startup.sh

# wal
exec --no-startup-id wal -R
# ...
```
[full dots here](https://github.com/MrHuds0n/dotfiles)

When I log into the system normally, the colors in polybar don't load despite the `wal -R` scripts being nearly everywhere. However when I run `wal` again from terminal after logging in, polybar refreshes with proper colors. This seemed to happen regardless of polybar configuration, just any reference to xrdb showed up as transparent after startup and required a manual `wal -R` from terminal to fix.

System is elementary OS 0.4 Loki if this helps.

**Comment by pasau** [comment]
i had a similar problem for a while, and finally fixed it. In my case, the polybar would simply not show up upon starting i3. I haven't found a way to get an error message, but adding this line to my polybar launch script fixed it:

`while pgrep -x wal > /dev/null; do sleep 1; done`

it seems polybar has to wait for wal to initialize colors properly

**Comment by MrHuds0n** [comment]
@pasau I tried that and unfortunately it didn't resolve the issue, thanks for the input regardless though.

**Comment by dylanaraps** [comment]
Tried running `wal -R` before `polybar` is started?

**Comment by MrHuds0n** [comment]
I have, yes. As I said, I tried running wal at every point in the startup scripts.

**Comment by RorixRebel** [comment]
do you see any polybar related errors in your /.xsession-errors?

**Comment by MrHuds0n** [comment]
That fixed it, thank you very much!

**Comment by RorixRebel** [comment]
glad to help

**Comment by Ordeeper** [comment]
i have the same issue, but is doesn't work for me
my i3 conf:
```
exec_always --no-startup-id wal -R
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
```

my polybar launch:
```
#!/usr/bin/env bash

# Terminate already running bar instances
# If all your bars have ipc enabled, you can use 
polybar-msg cmd quit
# Otherwise you can use the nuclear option:
# killall -q polybar

# Launch skybar
echo "---" | tee -a /tmp/polybar1.log
polybar skybar 2>&1 | tee -a /tmp/polybar1.log & disown

while pgrep -x polybar >/dev/null; do sleep 5; done

echo "Bars launched..."
```
I've been trying to solve this for 3 days
