### ISSUE TITLE
pywal.reload.colors() terminates python session

### ISSUE THREAD

**Issue by jarvick257** [dylanaraps/pywal#141]
I am trying to use pywal from a python script but whenever I try to reload the colorscheme (both with `pywal.reload.colors(True)` and `pywal.reload.colors(False)`) the script stops. Same happens when trying to run this command in a terminal python session. Is that expected behavior?

I am running arch with Python 3.6.3 and wal 0.6.9

**Comment by dylanaraps** [comment]
Fixed in master. Pushing a new release in a sec. Thanks :+1:
