### ISSUE TITLE
System alert sound always present when running wal.

### ISSUE THREAD

**Issue by cj-sv** [dylanaraps/pywal#145]
- GNOME Terminal 3.24.2 Using VTE version 0.48.4 +GNUTLS -PCRE2
- Zsh 5.2

Possibly from the garbage workaround or VTE sequence?

**Comment by dylanaraps** [comment]
Are you hearing the terminal bell? I can't reproduce this at all. 

Does running this command cause the sound to play?: `echo -en "\033[1000H"`

**Comment by cj-sv** [comment]
Yep, hearing the terminal bell.
Running `echo -en "\033[1000H"` doesn't reproduce the sound.

**Comment by dylanaraps** [comment]
What about this one? `echo -en "\033[8m"` or `echo -en "\0337\0338"`

**Comment by cj-sv** [comment]
Nope, both code snippets don't reproduce the sound.

**Comment by dylanaraps** [comment]
Does the bell sound when running `cat ~/.cache/wal/sequences`?

**Comment by cj-sv** [comment]
Yes

**Comment by dylanaraps** [comment]
This should be fixed in the latest master.

**Comment by cj-sv** [comment]
Tested on the latest update. Tried cleaning cache and reinstalling. Still seems to be there. Running `wal -R` triggers the alert as well.

**Comment by dylanaraps** [comment]
By latest update do you mean the latest release or latest git commit? I haven't made a new release with the fix yet.

**Comment by cj-sv** [comment]
Latest git commit. I cloned the repo.

**Comment by dylanaraps** [comment]
I can't reproduce this issue at all. Does running the entire sequence as a whole cause the beep?

`echo -en "\033[s\033[1000H\033[8m\033]708;#000000\007\033[u"`

**Comment by cj-sv** [comment]
Yep, looks like it.

**Comment by dylanaraps** [comment]
Can you cut out sequences from that list until it stops? We need to figure out the exact sequence that's causing the issue.

**Comment by cj-sv** [comment]
There were no alert sounds after removing either `\007\033[u` or `708`

**Comment by dylanaraps** [comment]
Ok, I think we can conclude that the escape sequences containing `7` are triggering the ascii bell `\007` somehow.

**Comment by dylanaraps** [comment]
It turns out that I was using the terminal bell sequence as the color changing sequence delimiter. I looked up the spec and found an alternative sequence. This issue should now be fixed. Try the latest commit!

**Comment by cj-sv** [comment]
Awesome, I just tested it out and it's now fixed. Great work man~
