### ISSUE TITLE
re-add -r just that instead of using previous method, just cat the sequence file

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#147]
I think this might be a good change for `pywal` since as it is it might break a lot of people's config and it should be pretty simple to implement with a simple system call, if not, this would mean every instance of `wal  -r` in everyone's dot files would be invalid.

it is pretty simple to implement in `wpgtk` too, but I still think it's best for `pywal` remain compatible with previous instances wherever possible, I can make a PR if you'd like.

**Comment by dylanaraps** [comment]
A major version number indicates changes that break compatibility with previous versions. `pywal` will not crash if you're still using `wal -r` (*Though the api might, that's my fault and I apologise*), instead it will display a message informing you of the syntax change.

All the `-r` flag did was print the contents of the `sequences` file to the terminal. There was a regex subsitution to fix VTE terminals but other than that, all it was  doing is `cat file`. The VTE fix was no longer needed which made the `-r` flag a slow. glorified `cat`.

The reason this was changed to a shell alternative is that this simple task had a `300ms` overhead in Python which doesn't translate well to the task at hand. 

On slower machines it can take seconds for the theme to apply and I actually received a report like this which prompted me to find a faster alternative. The new `cat` method takes `0-1`ms to run on average, it's seamless and doesn't have a chance of blocking the terminal.

I've pushed a new release that adds back the `wal -r` functionality but it still contains the error message warning users that it's deprecated and about how they change to the new syntax. The error message is written to `stderr` whilst the sequences are printed to `stdout` so you can silence the error in `wpgtk` if you'd like.
