### ISSUE TITLE
cat sequence does not work under tmux

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#151]
I've tried with `screen-color256` and `xterm-color256` but neither provided color when doing `cat` on sequences.

**Comment by dylanaraps** [comment]
?

**Comment by deviantfero** [comment]
I realized this is a non-issue, since only a small amount of users log directly into a tmux session, and even in that situation you would do so via `.bashrc` or what have you, where you can do the `cat` before entering the session. thanks for looking into this anyway, if you disagree you can reopen this issue.
