### ISSUE TITLE
Wallpaper is not set

### ISSUE THREAD

**Issue by shizonic** [dylanaraps/pywal#152]
While everything works (every colors change!) the wallpaper itself does not. Even when I run `~/.fehbg` nothing happens.

**Comment by dylanaraps** [comment]
What's your environment like? Are you using a WM/DE?

**Comment by shizonic** [comment]
@dylanaraps No DE only a WMs (i3 & openbox)

**Comment by shizonic** [comment]
As a temporary solution I execute wal like this:
`wal -i /path/to/img.png -o wal-upd` and inside **wal-upd** I have `feh --bg-tile "$(< "${HOME}/.cache/wal/wal")"`.

**Comment by dylanaraps** [comment]
Can you send me the output of `env`?

**Comment by shizonic** [comment]
`ANDROID_HOME=/opt/android-sdk
ANDROID_NDK=/opt/android-ndk
ANDROID_NDK_HOME=/opt/android-ndk
ARCH=x86_64
ARCHFLAGS=-arch x86_64
ARDMK_DIR=/home/tm/.local/src/arduino/contrib/makefile
ARDUINO_DIR=/usr/lib/arduino
AWT_TOOLKIT=XToolkit
BROWSER=google-chrome-unstable
BSPWMRC=/home/tm/.local/etc/bspwm/bspwmrc
BSPWM_FIFO=/home/tm/.cache/bspwm/wm_state
BSPWM_STATE=/home/tm/.cache/bspwm/state.json
CARGO_HOME=/home/tm/.cargo
CODE_HOME=/home/tm/code
COLORFGBG=default;0
COLORTERM=rxvt
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DE=xfce
DISPLAY=:0
DOCKER_REPO_PREFIX=shizonic
EDITOR=nvim
ENV_WORK=1
EXEC_WM=openbox
FONT_PRIMARY=Source Sans Pro
FONT_SECONDARY=Source Sans Pro
FONT_TERMINAL=Source Code Pro
FZF_DEFAULT_OPTS=
    
    
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1

    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1

GIMP2_DIRECTORY=/home/tm/.config/gimp
GITHUB_HOME=/home/tm/code/github
GOPATH=/home/tm/.go
GRADLE_HOME=/usr/share/java/gradle
GREP_COLOR=37;45
GREP_COLORS=mt=37;45
GTK2_RC_FILES=/home/tm/.config/gtk-2.0/gtkrc
GTK_MODULES=canberra-gtk-module
HG=/usr/bin/hg
HOME=/home/tm
INVOCATION_ID=e7ebb55b4e014426bd1a5c7de1f6ecd1
JAVA_HOME=/usr/lib/jvm/default
JOURNAL_STREAM=9:22392
LANG=de_CH.UTF-8
LC_ADDRESS=de_CH.UTF-8
LC_CTYPE=de_CH.UTF-8
LC_IDENTIFICATION=de_CH.UTF-8
LC_MEASUREMENT=de_CH.UTF-8
LC_MONETARY=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
LC_NUMERIC=de_CH.UTF-8
LC_PAPER=de_CH.UTF-8
LC_TELEPHONE=de_CH.UTF-8
LC_TIME=de_CH.UTF-8
LD_LIBRARY_PATH=/usr/lib/
LESS=-g -i -M -R -S -w -K -z-4 --lesskey-file=/home/tm/.config/lesskey
LESSHISTFILE=/home/tm/.cache/.lesshst
LESS_TERMCAP_mb=[01;31m
LESS_TERMCAP_md=[01;31m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_se=[0m
LESS_TERMCAP_so=[00;47;30m
LESS_TERMCAP_ue=[0m
LESS_TERMCAP_us=[01;32m
LOCAL_BIN=/home/tm/.local/bin
LOCAL_ETC=/home/tm/.local/etc
LOCAL_LIB=/home/tm/.local/lib
LOCAL_SRC=/home/tm/.local/src
LOCAL_VAR=/home/tm/.local/var
LOGNAME=tm
LPASS_AGENT_TIMEOUT=0
LPASS_DISABLE_PINENTRY=1
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/spool/mail/tm
MAVEN_OPTS=-Xmx512m
MONPOS=left
MOVIES=/home/tm/media/vids/movies
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
MUSIC=/home/tm/media/music
NOTMUCH_CONFIG=/home/tm/.config/notmuch/config
NO_AT_BRIDGE=1
NPM_HOME=/home/tm/.npm
OLDPWD=/home/tm
PAGER=less
PATH=/home/tm/.local/bin:/home/tm/.local/bin/pacupg:/home/tm/.local/bin/laptopkb:/home/tm/.local/bin/event-driver-cmd:/home/tm/.local/lib:/home/tm/.local/lib/python3.6:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/emulator:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/ccache/bin:/home/tm/.yarn/bin:/home/tm/.cargo/bin:/home/tm/.go/bin
PERLDOC_PAGER=more
PERL_HOME=/home/tm/.local/var/perl
PHOTOS=/home/tm/media/pics/photos
PICS=/home/tm/media/pics
PWD=/home/tm
QT_STYLE_OVERRIDE=GTK+
RUSTUP_HOME=/home/tm/.rustup
SCREENS=/home/tm/media/pics/screens
SHELL=/usr/bin/zsh
SHLVL=5
SSH_AGENT_PID=7390
SSH_AUTH_SOCK=/tmp/ssh-agent.sock.1000
SVDIR=/home/tm/.local/var/service
SVROOT=/home/tm/.local/etc/sv
SXHKD_SHELL=/usr/bin/dash
TERM=tmux-256color
TMUX=/tmp/tmux-1000/default,17885,0
TMUX_PANE=%1
USER=tm
USE_TMUX=1
VIDS=/home/tm/media/vids
VISUAL=nvim
WALLPAPERS=/home/tm/media/pics/wallpapers
WEB_HOME=/home/tm/code/web
WINDOWID=8388618
WINDOWPATH=1
WINEPREFIX=/home/tm/.local/share/wine
WORKON_HOME=/home/tm/.virtualenvs
XAUTHORITY=/home/tm/.Xauthority
XDG_CACHE_HOME=/home/tm/.cache
XDG_CONFIG_HOME=/home/tm/.config
XDG_CURRENT_DESKTOP=XFCE
XDG_DATA_HOME=/home/tm/.local/share
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_ID=c1
XDG_VTNR=1
XKB_DEFAULT_LAYOUT=ch
XKB_DEFAULT_VARIANT=de
YARN_HOME=/home/tm/.yarn
ZDOTDIR=/home/tm/.zsh
_=/usr/bin/env
_JAVA_OPTIONS=-Dother.options=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3
MANPATH=:/usr/local/share/man:/usr/share/man
LC_MESSAGES=C
`

Did you mean this?

**Comment by dylanaraps** [comment]
Are there any `wallpaper:` messages in the terminal when you run `wal`?

**Comment by shizonic** [comment]
Yes!
```
wal -i /path/to/image.png -o wal-upd
image: Using image /path/to/image.png
colors: Found cached colorscheme.
colors: Set terminal colors.
wallpaper: Set the new wallpaper.
export: Exported all files.
export: Exported all user files.
reload: Reloaded environment.
```

**Comment by dylanaraps** [comment]
Weird, that tells me that wal detected a wallpaper setter and ran it.

**Comment by shizonic** [comment]
@dylanaraps Indeed it is weird! I also do not understand why it does not work, but it does NOT... Could you imagine another reason for it?

**Comment by dylanaraps** [comment]
I've got zero clue, you haven't got any envars that would conflict with DE detection so `pywal` should fallback to WM detection and `feh` is the first setter in the list.

**Comment by dylanaraps** [comment]
Can you give me the output of `which feh`?

**Comment by shizonic** [comment]
```
$ which feh
/usr/bin/feh
```

In my i3 WM I do due to proper working xdg-open behaviour:
```
export XDG_CURRENT_DESKTOP=XFCE
export DE="xfce"
```

Could cause this the problem?

**Comment by dylanaraps** [comment]
Yup, that's it.

That's causing `wal` to think you're running xfce.

**Comment by shizonic** [comment]
Okay, damn. How could I prevent wal from that? The problem is: If I do not export these environment variables openbox does not remember my default browser. That's why it's important to have set them... Is there a way to bypass wal's DE detection?

**Comment by shizonic** [comment]
@dylanaraps Solved it by only exporting `export DE="xfce"` instead of
```
export XDG_CURRENT_DESKTOP=XFCE
export DE="xfce"
```
Now my default browser is recognized and wal does set the proper wallpaper! Thank you very much for your help. :-)
