### ISSUE TITLE
URxvt transparency broken?

### ISSUE THREAD

**Issue by awolbox** [dylanaraps/pywal#154]
After the latast update i rebooted and logged back in only to find that there now seems to be a constant solid color on the right side and bottom of URxvt with transparency. I can run `wal -i` and the entire backround will be filled. It's only when i use the `-a` flag that i'm left with about 5 pixels on the right side and 15 on the bottom of solid color, the same color it would be without the `-a` flag.

**Comment by dylanaraps** [comment]
Fixed!
