### ISSUE TITLE
IntelliJ terminal not working

### ISSUE THREAD

**Issue by yoannfleurydev** [dylanaraps/pywal#155]
By setting this line in my `~/.zshrc`: 

```bash
(cat ~/.cache/wal/sequences &)
```

or the alternative one:

```bash
cat ~/.cache/wal/sequences
```

the IntelliJ terminal is not working (not giving the prompt back). By commenting the line, it's working.
Here is a screenshot of the prompt with the commented line:
![no-pywal-issue-intellij](https://user-images.githubusercontent.com/3920615/34513476-bef36c3a-f068-11e7-8a8a-819219e9f865.png)
And here is a screenshot of the prompt with the uncommented line:
![pywal-issue-intellij](https://user-images.githubusercontent.com/3920615/34513491-d29a5afa-f068-11e7-90e1-dcf1abd0ae6f.png)

Note that before the `-r` deprecation, this was working as expected (even if the terminal colors were overridden by Intellij's color scheme.

Hope there are enough details in this report.

**Comment by dylanaraps** [comment]
So the colors never worked in IntelliJ they just didn't hang the terminal like they do now?

**Comment by yoannfleurydev** [comment]
Yes, colors never worked before in IntelliJ, but I got the prompt back when using `-r` instead of the new way to handle the sequence. 🤔
So it was fine to me because I have full theme on IntelliJ and colors worked on other terminal.

**Comment by dylanaraps** [comment]
What's the easiest way for me to reproduce this? ie installing IntelliJ?

**Comment by yoannfleurydev** [comment]
I think installing IntelliJ is the best way to reproduce this issue, in my opinion. 
Here is my version:

```
IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 25, 2017
Licensed to Smartpanda / Yoann Fleury
Subscription is active until August 17, 2018
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.10-1-ARCH
```

But the [Community Edition](https://www.jetbrains.com/idea/download/download-thanks.html?platform=linux&code=IIC) will probably do the same.

**Comment by yoannfleurydev** [comment]
I'll close this issue as it is resolved using the latest IntelliJ version. There is no more problem with the prompt not showing in IntelliJ's Terminal.

![bitmoji](https://render.bitstrips.com/v2/cpanel/3c97455d-0ce1-4ac8-82a0-601e6d6f6fd2-d9ac9202-f0c1-4a4f-9148-545e258070eb-v1.png?transparent=1&palette=1&width=246)

Here is the version of IntelliJ currently working if someone needs more details:
```
IntelliJ IDEA 2018.2.3 (Ultimate Edition)
Build #IU-182.4323.46, built on September 3, 2018
Licensed to Smartpanda / Yoann Fleury
You have a perpetual fallback license for this version
Subscription is active until August 18, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.5-arch1-1-ARCH
```
