### ISSUE TITLE
Replicate wal -t behaviour?

### ISSUE THREAD

**Issue by MrHuds0n** [dylanaraps/pywal#156]
Since the cat sequence was added and `wal -rt` deprecated, I can't figure out how to prevent the jumbled text appearing in every new terminal (using termite as the emulator).

```
# .zshrc
(cat ~/.cache/wal/sequences &)
```

Results in this in every new terminal.

```
]708;#0F0E19%                                                                                          
λ heartbeat [~] :: 
```

**Comment by dylanaraps** [comment]
Run `wal -c` then run `wal` normally.

**Comment by MrHuds0n** [comment]
Nope, this still leaves me with the jumbled text.

**Comment by dylanaraps** [comment]
Are you on `1.0.0`+?

**Comment by MrHuds0n** [comment]
Yeah.

```
λ heartbeat [~] :: wal -v       
wal 1.1.0
```

**Comment by dylanaraps** [comment]
What's the contents of this file: ~/.cache/wal/sequences`?

**Comment by MrHuds0n** [comment]
Ah, turns out I'm a little bit of a fool, reloading the colourscheme with the same image seems to have fixed the problem. Thank you for the help regardless :)
