### ISSUE TITLE
Setting the background color with -b

### ISSUE THREAD

**Issue by Bluedrack28** [dylanaraps/pywal#158]
I tried to set the background color this way `wal -b #000000` but the way that worked was `wal -b#000000` which is for me not the most intuitive for a command line.
I just want to share my user opinon.
Thank you for everything.
My version is the 1.0.3

**Comment by dylanaraps** [comment]
You need to quote the argument `-b "#000000"`. Without the quotes, your shell treats `#` as the start of a comment.
