### ISSUE TITLE
Invisible visual block in vim

### ISSUE THREAD

**Issue by osum4est** [dylanaraps/pywal#160]
Using the vim plugin, whenever I try to select something in visual mode, it turns the same color as the terminal background (invisible).

**Comment by deviantfero** [comment]
you could set your own background color for visual with something like `hi visual ctermbg=4 ctermfg=0` and then set it in your .vimrc if you don't like and aspect of the theme, but I guess that's also a possible solution for the theme itself if it's an issue for other people.

**Comment by dylanaraps** [comment]
Update the theme and let me know if it's any better.

**Comment by osum4est** [comment]
Works like a charm now, thanks!
