### ISSUE TITLE
[enhancement request] Reload bumblebee-status

### ISSUE THREAD

**Issue by ltgouvea** [dylanaraps/pywal#162]
Current behaviour: pywal runs, everything works and colorscheme gets loaded on all terminals, but [Bumblebee-Status](https://github.com/tobi-wan-kenobi/bumblebee-status/) remains with the previous colorscheme until I force reload i3  with `$mod+Shift+r`.

Desired effect: When i3 reloads, bumblebee gets reloaded as well with the new colorscheme, as in when using Polybar

Thanks! :D

**Comment by dylanaraps** [comment]
pywal only reloads the i3 config file. To update bumblebee-status' I'd need to change pywal to restart i3. I'm not going to do this as it's more prone to interfering with peoples setups.

You can just write a script that restarts i3 and call it using `wal -i img.jpg -o script`.

**Comment by ltgouvea** [comment]
It worked flawlessly with a 2 line little script! So sorry for my laziness :laughing:
