### ISSUE TITLE
pywal not working in debian

### ISSUE THREAD

**Issue by FushPush** [dylanaraps/pywal#163]
Installed pywal using pip3 install pywal, so now im trying to use the command wal -i [PICTURE] but i keep getting this: bash: wal: command not found, did i do something wrong or is debian not supported?

**Comment by pydo** [comment]
Did you try installing the package in your global sites packages without `sudo`?
Try creating a new virtualenv `virtualenv -p python3 env` and then installing it from there.

**Comment by FushPush** [comment]
solved it by first chrooting it when it was in .local/bin/wal(.py?), then i moved the file to /usr/share/local/bin, then it just works for some reason

**Comment by BrianD91** [comment]
I am encountering this same issue in Kubuntu 18.04

**Comment by Lalit64** [comment]
Encountering this issue with macOS
