### ISSUE TITLE
[enhancement request] Add a saturation option

### ISSUE THREAD

**Issue by gillescastel** [dylanaraps/pywal#166]
It would be nice to have color schemes with more (or less) saturation.

There are multiple possibilities: 

* Add `x` to the saturation of each color,
* Change the saturation of each color with `x`%,
* Change the saturation of each color to a fixed amount.

**Comment by exic** [comment]
@zol0 did you find a solution for that yet?

**Comment by deviantfero** [comment]
If it could be accessed with the pywal API it would be awesome too!

looking forward to it.

**Comment by dylanaraps** [comment]
Done.

Added `--saturate` which takes a float.
