### ISSUE TITLE
rofi changed theme engine

### ISSUE THREAD

**Issue by tim241** [dylanaraps/pywal#167]
rofi uses the `rasi` format, the `Xdefaults`/`Xresources` method is outdated
https://github.com/DaveDavenport/rofi/blob/next/doc/rofi-theme.5.markdown
I'd like to request an update to use the new rofi theme method.

**Comment by dylanaraps** [comment]
My laptop charger has broken and I’m waiting for a replacement. Till then I’m unable to work on any of my projects. 

This will be implemented as soon as I can boot my laptop.

**Comment by dylanaraps** [comment]
Added in https://github.com/dylanaraps/pywal/commit/3c41e8da4718f5abd12b1592a896242748f67d32.

Instructions will be added to the wiki shortly.

**Comment by dylanaraps** [comment]
Docs: https://github.com/dylanaraps/pywal/wiki/Customization#rofi
