### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by boardfish** [dylanaraps/pywal#168]
I'm aware `pywal` uses `oomox` as a dependency, and that has support for theming the Spotify app if it's possible. Waiting on them for a fix as [`oomoxify-cli` is currently broken](https://github.com/actionless/oomox/issues/119), but I'm happy to patch this in myself once it's there. I'm fairly sure it's as simple as executing the `oomoxify-cli` command with the file `pywal` exports for the standard `oomox` command to use, *provided* Spotify is installed on the system.

Also, would we just check to see if Spotify is installed in some way, or just run `oomoxify-cli` while silencing the output and see what flag it returns?

**Comment by boardfish** [comment]
`oomoxify-cli` is now fixed thanks to a misreference in the project's README.md, so I'll test it myself and potentially open a pull request soon.

**Comment by boardfish** [comment]
Upon further inspection, `oomoxify-cli` is registered as being in the user's `PATH` but `cd`s to `oomox`'s root directory rather than that of its plugins. I've commented on the original issue in hopes of this being fixed, and at that point it'll be safe to load the generated `oomox` colors into the script.

**Comment by vKnmnn** [comment]
Does changing the spotify theme work for you via GUI?

**Comment by boardfish** [comment]
Sorry, this fell by the wayside for me and it turns out it's actually `oomox`/@actionless's problem that they've since [fixed](https://github.com/actionless/oomox/issues/119). Issue isn't yet closed (my bad) but I'm now ready to open a PR for this one.

**Comment by dylanaraps** [comment]
You can easily add Spotify support by using `-o` with a custom script.

Example:

```sh
#!/usr/bin/env bash
oomoxify-cli -g ~/.cache/wal/colors-oomox

if pgrep spotify; then
    pkill spotify
    spotify
fi
```

Caveat: This requires `sudo` and will open a `gksu` window to authenticate. This is why this won't be added to `pywal` directly.

**Comment by actionless** [comment]
remove `-g` option

**Comment by dylanaraps** [comment]
It still requires sudo. Using -g opens a gksu window which works even if the script is run in the background.

**Comment by actionless** [comment]
mb try https://rosettacode.org/wiki/Check_input_device_is_a_terminal#Python

**Comment by boardfish** [comment]
I got it working by just adding the `oomoxify-cli` call after the standard `oomox` call, but it doesn't relaunch Spotify.
