### ISSUE TITLE
using css in stylish

### ISSUE THREAD

**Issue by vKnmnn** [dylanaraps/pywal#171]
Hi Dylan,

today i tried setting my startpage to use wal colors via stylish in Firefox. The method described in the wiki does not work. Stylish expects a Hex value and gives a warning when i try to use `var ( --background)`

Can you point me in the right direction?

**Comment by dylanaraps** [comment]
Can you send me a copy of your stylesheet?

**Comment by Cimaje** [comment]
Hi, I am having the same issue. In fact most web pages default to white if I try to import the colors.css file from pywal. Any advice?

**Comment by deviantfero** [comment]
Have you tried asking in the discord channels? maybe the community might be
able to help you out.

-- att. Fernando Vasquez --

**Comment by golam71** [comment]
how was it fixed?
