### ISSUE TITLE
Cannot start with i3 | works fine from console

### ISSUE THREAD

**Issue by fusion4bass** [dylanaraps/pywal#173]
Hi,

I've seen similar issue in wal:
https://github.com/dylanaraps/wal/issues/42

But it was fixed by modyfing kill_old() function so I guess that's not it.

What happens is I can run wal from console but not from i3 startup nor bindkey.
I'm using pywal 1.2.2 on ARCH Linux guest OS on VirtualBox with Guest Additions and this happens:

- bind key in i3 to run wal
- hit key
- x11/i3 (or both?) crashes and screen goes back to console
- I hit "ctrl+F" which is shortcut to change display mode from fullscreen to window on virtualbox
- once guest OS is in window mode, i3 comes back to life with newly loaded pywal colorscheme and wallpaper

It might have something to do with resolution change once display mode is changed.

I've tried to look into i3 dump log to check if that's i3 problem but couldn't find any clue.
[i3-dump-log.txt](https://github.com/dylanaraps/pywal/files/1679221/i3-dump-log.txt)

**Comment by fusion4bass** [comment]
Definitely problem of pywal as same thing occur when I run it through xinit

>user ~ % cat .xinitrc 
VBoxClient-all
#wal -i ~/Pictures/Wal/current
~/.wal &
exec i3

**Comment by dylanaraps** [comment]
What’s ~/.wal?

**Comment by fusion4bass** [comment]
Sorry, I didn't make it clear :)

~/.wal was my attempt to start it not directly but via shell script

> #!/bin/sh
'wal' '-i' '/home/user/Pictures/Wal/sw-xwings.jpg' 

but same thing happens with 

>user@computer ~ % cat .xinitrc 
VBoxClient-all
wal -i ~/Pictures/Wal/current

**Comment by BenKugler** [comment]
I have experienced the same issues on two different Arch Linux Virtual Box installs.

**Comment by joaocmd** [comment]
Same happening here, and found similar thread on [reddit from 4 months ago](https://www.reddit.com/r/i3wm/comments/72t11d/unable_to_run_pywal_on_i3_startup_or_from_key/)

**Comment by fusion4bass** [comment]
Found workaround by creating a systemd/user service

>user@computer ~/.config/systemd/user % cat pywal.service
[Unit]
Description = Restore pyWal colorscheme from last session
After = graphical.target
[Service]
Type=oneshot
ExecStart=/usr/bin/wal -R
RemainAfterExit=true
Environment="DISPLAY=:0"
[Install]
WantedBy=default.target

I had to pass  DISPLAY environment, without it I got "xrdb, can't open display".

**Comment by Burninator448** [comment]
I'm having the same problem using bspwm in VirtualBox Arch VM with guest additions installed. If I run pywal through .xinitrc or bspwmrc it loads up and then seems to crash once pywal runs. It also exits if I bind it using sxhkd. I've tried using both `wal -i $HOME/Pictures/Wal/kiminonawa1.png` and `wal -R`.

**Comment by angarod** [comment]
maybe the configuration of .xinitrc is overrided by .xprofile or another config file from Xorg. Try put your configuration in these files.

**Comment by dylanaraps** [comment]
So from what I gather; pywal crashes when run from VirtualBox VMs?

I'm going to write a little test script to see if it reproduces the issue.

**Comment by dylanaraps** [comment]
Run this script and let me know if it crashes your VMs.

```sh
#!/bin/bash

read -rd '' sequences <<'EOF'
]4;0;#1a1f17\]4;1;#aa7758\]4;2;#82a969\]4;3;#90a981\]4;4;#7baa7c\]4;5;#9aa89c\]4;6;#80aa90\]4;7;#c5c7c5\]4;8;#535751\]4;9;#aa7758\]4;10;#82a969\]4;11;#90a981\]4;12;#7baa7c\]4;13;#9aa89c\]4;14;#80aa90\]4;15;#c5c7c5\]10;#c5c7c5\]11;#1a1f17\]12;#c5c7c5\]13;#c5c7c5\]17;#c5c7c5\]19;#1a1f17\[s[1000H[8m]708;#1a1f17\[u]13;#c5c7c5\\
EOF

for term in /dev/pts/[0-9]*; do
    [[ -w "$term" ]] && printf "%b" "$sequences" > "$term" &
done
```
