### ISSUE TITLE
cache files are deprecated in each pywal release

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#176]
Hi @dylanaraps I was taking a look at the new naming convention for the cache_file for each image, I noticed that with this way of differentiating the files, the users will lost all changes in a color-scheme with each new release of `pywal`, as they will be ignored and a new one will be generated, I have two suggestions that might help avoid this issue.

* handle cache file versions separately from `pywal`'s version,
so instead of appending `pywal.__version__` you could append something like `pywal.__cache_version__`, which would only change each time there's a breaking change in the way you do cache files.

* be able to specify a custom cache_file name to `color.get()` to allow `wpgtk` or other software that relies on `pywal` to decide it's own naming convention

I personally believe that my first suggestion is the best of the two, it's simpler and will please your users too (not loosing their color-schemes on each update).

I've done a PR #177 to implement this, please let me know your thoughts on this matter.

anyway, thanks for reading!

**Comment by dylanaraps** [comment]
Fixed in #177
