### ISSUE TITLE
Comments in vim are not grey anymore in 1.3.0.

### ISSUE THREAD

**Issue by T-Rex96** [dylanaraps/pywal#178]
I'm using the wal plugin for vim. Usually, comments would be displayed in a grey-ish color, but since the latest version they are just the normal color. zsh-autosuggestions has the same issue. Screenshot:

Before (1.2.3):

![before](https://user-images.githubusercontent.com/13141438/35781606-ad895264-09ec-11e8-8ea8-5cf4f2fced0b.png)

After (1.3.0)

![after](https://user-images.githubusercontent.com/13141438/35781610-bb3b9bce-09ec-11e8-8779-63e81159a958.png)

**Comment by dylanaraps** [comment]
Fixed, thanks!
