### ISSUE TITLE
Rofi prompt change with rofi.theme

### ISSUE THREAD

**Issue by AndrewOlsen** [dylanaraps/pywal#179]
```
$ rofi -v
Version: 1.5.0-dirty (tags/1.5.0)

$ wal -v
wal 1.3.2
```
Enabling the wal theme via the new ~/.config/rofi/config file removed the colon and space in the prompt.

Here is rofi without the theme enabled:
![notheme](https://u.teknik.io/wlZDC.png)

And here it is with the theme enabled:

![theme](https://u.teknik.io/HLp7k.png)

**Comment by Bluedrack28** [comment]
I don't see the problem but if you want to resolve the problem, you could overwrite the rofi config with this [template](https://github.com/dylanaraps/pywal/blob/master/pywal/templates/colors-rofi-dark.rasi) and place in your file .config/wal/templates/. It's really easy, it's a bit like css.

**Comment by dylanaraps** [comment]
Fixed.
