### ISSUE TITLE
Colorscheme not working on rofi

### ISSUE THREAD

**Issue by AUTplayed** [dylanaraps/pywal#183]
After updating rofi and pywal to the newest version the color scheme doesn't apply to it anymore.

I'm not really sure what I should provide for it to be reproducable tho, so far I tried:

- rebooting
- reinstalling both pywal and rofi
- pacman -Syu

**Comment by AUTplayed** [comment]
1.5.0-dirty

**Comment by ltgouvea** [comment]
Got the same issue occurring on Rofi version 1.2.0

**Comment by Clyybber** [comment]
It now requires some manual configuration(providing more customizability):
https://github.com/dylanaraps/pywal/wiki/Customization#rofi

**Comment by AUTplayed** [comment]
works great, thanks
