### ISSUE TITLE
UnicodeDecodeError: 'utf-8'

### ISSUE THREAD

**Issue by Allyriadil** [dylanaraps/pywal#185]
After using a template for rofi in .config/wal/templates this error appears upon setting the colors. I am using the default template suggested in the wiki.

> wal -R
>   File "/usr/bin/wal", line 11, in <module>
>     load_entry_point('pywal==1.3.2', 'console_scripts', 'wal')()
>   File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 159, in main
>     process_args(args)
>   File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 143, in process_args
>     export.every(colors_plain)
>   File "/usr/lib/python3.6/site-packages/pywal/export.py", line 64, in every
>     template(colors, file.path, join(output_dir, file.name))
>   File "/usr/lib/python3.6/site-packages/pywal/export.py", line 13, in template
>     template_data = util.read_file_raw(input_file)
>   File "/usr/lib/python3.6/site-packages/pywal/util.py", line 57, in read_file_raw
>     return file.readlines()
>   File "/usr/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte

**Comment by dylanaraps** [comment]
Send me your template file

**Comment by Allyriadil** [comment]
I am using the default template provided by pywal.

**Comment by anonymous133** [comment]
@Allyriadil @dylanaraps

Hi! 
I stumbled about the same issue. In my case vim created a swap file in the template folder which caused the error. Maybe pywal could ignore *.swp files.

**Comment by dylanaraps** [comment]
Will do.

**Comment by dylanaraps** [comment]
Done.
