### ISSUE TITLE
gtk error

### ISSUE THREAD

**Issue by Mati20187** [dylanaraps/pywal#188]
After this command, terminal scheme doesn't change. oomox is installed. What should I do to fix gtk error?

$ sudo wal -i saturn.jpg 
image: Using image /home/mati/Pictures/saturn.jpg
colors: Found cached colorscheme.
wallpaper: Set the new wallpaper.
\\\\\\\\\\\\\\\\\\\\\\colors: Set terminal colors.
export: Exported all files.
export: Exported all user files.
reload: Reloaded environment.
gtk: Use -g to generate an oomox theme.

When I try -g : 

$ sudo wal -g
gtk: oomox not found, skipping...

**Comment by Minda1975** [comment]
Why you use sudo?
