### ISSUE TITLE
support for qt5

### ISSUE THREAD

**Issue by angarod** [dylanaraps/pywal#189]
Some applications like keepassxc and nextcloud client are not support by pywal because of qt5.
I have used qt5ct for changing the qt5 theme, pick the gtk2 theme (wal) and the result is not as beautiful as the gtk theme.

Any solution for that ? Or did i something wrong ?
Thanks !

**Comment by dylanaraps** [comment]
Themes are handled by oomox, this isn't a pywal issue. Open an issue on oomox's tracker.
