### ISSUE TITLE
Highlighting doesn't appear on termite.

### ISSUE THREAD

**Issue by gib98** [dylanaraps/pywal#190]
After running wal, when I am selecting text in termite, it works, but there is no way to know what is selected.

**Comment by mlueck88** [comment]
Confirmed for mate-terminal and roxterm.
It seems that selected text is turned white (i.e. the corresponding equivalent in the colorscheme), which works as highlighting for every other color, but most text in the terminal is white.

**Comment by dylanaraps** [comment]
Fixed. Sorry for the delay.
