### ISSUE TITLE
Help connecting pywal to rofi

### ISSUE THREAD

**Issue by GauravChaddha1996** [dylanaraps/pywal#191]
I'm using Ubuntu 17.10 with wayland. I want to theme my rofi based on color scheme generated by pywal. How do I go on to do this? I'm able to run wal and see that color scheme is generated using "xrdb -query". Is there a way to use these colors in my .Xresources and theme rofi from there?

**Comment by GauravChaddha1996** [comment]
For example this is my current .Xresources. How do I get color "#A31F22" in rofi.color-normal hlfg to be replaced by variable color1 whose value changes with pywal (#A31F22 is the current color of $color1). What's the syntax?
```
rofi.location:          0
rofi.color-enabled:     true
!                       'background', 'border'
rofi.color-window:       #e60e0304, #e60e0304
! State:                'bg',          'fg',   'bgalt',       'hlbg',        'hlfg'
rofi.color-normal:      argb:00333333, #ffffff, argb:00333333, argb:00333333, #A31F22
rofi.color-urgent:      argb:00333333, #ffffff, argb:00333333, argb:00333333, #A31F22
rofi.color-active:      argb:00333333, #ffffff, argb:00333333, argb:00333333, #A31F22
rofi.separator-style:   dash
rofi.fullscreen:        true
rofi.padding:           300
rofi.hide-scrollbar:    true
rofi.line-margin:       5
rofi.fake-transparency: false
rofi.yoffset:           0
rofi.xoffset:           0
rofi.width:             1366
rofi.opacity:           90
rofi.font:              SourceCodePro-Regular 12
```

**Comment by dylanaraps** [comment]
Read the rofi section of the Wiki. You need to enable the theme in your rofi config file.
