### ISSUE TITLE
-g flag throwing an error

### ISSUE THREAD

**Issue by wilberanderson** [dylanaraps/pywal#192]
Whenever I try to use the -g flag (for the oomox theme), it throws this error, regardless of the wallpaper I have.

`$ wal -g`
`reload: Waiting for oomox...`
`Error: 0.25294 isn't a valid CSS value.`
`        on line 340 of gtk-3.20/scss/widgets/_view.scss`
`>>   border: 1px solid alpha($borders_color, (lightness($bg_color))/100% + .2);`
`   ------------------------------------------^`
`make: *** [css_gtk320] Error 1`

I'm using the most recent version of pywal from pip3, 1.3.2
I'm also on the most recent oomox, 1.5.0-1

**Comment by dylanaraps** [comment]
This is an oomox error and is unrelated to pywal. Open an issue on oomox’s tracker.
