### ISSUE TITLE
rofi 1.5.0+ don't show colon in theme properly

### ISSUE THREAD

**Issue by clearnote01** [dylanaraps/pywal#194]

**Comment by clearnote01** [comment]
```
#inputbar {{
    padding: 1px;
    children: [ prompt,textbox-prompt-colon,entry,case-indicator];
}}

#textbox-prompt-colon {{
    expand: false;
    str: ":";
    margin: 0px 0.3em 0em 0em;
    text-color: @normal-foreground;
}}

```

Adding the code above in rofi theme template will fix the issue.

**Comment by dylanaraps** [comment]
The templates do include the colon no?

**Comment by clearnote01** [comment]
With the latest version rofi, current template doesn't show colon.

**Comment by dylanaraps** [comment]
I’m saying it’s already fixed in the -git version. I’ll push a new release
with the fix tomorrow.

**Comment by clearnote01** [comment]
Well, I suppose then I was using an earlier version of pywal from AUR which didn't show colon.
Obviously, the current code does have the colon in the template. 

Sorry for the unnecessary issue, I should close this then?

**Comment by dylanaraps** [comment]
Yeah 😄
