### ISSUE TITLE
Repo of Popular Colorschemes

### ISSUE THREAD

**Issue by blahsd** [dylanaraps/pywal#198]
I've found out that it's way more convenient, rather than applying even popular colorschemes and themes, such as Solarised, Zenburn, etc. to just `wal` away instead of finding the correct theme for each of my programs. 

My point is: should we put all of these together and have a repo of popular schemes for wal?

**Comment by dylanaraps** [comment]
I've started working on it in #200.

**Comment by blahsd** [comment]
I was about to say that I must be blind not to have seen that – then I realise *when* you started it. hehe. Glad to have contributed a good idea, if I did – I'll move on to contribute some good PRs, if I can.
