### ISSUE TITLE
[Possible feature request] Get alternative schemes from same picture file

### ISSUE THREAD

**Issue by irvall** [dylanaraps/pywal#201]
I really enjoy Pywal first and foremost! Is it currently possible to get alternate colour schemes from the same photo? Some photos I've tried out are not using the most, IMO, exciting colours from a given photo so would love a function like this. Maybe a function to "randomize" what colour goes where (background, bold text, and so on).

Thanks!

**Comment by dylanaraps** [comment]
pywal now has 5 total color backends so I think it's ok to close this.
