### ISSUE TITLE
[Feature request] Exclude `colors-tty.sh` from being loaded

### ISSUE THREAD

**Issue by khoacao96** [dylanaraps/pywal#202]
Right now `colors-tty.sh` in `.cache/wal/` are being loaded by default. Could there be an option to exclude this file from being loaded? I don't want my tty's colors to change when I'm using a colorscheme.

My only workaround so far is to include an empty `colors-tty.sh` (with only one line: `#!/bin/sh`) inside `.config/wal/templates/` to override the default behavior. It does work, but I hope it can be implemented officially like the `-s` parameter.

And also, thank you for your work with `pywal`!

**Comment by dylanaraps** [comment]
Fixed in https://github.com/dylanaraps/pywal/commit/2e0ab26d7542dec0657c06d431e674de01856228

Use `-t` to skip tty colors.
