### ISSUE TITLE
Error generating custom background color

### ISSUE THREAD

**Issue by Anode194** [dylanaraps/pywal#203]
Sorry if this is user error but Everytime I try and set a custom background color I get this error:

 wal -b "#ffffff"
Traceback (most recent call last):
File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==1.3.2', 'console_scripts', 'wal')(File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 159, 
    process_args(args)
File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 133, 
    colors_plain["special"]["background"] = args.b
UnboundLocalError: local variable 'colors_plain' referenced before assi

I hope this helps.

**Comment by dylanaraps** [comment]
You still need to specify an image or file input for colors. (`-i` or `-f`)
