### ISSUE TITLE
chunkwm integration

### ISSUE THREAD

**Issue by blahsd** [dylanaraps/pywal#206]
First off, thanks for the incredible tool. 

Secondly, on my setup I have chunkwm sourcing the colors for window borders from pywal's files. If you care for it, I could write a wiki entry on how to set it up.

**Comment by dylanaraps** [comment]
Please do!

**Comment by blahsd** [comment]
### chunkwm

To use `wal` with chunkwm you need to modify chunkwm's configuration file (`~/.chunkwmrc`) in order to include colors from an different file, so that it includes this lines: 

```source .cache/wal/chunkwmcolors

NFOCUS=$(echo $FOCUS | sed 's/#//')
NPRESE=$(echo $PRESE | sed 's/#//')

chunkc set preselect_border_color        $NPRESE
chunkc set focused_border_color          $NFOCUS```

Furthermore, you need to define a new pywal template here: `.config/wal/templates/chunkwmcolors` that reads so:

```FOCUS=0xff{color2}
PRESE=0xff{color1}```

substituing {color1} and {color2} for whichever colros in your coloscheme you'd like to use for, respectively, the preselected window border and the focused window border.

**Comment by ubuntudroid** [comment]
FYI: I reworked the instructions a bit to clarify paths and color names.
