### ISSUE TITLE
A way to hide the caret/change its color.

### ISSUE THREAD

**Issue by Kommynct** [dylanaraps/pywal#211]
I can't find anything in the css that allows me to do this, and its really the only thing I don't like about my current theme.

thank you.

**Comment by dylanaraps** [comment]
Can you please elaborate? I don't understand what this issue is about.

**Comment by Kommynct** [comment]
I have literally no idea how I managed to post here. I don't even know what this program is. This was an issue for something else. I now fear I'm schizophrenic.
