### ISSUE TITLE
Question: Variety + feh + pywal, will it be possible?

### ISSUE THREAD

**Issue by thyeun** [dylanaraps/pywal#214]
OS : Arch Linux
WM : i3-gaps, i3-blocks
terminal : urxvt
fm : ranger

my intention are, while variety auto change the background wallpaper, it will trigger pywal for the terminal color change and not sure feh can be use as a middle man to connect in-between variety and pywal if needed (or feh are no need)

my current setting are variety + feh, without feh, variety wont be trigger for each hours automatically changing background wallpaper.

i been trying it now, but sadly, can't make it wonk, and not sure either is variety or feh or pywal not set correctly.

so, if someone come across of this, pls kindly guide me on. thanks you so much

p/s : sorry if i'm not allow to ask question here, than just trigger me, i will close it.

**Comment by dylanaraps** [comment]
Run `wal` with `-n` and follow the docs:

> If you want to run custom commands every time the wallpaper changes or if you use an alternative desktop environment, please edit the scripts in ~/.config/variety/scripts. There are examples there for various desktop environments.

**Comment by thyeun** [comment]
@dylanaraps, not working with variety even using ```wal -n```, meaning that when variety change the wallpaper, it wont trigger ```wal -n```

**Comment by thyeun** [comment]
@dylanaraps, =.= finally make it working with variety, everytime variety change the background wallpaper, pywal will change also. 

so happy now, and thank you so much!!! really love pywal~

**Comment by trillex** [comment]
@thyeun, can you share how you managed to get it to work? Anything I do in set_wallpaper seems to not be fired.

**Comment by thyeun** [comment]
@trillex go to ```~/.config/variety/scripts/set_wallpaper``` 

add this ```wal -i "$WP" -g```

into the line below

```# i3-wm/Feh. Use Feh only for i3, as it may cause problems with Nautilus, (see bug https://bugs.launchpad.net/variety/+bug/1047083)
if [ "$XDG_CURRENT_DESKTOP" == "i3" ] || [ "$XDG_SESSION_DESKTOP" == "i3" ]; then
    #feh --bg-fill "$WP" 2> /dev/null
    wal -i "$WP" -g
fi```

than change the ```WP = $3```

**Comment by thyeun** [comment]
@trillex, so each time variety auto change the wallpaper, pywal will change also, u can set time to change wallpaper on variety, let say you set wallpaper change 10mins, than each 10mins, pywal will change

![screenshot_2018-04-12_15-29-46](https://user-images.githubusercontent.com/1939446/40008580-3923f684-57d2-11e8-91d1-5097476e7a0d.jpg)

**Comment by trillex** [comment]
Thanks for the prompt answer! I actually managed to get it to work but surprised it is so different from yours.

Essentially, before the $WP = $1, I put in:

`python3 /home/username/.local/bin/wal -i $3 -n -q`

I have pywal installed as user, so not sure if that was why it was failing to call wal directly from the script. 

But, we both got it working in the end and that's the important bit. :)
