### ISSUE TITLE
i3wm-gaps and i3blocks not working after upgrade to pywal version 2.0.0

### ISSUE THREAD

**Issue by thyeun** [dylanaraps/pywal#219]
OS : Arch Linux
pywal : 2.0.0
WM : i3wm-gaps and i3blocks

My issue have to explain into two type of changing

Auto mode changing using ```Variety```
Before upgrade to ```pywal 2.0.0```, i'm using ```pywal 1.3.3```, below is the explain of the result (before upgrade)
- Terminal, gtk, i3wm-gaps, i3blocks and everything that pywal can change, it will automatically change once variety change the background wallpaper.

After upgrade to pywal 2.0.0
- Terminal. and gtk will change, once variety change the background wallpaper.
- i3wm-gaps and i3 blocks **won't** change. (this is current i'm facing this issue)

---------------------------------------------------------------------------------------------------------------------

Manually mode changing using ```wal -i abc.jpg -g```
Before upgrade to ```pywal 2.0.0```
- everything will change.

after upgrade to ```pywal 2.0.0```
- everything will change.

so what i'm missing out for pywal 2.0.0? =.= 8 hours ago, it work like charm, now it not possible to make i3wm-gaps and i3blocks change!!

**Comment by dylanaraps** [comment]
Fixed.

**Comment by thyeun** [comment]
@dylanaraps, still one things, not sure either is related with pywal 2.0.0 or not, but for 1.3.3 i didn't see it appear

when i **enable** pywal
each minutes look like pywal are triggering something on the behind because i3wm-gaps and i3blocks will blink every minutes. 

and there are no changing on colorscheme, just blink every minutes on i3wm-gaps and i3blocks, others not affected.

when i **disable** pywal
that every minutes blink gone, so i'm sure it is related with pywal. but not sure it is happen only on pywal 2.0.0 or older version 1.3.3 also. (because 1.3.3 i didn't notice it).

**Comment by thyeun** [comment]
@dylanaraps sorry, it is not pywal issue, my mistake!
