### ISSUE TITLE
Weird line appearing after prompt on Tilix

### ISSUE THREAD

**Issue by Clyybber** [dylanaraps/pywal#22]
If entering a commend after that it says "command not found: to"
It seems like wal is not launched in the bg. Im using the instructions from the readme.
Im using zsh

**Comment by dylanaraps** [comment]
Can you send me your `.zshrc`? I can't reproduce this.

**Comment by dylanaraps** [comment]
Try changing `(wal -r &)` to `setsid wal -r`.

Does the new command work?

**Comment by Clyybber** [comment]
Here is my .zshrc

`if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

PROMPT="%1d >  "

setsid wal -r
`
It doesn't make a difference changing out the commands.
[Screenshot](http://imgur.com/a/oBWPH)

**Comment by Clyybber** [comment]
It also happens when entering
(wal -r &)
or 
setsid wal -r
in the terminal manually.

**Comment by dylanaraps** [comment]
Add `-t` to all of your `wal` commands, see the help page for what `-t` does.
