### ISSUE TITLE
[feature request] - some way of knowing if the colorscheme was generated or caught from cache

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#220]
I'm having this issue in `wpgtk` implementing the backends functionality, where if I already have a different colorscheme generated by another backend I can't update my 'sample' image accordingly, this is because I have no pragmatic way of knowing if the colorscheme was found in cache or generated, I would appreciate any input on this, thanks @dylanaraps

**Comment by dylanaraps** [comment]
I can add a field to the `dict` that states whether or not the scheme was pulled from the cache.

Something like this:

```py
# If it was pulled from the cache.
colors["cached"] = True

# If it wasn't
colors["cached"] = False
```

Then you can just check the value of the field.

How does this sound?

**Comment by deviantfero** [comment]
I think it would be nice, but it would only save me a `isfile`, so I guess i'll do it that way, checking if there was a JSON file before getting the colors, and if there wasn't I'd generate a sample image, that way I save you the trouble, sounds ok right? I hadn't thought about it.
