### ISSUE TITLE
Upgrading to pywal 2.0.2 breaks the command

### ISSUE THREAD

**Issue by blahsd** [dylanaraps/pywal#221]
I just updated through pip, but it looks like this broke the wal command by making the binary in /usr/local/bin disappear. This is on osx 10.13.

So right now I have the following:

```/usr/local/bin
❯ pip --version
pip 9.0.3 from /usr/local/lib/python3.6/site-packages (python 3.6)

/usr/local/bin
❯ pip install pywal
Collecting pywal
Installing collected packages: pywal
Successfully installed pywal-2.0.2

/usr/local/bin
❯ pip show pywal
Name: pywal
Version: 2.0.2
Summary: Generate and change colorschemes on the fly
Home-page: https://github.com/dylanaraps/pywal
Author: Dylan Araps
Author-email: dylan.araps@gmail.com
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires:

/usr/local/bin
❯ wal
zsh: command not found: wal

/usr/local/bin
❯ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

/usr/local/bin
❯```

**Comment by dylanaraps** [comment]
Nothing in the code changes since 2.0 affected the installation. I’m not sure if this is a pywal issue. 

Can anyone else reproduce?

**Comment by blahsd** [comment]
Shit, my bad then, I had the binary in /usr/local/bin but I guess I was the one who symlinked it there and just forgot about it. Sorry for wasting your time.
