### ISSUE TITLE
remove warning for wpgtk in release 2.0.0

### ISSUE THREAD

**Issue by deviantfero** [dylanaraps/pywal#222]
I've finished the work to adapt the new backend feature to `wpgtk` and released version `5.0.0` which supports pywal `2.0.2`, so it would be great if you could add that wpgtk now supports the latest version.

here's the release btw:
https://github.com/deviantfero/wpgtk/releases/tag/5.0.0

**Comment by dylanaraps** [comment]
Done.

Congratz on your release!
