### ISSUE TITLE
[feature request] Iterative wallpaper selection.

### ISSUE THREAD

**Issue by HarrisonTotty** [dylanaraps/pywal#227]
I think it would be nice to add a flag, say `--iterative`, to enable iterative image selection when supplying `wal` with a directory (as opposed to random image selection). It should be easy to implement, as the previous image is already stored in cache. I can create a PR with the relevant changes if requested, depending on how popular the idea is.

Note that by "iterative", I mean that `wal` will select the next image in the specified directory when sorting alphabetically.

**Comment by dylanaraps** [comment]
Done.

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/pywal/commit/d14821694ac2a0d6515f81bafe44401d3dd37654
