### ISSUE TITLE
oomix icon colors

### ISSUE THREAD

**Issue by bhughesshelton** [dylanaraps/pywal#228]
I'm using wal to set the GTK theme in oomox (which works very well and looks lovely by the way), but is there any way to set oomox fArchdroid flat icon colors as well? Just haven't seen it in the docs and haven't been able to figure out a workaround. Cheers.

**Comment by dylanaraps** [comment]
You can use an external script with `-o` to run additional programs after pywal completes. You can also use the export file for oomox with all of its scripts.

```sh
#!/bin/sh
oomox-archdroid-icons-cli -o wal ~/.cache/wal/colors-oomox
```

- Save it as `wal-set` (as an example)
- Run it with pywal. `wal -i img.jpg -o /path/to/wal-set`

This won't be added to pywal as oomox is already slow enough on its own.
