### ISSUE TITLE
fix non-ascii character in description

### ISSUE THREAD

**Issue by AvdN** [dylanaraps/pywal#23]
The description in the ``setup.py`` starts with  bytes f09f 8ea8, but you don't have an encoding set for that  file. 

So anyones browser/editor will display that incorrectly unless they happen to have the same settings as the  ones used by you. In this case I see a white box placeholder on PyPi and when doing `pip show pywal` after installing pywal in a virtualbox

If that non-ascii must be there, at least add `# coding: utf-8` to the top of your ``setup.py`` and insert the character you want. And check if PyPI actually displays that correctly, not just in your browser, but those on other platforms/configurations as well. Now it just look like a bug.

![pywal_00](https://user-images.githubusercontent.com/1210650/27722566-c6641e9e-5d68-11e7-8ff1-ac3382cccb5f.png)

![pywal_01](https://user-images.githubusercontent.com/1210650/27722684-5affa0be-5d69-11e7-8e1f-b5100020fb72.png)

**Comment by dylanaraps** [comment]
Fixed.

I've removed the character, it was just the emoji from the description here on GitHub. I didn't know `pip` let you view the description in the terminal otherwise I wouldn't have included it.

Thanks for opening this issue. :)

**Comment by dylanaraps** [comment]
I've pushed `0.3.3` to `pypi` which includes this fix.
