### ISSUE TITLE
st and PyWal still not getting along

### ISSUE THREAD

**Issue by m4iler** [dylanaraps/pywal#233]
Hi,

I looked at the issue concerning Luke Smith's fork of PyWal (dunno how to link, but it's one of the 4 issues I found when using st).

I tried with Luke's fork of the st program first, after you said it's meant for the default st build only, I downloaded the 0.8.1 version from st.suckless.org and it still throws an error.

Here is my error report:

```
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.1\" -D_XOPEN_SOURCE=600 -O -c st.c
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.1\" -D_XOPEN_SOURCE=600 -O -c x.c
x.c: In function ‘xdrawcursor’:
x.c:1423:11: error: ‘defaultrcs’ undeclared (first use in this function); did
you mean ‘defaultcs’?
    g.fg = defaultrcs;
           ^~~~~~~~~~
           defaultcs
x.c:1423:11: note: each undeclared identifier is reported only once for each function it appears in
Makefile:22: x.o failed
make: *** [x.o] Error 1
```

Can we do something about this? I'd be absolutely thrilled to help, but I don't know how (yet)

**Comment by dylanaraps** [comment]
This has been fixed.

**Comment by m4iler** [comment]
So all I need to do is delete the two arrays signalling Dark and Light theme? Nothing more? Thanks!
