### ISSUE TITLE
pywal on Android via Termux

### ISSUE THREAD

**Issue by leewdch** [dylanaraps/pywal#237]
I found all the dependencies for pywal and tested the console and looks like it's compatible with wal recoloring so I thought why not? I symlinked my sdcard directory, installed pywal and tried to run it but this happened. Sorry for a screenshot but it's quite troublesome doing this via phone

![screenshot_20180429-185824](https://user-images.githubusercontent.com/11262717/39409102-5ffe166a-4be1-11e8-83ef-214d41700061.png)
![img_20180429_191512](https://user-images.githubusercontent.com/11262717/39409122-ab5a9016-4be1-11e8-99ff-2174e27341b2.jpg)

**Comment by dylanaraps** [comment]
Do you have imagemagick installed?

**Comment by leewdch** [comment]
I installed the stable branch but there is a dev branch as well

**Comment by dylanaraps** [comment]
Does this command work on it's own?

```sh
convert /path/to/img.jpg -resize 25% -colors 16 -unique-colors txt:-
```

**Comment by leewdch** [comment]
It says Segmentation fault

**Comment by dylanaraps** [comment]
Yup, this isn't a pywal issue. There's something wrong with the imagemagick build you have installed.

Closing this.
