### ISSUE TITLE
Background is not changed in Ubuntu 16.04

### ISSUE THREAD

**Issue by LuisGerman92** [dylanaraps/pywal#241]
I'm running Ubuntu 16.04 and had no problems installing pywal. However, when I try to use it, it changes the colorscheme in the terminal successfully, and it even says that the wallpaper was set, but the wallpaper is not chaged.

Am I missing something? I already read the documentation but could not make it work.

Here is the output of running the command in a directory that contains an image called pacman.jpg:

luis@Lap:~/Pictures/Wallpapers$ wal -i pacman.jpg 
[I] image: Using image /home/luis/Pictures/Wallpapers/pacman.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[I] colors: Generation complete.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

                                                                                
                                                                                

[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
[I] reload: Use -g to generate an oomox theme.

**Comment by dylanaraps** [comment]
Try the latest git commit.

1. `git clone https://github.com/dylanaraps/pywal`
2. `cd pywal`
3. `python -m pywal -i /path/to/img.jpg`

**Comment by LuisGerman92** [comment]
Thank you :D it worked!

One note though, it seems that my default python is python2.7 so I got an error the first time I tried running the command, but I only had to change the third command to call python3 instead.
python3 -m pywal -i /path/to/img.jpg

Thank you very much!

**Comment by dylanaraps** [comment]
Good to know. Glad it's working now. :)

**Comment by dylanaraps** [comment]
I've pushed a new release including this fix. :)
