### ISSUE TITLE
Pywal now has a Discord server

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/pywal#244]
I've been using Discord more and more lately and have decided to open a server for discussion about Pywal and my other projects. When Matrix/Riot.im mature we will migrate to their platform or 
run our own instance.

Note: I know that Discord is proprietary but so is GitHub.

Click here to join: [![Discord](https://img.shields.io/discord/440354555197128704.svg)](https://discord.gg/BtnTPFF)

**Comment by hedythedev** [comment]
invalid invite?
