### ISSUE TITLE
wal suddenly started asking for sudo

### ISSUE THREAD

**Issue by bootzin** [dylanaraps/pywal#245]
I feel like after last update wal has suddenly started asking for super user permissions, is that really necessary? As I have an alias to easily change all my system's colors according to a wallpaper and as I also use this alias inside ranger to choose a new wallpaper, it is really annoying having to type my sudo pw everytime. Is that a problem with my system or was it really an intended change? And if so, can I do something so that I don't need to grant it super user permissions again? I mean, it worked just fine before

More specifically, I get the following message when running it without sudo:

> Traceback (most recent call last):
>   File "/bin/wal", line 11, in <module>
>     load_entry_point('pywal==3.0.0', 'console_scripts', 'wal')()
>   File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 194, in main
>     parse_args(parser)
>   File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 147, in parse_args
>     colors_plain = colors.get(image_file, args.l, args.backend)
>   File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 141, in get
>     util.save_file_json(colors, cache_file)
>   File "/usr/lib/python3.6/site-packages/pywal/util.py", line 87, in save_file_json
>     with open(export_file, "w") as file:
> PermissionError: [Errno 13] Permission denied: '/home/username/.cache/wal/schemes/_home_username_Pictures_Wallpapers_BUokHxx_png_dark_None_1.1.0.json'
> 

### pywal version
wal 3.0.0

### System
Linux titan 4.16.7-1-ARCH #1 SMP PREEMPT Wed May 2 21:12:36 UTC 2018 x86_64 GNU/Linux

### Steps to reproduce
wal -c -g -i  ~/Pictures/Wallpapers/current.png -o 'patch-st-colors'

"patch-st-colors" is a script I made that sets defaultbg color to always be "black" (Otherwise I can't use st with transparency) and recompiles st after running wal, as simply running "cat ~/.cache/wal/sequences" didn't always work to change the colorscheme

**Comment by dylanaraps** [comment]
It shouldn't be asking for `sudo` at all and I can't reproduce this.

What's the output of `ls -l ~/.cache/wal`?

**Comment by bootzin** [comment]
Thanks, that solved the error (: 
I might have ran wal as sudo once accidentally, so the json file under .cache/wal/schemes had root rw permissions only. As such, I couldn't change it as a normal user
Removing the file as root and running wal again fixed the issue, thanks for the help!
