### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by gh00sty** [dylanaraps/pywal#247]
$ wal -i "orange.png" -a 90
> works great transpacy is set on rxvt-unicode
> restarting X

$ wal -R
> everything works except transparency so i have to relaunch the first command again

sys+soft used : archlinux xorg bspwm urxvt compton rofi

**Comment by dylanaraps** [comment]
You can use `wal -R -a 90`. This is a known issue. https://github.com/dylanaraps/pywal/issues/187
