### ISSUE TITLE
Unreadable directory names on mounted media drive

### ISSUE THREAD

**Issue by Mr-SD** [dylanaraps/pywal#248]
Colors used for directories on my (ntfs) media mounted drives are unreadable:
![screenshot-2018-05-26_23-04-28](https://user-images.githubusercontent.com/3237827/40581864-9288768a-6139-11e8-91fd-352707f9c288.png)
![screenshot-2018-05-26_23-15-32](https://user-images.githubusercontent.com/3237827/40581894-c91ce626-613a-11e8-982c-23ff17687cab.png)
![screenshot-2018-05-26_23-16-40](https://user-images.githubusercontent.com/3237827/40581896-e1581198-613a-11e8-99d6-d5eaf4eb89ca.png)

This doesn't happen for other directories, not even for directories under `/media`:
![screenshot-2018-05-26_23-03-10](https://user-images.githubusercontent.com/3237827/40581870-b7f4d4c2-6139-11e8-96e0-90ebae28bd74.png)
![screenshot-2018-05-26_23-03-35](https://user-images.githubusercontent.com/3237827/40581871-b81ab8d6-6139-11e8-9f84-b73f760ea8a2.png)

I'm using termite, although the same happens on urxvt.

**Comment by dylanaraps** [comment]
I’ll look into this. Cheers

**Comment by dylanaraps** [comment]
Fixed.

You'll need to add a line to your `.bashrc` (*or equivalent*).

```sh
. ~/.cache/wal/colors.sh
```

Sourcing this file does the following:

- Make `$color0` to `$color15` available in the terminal.
- Make `$background`, `$foreground` and `$cursor` available in the terminal.
- Make `$wallpaper` available in the terminal.
- Force FZF to use `16` colors instead of 256.
- Fix `LS_COLORS` highlighting for `ow`, `st` and `su`.

**Comment by dylanaraps** [comment]
Here's what the file looks like:

```sh
# Shell variables
# Generated by 'wal'
wallpaper='/home/black/Pictures/Wallpapers/21 - ho1gEaP.jpg'

# Special
background='#1f1d19'
foreground='#c7c6c5'
cursor='#c7c6c5'

# Colors
color0='#1f1d19'
color1='#aa855e'
color2='#aa9477'
color3='#aa9f8f'
color4='#a7a6a4'
color5='#97a3aa'
color6='#8599aa'
color7='#c7c6c5'
color8='#575552'
color9='#aa855e'
color10='#aa9477'
color11='#aa9f8f'
color12='#a7a6a4'
color13='#97a3aa'
color14='#8599aa'
color15='#c7c6c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
```

**Comment by Mr-SD** [comment]
Sorry for the late reply. I just tried it and indeed, directory names on my media drive are now readable but they use a different color when compared to regular directories in my main ext4 system drive. Is this intentional?
![screenshot-2018-08-03_04-46-41](https://user-images.githubusercontent.com/3237827/43631060-8b4e3c68-96d8-11e8-8b36-2e7a69d0f06d.png)
![screenshot-2018-08-03_04-47-45](https://user-images.githubusercontent.com/3237827/43631061-8b6e5f48-96d8-11e8-9fd6-ea21de4eec8a.png)
