### ISSUE TITLE
colors.sh: bad substitution since update to 3.0.1

### ISSUE THREAD

**Issue by shizonic** [dylanaraps/pywal#252]
Since the update to version 3.0.1 I get the follow error when sourcing colors.sh:
```
/home/$USER/.cache/wal/colors.sh:36: bad substitution
```
This is caused by the line:
```
# Fix LS_COLORS being unreadable.                                                                             
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
```
Downgrading to version 3.0.0 and regenerating my generated themes fixes this issue temporarly.

**Comment by dylanaraps** [comment]
What shell are you using? The colors.sh should be POSIX (it works in dash).

**Comment by shizonic** [comment]
Thanks for the quick answer. I am using zsh.

**Comment by dylanaraps** [comment]
Fixed. https://github.com/dylanaraps/pywal/commit/6c0cdf212d174766bea0f09480b6d9a17bfadac4

**Comment by shizonic** [comment]
This was quick. Thank you!

**Comment by dylanaraps** [comment]
No problem :)

**Comment by D-Vaillant** [comment]
I had a similar issue (also on zsh); the changed version didn't work but this one did. I don't understand why.
`export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"`
