### ISSUE TITLE
Issue with the custom wal function for setting the wallpaper

### ISSUE THREAD

**Issue by kartikvashistha** [dylanaraps/pywal#253]
Hi,
I use i3wm with dual monitors, and therefore made a custom function to span my wallpaper as explained [here](https://github.com/dylanaraps/pywal/wiki/Getting-Started). However, whenever I first boot into my wm or reload my i3 config, `wal` sets my wallpaper with the default `fill` mode instead of my custom `wal-center` function. I tried to use `wal-center -R` in my `.xinitrc` to see if that fixes it, however that didn't seem to work. Is there any known solution for such an issue?

My .bashrc
```
   (cat ~/.cache/wal/sequences &)#
    wal-center() {
     wal -n -i "$@"
     eh --no-xinerama --bg-center "$(< "${HOME}/.cache/wal/wal")"
```

My .xinitrc
```
 wal-center -R

```

**Comment by Mikle-Bond** [comment]
1. I'm not sure this is correct. Do you really use `eh` or is it a typo?
2. Probably, `.xinitrc` can't call your function at all. Usually it is being read by `startx`, or similar program. Which is not an interactive shell. So, your `.bashrc` is not being sourced, and functions are not being inherited, so there is no `wal-center` in `.xinitrc`
3. Even if it could be called, the way you pass params in it would expand call to `wal -n -i -R`, which results in this error `wal: error: argument -i: expected one argument `.

The way I see a solution is simply put this calls directly to .xinitrc:
.bashrc:
```bash 
(cat ~/.cache/wal/sequences &)
```
.xinitrc
```sh
wal -n -R
feh --no-xinerama --no-fehbg --bg-center "$(< "${HOME}/.cache/wal/wal")"
```
You can also keep the `wal-center` function in `.bashrc` in case you want to *change* wallpaper, not restore previous.

**Comment by kartikvashistha** [comment]
@Mikle-Bond Thank you for your response, yes, eh was indeed a typo for feh!
Your answer makes complete sense, and theoretically should work. However, for some reason the `feh` command in my xinitrc doesn't execute after I login. Here's the complete xinitrc for your reference:

```
 setxkbmap gb
  
   exec start-pulseaudio-x11
   
   dbus-update-activation-environment --systemd DISPLAY
   eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
   export SSH_AUTH_SOCK
   
  #From pywal wiki:
  # Add this to your .xinitrc or whatever file starts programs on startup.
  # -R restores the last colorscheme that was in use.
  wal -n -R
   feh --no-xinerama --no-fehbg --bg-center "$(< "${HOME}/.cache/wal/wal")"
  
  exec i3

```
I even tried to use the `exec` command before the `wal` and `feh` commands respectively, yet that didn't seem to work either. Any idea why?

**Comment by dylanaraps** [comment]
You should only have one `exec` in your `.xinitrc` and it should be the last command at the bottom.

**Comment by dylanaraps** [comment]
Closing this as it isn't a bug. Feel free to continue discussing this.

**Comment by kartikvashistha** [comment]
@dylanaraps Thank you very much, this solved it!
