### ISSUE TITLE
I broke something.

### ISSUE THREAD

**Issue by blahsd** [dylanaraps/pywal#260]
I thought this was an issue with the `-l` argument, while it appears that I broke the whole thing. I'm leaving this up in case anybody has got some intel and can help me fix it. Uninstall and reinstall, through either `pip` or `git clone` doesn't seem to help. 

```
~
❯ wal -i Pictures/Wallpapers/girl-bus.jpg -l
[I] image: Using image girl-bus.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[I] colors: Generation complete.
[I] wallpaper: Set the new wallpaper.
^C^C^CTraceback (most recent call last):
  File "/Users/<...>/Library/Python/3.6/lib/python/site-packages/pywal/util.py", line 78, in save_file
    file.write(data)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/Users/<...>/Library/Python/3.6/lib/python/site-packages/pywal/__main__.py", line 194, in main
    parse_args(parser)
  File "/Users/<...>/Library/Python/3.6/lib/python/site-packages/pywal/__main__.py", line 166, in parse_args
    sequences.send(colors_plain, to_send=not args.s)
  File "/Users/<...>/Library/Python/3.6/lib/python/site-packages/pywal/sequences.py", line 95, in send
    util.save_file(sequences, term)
  File "/Users/<...>/Library/Python/3.6/lib/python/site-packages/pywal/util.py", line 78, in save_file
    file.write(data)
KeyboardInterrupt

~ 47s
❯
```

**Comment by blahsd** [comment]
I changed `util.py` like so: 

```
def save_file(data, export_file):
    """Write data to a file."""
    create_dir(os.path.dirname(export_file))

    try:
        **logging.info("Writing to %s.", export_file)**
        with open(export_file, "w") as file:
            file.write(data)
    except PermissionError:
        logging.warning("Couldn't write to %s.", export_file)
```

adding the bolded line to understand where the issue is. It appears I can't write to one of the ttys files. This is the output:
```
~/Library/Python/3.6/bin
❯ ./wal -i ~/Pictures/Wallpapers/hills.jpg
[I] util: Writing to /Users/<...>/.cache/wal/wal.
[I] image: Using image hills.jpg.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] util: Writing to /dev/ttys002.
[I] util: Writing to /dev/ttys003.
```
Do you @dylanaraps have any idea of why this could be happening?

**Comment by dylanaraps** [comment]
There's a try/catch block there to stop exactly this. Is there another exception we should be catching?

**Comment by blahsd** [comment]
Mmmh. Might be. I tried to get more information on what's going on with this:
```
def save_file(data, export_file):
    """Write data to a file."""
    create_dir(os.path.dirname(export_file))

    try:
        logging.info("Writing to %s.", export_file)
        with open(export_file, "w") as file:
            file.write(data)
    except e:
        logging.info(e)
```
which apparently is not the right way to do it, because I got exactly the same output. 

So I tried removing the try/catch altogether in the hope of just having the program fail ungracefully and maybe get a traceback, but nothing there also.

The easy workaround is just running it with `-s` but I thought you still might have wanted to know about this.

**Comment by blahsd** [comment]
Tried both that and just `except:` with no exception specified

**Comment by dylanaraps** [comment]
What about something like this:

```py
def save_file(data, export_file):
    """Write data to a file."""
    create_dir(os.path.dirname(export_file))

        with open(export_file, "w") as file:
            try:
                file.write(data)
            except IOError:
                logging.warning("Couldn't write to %s.", export_file)
```

**Comment by blahsd** [comment]
Nope. Tried a bunch of variations, removing `with` in favour of a try/finally, adding a manual `file.close()` and switching through a bunch of exceptions. If I get any more creative ideas I'll try and let you know. It really is not an issue for me because I don't use terminal sending anyways, so as long as no one is reproducing this, you don't have to bother.

**Comment by thjread** [comment]
I had the same (or a very similar) issue, where pywal got stuck writing to `/dev/pts/6`. I couldn't figure out what that represented - it wasn't any of the terminals I had open. `$ echo test > /dev/pts/6` also hung.

Unfortunately I haven't figured out how to reproduce this consistently - I restarted the X server and the problem went away for now.
