### ISSUE TITLE
Is base16-phd incorrect?

### ISSUE THREAD

**Issue by D-Vaillant** [dylanaraps/pywal#265]
https://github.com/dylanaraps/pywal/blob/master/pywal/colorschemes/dark/base16-phd.json
Here's the original (from https://github.com/chriskempson/base16-unclaimed-schemes/blob/master/phd.yaml):
```
base00: "061229"
base01: "2a3448"
base02: "4d5666"
base03: "717885"
base04: "9a99a3"
base05: "b8bbc2"
base06: "dbdde0"
base07: "ffffff"
base08: "d07346"
base09: "f0a000"
base0A: "fbd461"
base0B: "99bf52"
base0C: "72b9bf"
base0D: "5299bf"
base0E: "9989cc"
base0F: "b08060"
```
And here's what pywal has:
```
#061229
#d07346
#99bf52
#fbd461
#5299bf
#9989cc
#72b9bf
#b8bbc2
#717885
#d07346
#99bf52
#fbd461
#5299bf
#9989cc
#72b9bf
#ffffff
```
There's definitely some correspondence but I'm not quite understanding why the themes are different.

**Comment by dylanaraps** [comment]
Some of the themes were modified to better fit `pywal`. Colors weren't change but they were rearranged.

**Comment by D-Vaillant** [comment]
Some of them got removed too, right? `#2a3448`, for example.

**Comment by D-Vaillant** [comment]
Nice, thanks for the information :+1:

**Comment by neon64** [comment]
I understand how this makes the base16 themes work better with `pywal`, but I'm in the situation where I'd really like a number of shades of grey - for use in backgrounds, borders and other aspects of the UI (particularly for e.g.: theming sway). I'd love to use pywal for the flexibility of not just having base16 themes, but unfortunately at the moment the lack of extra colours is a dealbreaker. Is it possible to expose more than 16 colors, perhaps? An extra 8 'greyish' colours (which could also be taken from images)?

**Comment by deviantfero** [comment]
you could use [wpgtk](https://github.com/deviantfero/wpgtk) if modifying your color-schemes is really important, it uses `pywal` in the back, so you're really not missing any feature.

pywal not only has base16 themes, it has over 200 themes to pick from, of course you can also create your own in a JSON file and feed it to `wal` or `wpgtk` for that matter, with `pywal` that is done with the `-f` flag

```
  -f "/path/to/colorscheme/file"
```
