### ISSUE TITLE
Something changed in the way the color palette is generated and is crashing pywal

### ISSUE THREAD

**Issue by delightfulagony** [dylanaraps/pywal#266]
I'm comparing the last release (`wal 3.1.0`) with (`wal 3.0.1`)

I first noticed it in a wallpaper that had a very consistent (and small) colour palette:
![wallpaper 04](https://user-images.githubusercontent.com/29728930/41811418-a118158e-770f-11e8-9623-c230b671b7ea.jpg)
In `wal 3.0.1` it used to generate me a palette which set my font colour to white, in `3.1.0` it changed to a light blue, a change in the way the palette is selected would be reasonable, I only mention it because it relates to the problem.

I tried then to obtain the palette of another image, which has a very grayscale palette and this is the terminal output:
```
$ wal -i ~/Pictures/wallpapers/wallpaper#05.jpg
[I] image: Using image wallpaper#05.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[E] wal: Imagemagick couldn't generate a palette.
[E] wal: Try a different image or backend.
```
I'm not posting the image because it's a personal one, it's similar to this one but darker:
![example](https://user-images.githubusercontent.com/29728930/41811415-922a7418-770f-11e8-929f-00edc052bd06.jpg)

An then I tried to use this image:
![pixelwallpaper 02](https://user-images.githubusercontent.com/29728930/41811428-b67d8044-770f-11e8-9054-c5d43f2396c4.png)
To find the following console output:
```
$ wal -i ~/Pictures/wallpapers/pixelwallpaper#02.png 
[I] image: Using image pixelwallpaper#02.png.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.1.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 198, in main
    parse_args(parser)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 154, in parse_args
    sat=args.saturate)
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 149, in get
    colors = getattr(backend, "get")(img, light)
  File "/usr/lib/python3.6/site-packages/pywal/backends/wal.py", line 78, in get
    return adjust(colors, light)
  File "/usr/lib/python3.6/site-packages/pywal/backends/wal.py", line 70, in adjust
    raw_colors[15] = util.blend_color(raw_colors[15], "#EEEEEE")
IndexError: list index out of range
```

The second image used to work without problems in `wal 3.0.1` and the third one I haven't tested in `wal 3.0.1`.

*I don't own the rights of any of the images posted here, they're there just for explanatory purposes*
***
**Edit:** After comparing the two branches I imagine the problem might be in https://github.com/dylanaraps/pywal/commit/1ef4c742a2c0ed35a408501a73a20ae184f90d22 but since I don't know python I can't really be sure.

**Comment by D-Vaillant** [comment]
I don't know the overall program at all but I see the issue: the first branch has:
`if len(raw_colors) > 16`
and the second does:
`if len(raw_colors) < 16`
But we need `len(raw_colors) < 17`, because further down we do:
`return [re.search("#.{6}", str(col)).group(0) for col in raw_colors[1:]]`
If `raw_colors` had exactly 16 elements, it'll end up spitting out a palette of 15 elements at the end and that's where the index error is coming from.

Depending on what the `re.search` is doing, either:
1. Change it to iterate over `raw_colors` and not leave out the first element, or
2. Change the error checking condition to require a minimum of 17 elements.

**Comment by dylanaraps** [comment]
Fixed, try the latest master.

**Comment by delightfulagony** [comment]
Yup, it works perfect now

**Comment by dunce345** [comment]
Using 3.1.0-2, and this issue has popped up again.

Tested on mainly black and white images and it gives the same error.

[I] image: Using image 5.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[E] wal: Imagemagick couldn't generate a palette.
[E] wal: Try a different image or backend.

tested with the following images.

![4](https://user-images.githubusercontent.com/17759116/44301190-3bb0cb80-a330-11e8-9084-5237a08c8a9f.jpg)
![5](https://user-images.githubusercontent.com/17759116/44301191-3bb0cb80-a330-11e8-9d7e-287634b04336.jpg)
