### ISSUE TITLE
Recursive -i argument

### ISSUE THREAD

**Issue by PhilsLab** [dylanaraps/pywal#270]
Quick idea i just wanted to use, but saw it didn't work:

using argument `-i <my-path>` where the directory <my-path> itself doesn't contain any pictures, but the subdirectories of it do.
In this folder I store multiple sets of wallpapers and i'd love to see pywal choosing a random one by having `-i` searching for images recursively.

**Comment by DoktorScience** [comment]
Hey, that would be a great feature!
In the mean time, I've written myself this little piece of code:
```#!/usr/bin/env bash
ocDir="${HOME}/path/to/folder"

ls $ocDir |sort -R |tail -n1 |while read file; do
    # Select one random file from directory
    wal -i ${ocDir}${file}
done
```

You could also supposedly create an alias to call this script.

**Comment by ecly** [comment]
Maybe the recursive search should be a separate option. Perhaps `-I`?
The recursive option could be an unpleasant slowdown for people with funny directory trees.

**Comment by LoLei** [comment]
I already tried something locally to have this functionality, if I can make it work properly I'll make a PR.
