### ISSUE TITLE
Transparency doesn't reload terminals with -f flag

### ISSUE THREAD

**Issue by delightfulagony** [dylanaraps/pywal#271]
When using the `-f` flag the alpha is set to 100 in existing terminals.
New terminals get alpha set properly, but in existing ones it doesn't get reloaded.
This issue is present since version [3.0.1](https://github.com/dylanaraps/pywal/releases/tag/3.1.0)
I believe the problem might be in https://github.com/dylanaraps/pywal/commit/603276a12610320a53d6b7d64e3f096f71ce2240

*This issue was first reported by @deadcombo on #256*
***
OS: Archlinux
Packages: URxvt, i3-gaps, compton, rofi

**Comment by deadcombo** [comment]
> New terminals get alpha set properly, but in existing ones it doesn't get reloaded.

Not for me, closing all terminals and opening new ones still does not give me transparency.

**Comment by dylanaraps** [comment]
Fixed.
