### ISSUE TITLE
Error after upgrade to Python 3.7

### ISSUE THREAD

**Issue by phlind** [dylanaraps/pywal#275]
Since the upgrade to Python 3.7 (I use homebrew on macOS) I get the following error when running `wal`:

`zsh: /usr/local/bin/wal: bad interpreter: /usr/local/opt/python/bin/python3.6: no such file or directory`

If I run `brew switch python 3.6.5_1` to revert to the older version, wal is working, but my vim does not. Is there any other solution to make it work? Thanks

**Comment by bysimeon** [comment]
uhh i came across the same issue with beets, what i've done is install [pyenv](https://github.com/pyenv/pyenv) and made an alias in my shell that runs beets with the right python version. you could do the same with pywal using the following template  `alias example='pyenv shell 3.6.5 && whatever command with wal'`

**Comment by bysimeon** [comment]
uhh, i don't remember as well. I never did this for pywal, but the methodology should be the same (i'm gonna sub in pywal here).

- my system python version was 3.7.0 so i'd always used pip (not pip3)
- i install pyenv
- switched shell to 3.6.5
- install pywal with pip install pywal
- then used the previously mentioned alias, which i changed to `pyenv shell 3.6.5 && [pywal command] && pyenv shell system`

personally, i installed my pywal from git and it was working properly when i upgraded to 3.7.0. I'd recommend doing a reinstall to see if that works
