### ISSUE TITLE
Termite's exec ruining colorscheme

### ISSUE THREAD

**Issue by aleprovencio** [dylanaraps/pywal#277]
Hello,
this is related to issues #126, #107 and #109, but as none of them is directly related to termite I decided to open a new one.

Launching an app as an argument with termite's exec such as ``termite -e nvim`` will not load the colorscheme correctly while ``urxvt -e nvim`` will.

**Comment by dylanaraps** [comment]
There’s nothing I can do to fix this sadly.

**Comment by aleprovencio** [comment]
No problem @dylanaraps!

If this is a termite thing, maybe you can give me more details/directions so I can create an issue upstream.

**Comment by dylanaraps** [comment]
This isn’t a bug, it’s intended behaviour in all terminal emulators. When you run termite with -e it skips loading your shell (which loads the wal colors) so no colors are applied.

**Comment by aleprovencio** [comment]
wow sorry about missing that.
`termite -e "bash -ic nvim"` does the job.

**Comment by indeedwatson** [comment]
That doesn't work for me and neither does https://github.com/dylanaraps/pywal/issues/126#issuecomment-338825524

**Comment by machin3io** [comment]
> wow sorry about missing that. `termite -e "bash -ic nvim"` does the job.

OMG, thank you so much! This was driving me nuts. Nice colors when launching the terminal, shitty colors when keymap launching any terminal app.

FWIW, it works just the same with alacritty and zsh

`alacritty -e zsh -ic vim`
`alacritty -e zsh -ic ranger`
etc.

edit: 
ok, well for ranger, it works for the first launch, but if you open a file from ranger in vim, and then go back, the colors will be lost. same if you go into the shell.

edit2:
Ok, the solution that solves all my problems is to simply not use pywal to set the colors in the shell.

Instead I just brought the colors of my favorite theme over to the alacritty config. Now the colors are consistent everywhere: terminal, ranger, vim, vim called from ranger, ranger after exiting vim, shell called from ranger, etc. 

No need to execute the shell via -e, and no need for re-aliasing ranger or vim.

**Comment by machin3io** [comment]
> This isn’t a bug, it’s intended behaviour in all terminal emulators. When you run termite with -e it skips loading your shell (which loads the wal colors) so no colors are applied.

Thank you too for that explanation about the root of the problem, and of course for the wonderful pywal.
