### ISSUE TITLE
pywal does not seem to work with Lilyterm

### ISSUE THREAD

**Issue by anselal** [dylanaraps/pywal#281]
Hi there,

great work with this tool, I really love it. I am using Lilyterm for a month or so prior to urxvt because Lilyterm supports Nerd fonts.

When I run pywal the colors change on the terminal but when I switch the focus to another window or move the window around the color scheme returns to my default.

**Comment by dylanaraps** [comment]
Hi, 

This is an issue with Lilyterm and not pywal.

**Comment by anselal** [comment]
OK thanks
