### ISSUE TITLE
[feature request] Generation of color9-15

### ISSUE THREAD

**Issue by ralismark** [dylanaraps/pywal#283]
Currently, pywal only generates 9 colours for the theme, with color9-15 being the same as color1-7. I saw #138, but it would be great if the higher colours were generated as lighter/brighter versions of the base colour set. [wpgtk](https://github.com/deviantfero/wpgtk) has something like this as "auto-adjust".

**Comment by Anachron** [comment]
Would be fairly simple using the colorz backend which already does this by default.

**Comment by dylanaraps** [comment]
Use `wpgtk` if you'd like more colors. The 15 colors the backends generate aren't all good. pywal picks the best groups found in testing hundreds of wallpapers on my machine.

**Comment by indeedwatson** [comment]
What about the colors from ready-made themes? For example https://github.com/morhetz/gruvbox has many colors yet when generated by pywal it's only 9. Is this a limitation that's just baked into pywal?

**Comment by mikebm94** [comment]
I know this is an old, closed issue, but I don't get the logic behind the decision. I understand that the 15 colors generated by the backends aren't all good, and that pywal chooses the 9 appropriate colors. Why then, can't pywal (either optionally or by default) just generate brighter versions of these colors?

That's really what the upper 8 colors of the terminal color palette are meant (or almost always used) for; colors 0-7 are normal/dark, and colors 8-15 are light versions of the previous 8 colors.

**Comment by sonjiku** [comment]
My pull request, #601, adds this functionality.
