### ISSUE TITLE
Auto starting i3wm from .zprofile causes pywal not to work.

### ISSUE THREAD

**Issue by NonaSuomy** [dylanaraps/pywal#288]
When you start i3wm from .zprofile like below all that loads is a grey background and you can no longer run pywal from i3 mod keys to change backgrounds but you can start it manually from the command line with "wal -i ~/.config/i3/wallpapers".

# File: ~/.zprofile

if [[ ! $DISPLAY && $XDG_VTNR -le 1 ]]; then
  exec startx
fi

# File: ~/.config/i3/config

# Applications to be launched when i3 starts
exec --no-startup-id wal -i $HOME/.config/i3/wallpapers
# Generate betterlockscreen background to match pyWal.
exec --no-startup-id source $HOME/.cache/wal/colors.sh && $HOME/.config/i3/scripts/betterlockscreen -u "$wallpaper" 
exec --no-startup-id $HOME/.config/i3/scripts/betterlockscreen -l blur

# Refresh Wal art.
bindsym $mod+c exec --no-startup-id wal -i $HOME/.config/i3/wallpapers

Wondering if there is a way to accomplish auto starting the WM launching pywal after tty login so pywal can still be run from the WM?

**Comment by dylanaraps** [comment]
Not sure if this is a pywal issue.
