### ISSUE TITLE
Missing URL in setup.py

### ISSUE THREAD

**Issue by TheFridgeMaster** [dylanaraps/pywal#29]
Good afternoon,

ENV Setup:

distro: ubuntu 17.04 - daily build
uname -a: Linux 4.12.0-999-generic
python: 3.6.2rc1 

I have been attempting to install pywal on my ubuntu 17.04 install and I am receiving an error upon running setup.py as per the below:

`fridge@fridgebuntu:~$ pip install pywal
Collecting pywal
  Using cached pywal-0.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HdFFPb/pywal/setup.py", line 13
        DOWNLOAD_URL = f"https://github.com/dylanaraps/pywal/archive/{VERSION}.tar.gz"
                                                                                     ^
    SyntaxError: invalid syntax
`

Upon inspection of setup.py it appears the URL 

> https://github.com/dylanaraps/pywal/archive/

 doesn't exist at all, let alone a child url.

Am I missing something here? It appears as if they are just not hosted anymore.

Cheers,
Kyle.

**Comment by TheFridgeMaster** [comment]
Apologies, turns out it was still executing the wrong pip version even though 3.6 was installed. I guess thats why people recommend virtualenv so much.

Anyways when I ran 

> python3.6 -m pip install pywal

It installed successfully. 

Apologies for wasting your time.

**Comment by dylanaraps** [comment]
No worries. :)
