### ISSUE TITLE
Bash sequences in suckless terminal (st)

### ISSUE THREAD

**Issue by thy6** [dylanaraps/pywal#290]
Using suckless/simple terminal (st) version 0.8.1 and pywal version 3.1.0. 

Instead of compiling the colors into the terminal I rely on the bash sequences to color the terminal. But suckless terminal has an issue with this because it does not seem to pick the colors for the cursor, even though it's picking the other colors when using the line `(cat ~/.cache/wal/sequences &)` in .bashrc.

I was able to fix this by editing the file `~/.local/lib/python3.6/site-packages/pywal/sequences.py` by adding a comma on line number 57 and adding this line after that:

    set_color(256, colors["special"]["foreground"])

So now line 58 looks just like line 57 but with 256 instead of 232 and without the comma at the end that you just added to line 57. The bash sequences are now picked up correctly by the suckless terminal and the cursor color is right.

**Comment by dylanaraps** [comment]
Done.
