### ISSUE TITLE
[Feature request] The -o option can only be passed once

### ISSUE THREAD

**Issue by roguh** [dylanaraps/pywal#295]
First off, thank you for creating this amazing project!

I find the `-o` option useful, but I wish I could use it to run multiple scripts instead of only one. For example,

```
wal -R -o reload-dunst.sh -o demonstrate-notifications.sh -o reload-plan9.sh
```

**Comment by deviantfero** [comment]
Why not create a script that calls all of those scripts?

**Comment by lasers** [comment]
This should be closed. Thanks @roguh.
