### ISSUE TITLE
pywal in cronjob not always changing desktop wallpaper

### ISSUE THREAD

**Issue by sambadevi** [dylanaraps/pywal#297]
I added wal to my user cron-table, however it's not always working.
The colorscheme itself changes every time but the wallpaper itselfs stays sometimes. If I manually trigger `wal -R` again, the wallpaper changes.

The cron line looks like this: `*/30 * * * * wal -a 80 -i ~/Pictures/Wal > /dev/null 2>&1`

### Setup
- python 3.7.0
- wal 3.1.0
- i3wm and x11

**Comment by brjborja** [comment]
+1

**Comment by zinglax** [comment]
+1

**Comment by wudaown** [comment]
setting the DISPLAY env should work.
`*/1 * * * * DISPLAY=:0 $HOME/bin/wall.py`
wall.py is a wrapper that I write to randomize the image.

**Comment by sambadevi** [comment]
Thanks @wudaown I'll try your suggestion
