### ISSUE TITLE
transparency / -a flag not reloading on predefined themes

### ISSUE THREAD

**Issue by jonas-kaiser** [dylanaraps/pywal#298]
When I use the -a flag together with the -i option, my terminals get transparent accordingly.
However this does not work when I set a theme using the --theme option. The background stays un-transparent and only new terminals will use the transparency 

I'm using urxvt with compton for transparency.

**Comment by uzkbwza** [comment]
Also having this issue.

**Comment by uzkbwza** [comment]
Okay - just realized I wasn't using the latest version. However, installing it with git clone and pip now has the issue that it won't apply transparency for terminals created after it was executed.

**Comment by annata83** [comment]
How you use the -a flag with -i ? This is what I get: 
 "with this command "
`wal -i -a `/home/niko/Pictures/wallpapers`
usage: wal [-h] [-a "alpha"] [-b background] [--backend [backend]]
           [--theme [/path/to/file or theme_name]] [--iterative]
           [--saturate 0.0-1.0] [--preview] [-c] [-i "/path/to/img.jpg"] [-g]
           [-l] [-n] [-o "script_name"] [-q] [-r] [-R] [-s] [-t] [-v] [-e]
wal: error: argument -i: expected one argument

**Comment by dylanaraps** [comment]
This works for me in master. What version of `pywal` are you using?

**Comment by annata83** [comment]
@dylanaraps Using 3.2.1
