### ISSUE TITLE
Error: 8 unsupported relocations

### ISSUE THREAD

**Issue by madstk1** [dylanaraps/pywal#299]
When using the '-resize' parameter in ImageMagick, it will result in
`Error: 8 unsupported relocations`
multiple times before reporting
`fish: "magick convert Wallpapers/15299..." terminated by signal SIGSEGV (Address boundary error)`

Using Python 3.6.6 and ImageMagick 7.0.8 (also tried 6.9.10.10 with no luck).
When using `-scale` instead, pywal will work fine.

I haven't been able to replicate this on my laptop, even with the same version numbers.

**Comment by stuartpb** [comment]
This should be fixed once [this upstream patch](https://github.com/ImageMagick/ImageMagick/commit/41a3cc9323255b321c9b5361a8f1aad8e68b6229) gets packaged into a release on Arch Linux.
