### ISSUE TITLE
Name change (Suggestions welcome)

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/pywal#3]
`wal` is already registered on Pypi so I can't create a `pip` package using the name `wal`. This means I'll either have to come up with a different name solely for the Pypi site (The repo and script name will stay the same) or I rename the entire project. (I'll pick a google-able name this time.)

Anyway, suggestions are welcome. :)

**Comment by unix121** [comment]
Maybe PyWal would be the way to go? Not far from the original name, just an indicator that it's the Python version.

**Comment by dylanaraps** [comment]
That's a good idea! `pip install pywal` is easy enough to remember.

This version will soon replace the bash version on the original repo so renaming the project to something unique and googleable doesn't seem like a bad idea either.

**Comment by dylanaraps** [comment]
I've added the package to pypi as `pywal`, check the README.
