### ISSUE TITLE
Severe problems with macOS 10.14 Mojave

### ISSUE THREAD

**Issue by pycebs** [dylanaraps/pywal#302]
Hello.

I'm using macOS 10.14 Mojave and when I set a wallpaper with pywal I get a few problems:

- Desktop turns black
- Dock crashes and cannot be restarted
- Cannot launch Safari, but I can launch Chrome

Of course there might be other errors that I just haven't noticed. I'm running in dark mode and I'm using a fresh/clean installation of macOS.

The problem is similar to #292. Once I delete the file "desktoppicture.db" in "/Users/username/Library/Application Support/Dock" everything works fine again. But as soon as I try setting the wallpaper with pywal again I get the exact same errors as I mentioned above. 

I looked at the code and I cannot understand how simply changing a wallpaper can cause such massive errors (the system literally becomes unusable), but maybe someone with more background knowledge can chime in.

**Comment by Dakishimete** [comment]
I wasn't expecting such massive damage while setting a wallpaper. There must have been some serious reworking in 10.14 to handle dynamic wallpapers. Thanks for the fix, you saved me a system restore.

**Comment by samerickson** [comment]
That fix works great!!!! Thanks

**Comment by dylanaraps** [comment]
Fixed.

Sorry folks, life (and death) got in the way.

**Comment by dylanaraps** [comment]
done

**Comment by arkdelkaos** [comment]
Same as @samuellvicente, on Mojave 10.14.1 with pywal 3.2.1 I get the _black wallpaper of death_ 🤔

**Comment by JarrettAzar** [comment]
I also got this problem today, just commenting to say its still around.

**Comment by robwaz** [comment]
@JarrettAzar, are you using the pip version or the version from GitHub?  I pulled the most recent version from GitHub and experienced no issue.

**Comment by mrusme** [comment]
Same issue here, using wal 3.3.0 via `pip3 install` and macOS 10.15.5. For a split second my heart dropped into my stomach, but deleting the `desktoppicture.db` seems to have recovered everything.

**Comment by robwaz** [comment]
Please see #515 and let me know if the issue persists.

**Comment by hoohugokim** [comment]
> Please see #515 and let me know if the issue persists. The change has not been merged into master yet.

I've had the same issue (pip3 install pywal), works wonders with your fork in #515.

macOS Catalina 10.15.5
