### ISSUE TITLE
Remove VTE workaround for VTE versions >= 0.54 - It is no longer necessary and even causing problems

### ISSUE THREAD

**Issue by pycebs** [dylanaraps/pywal#304]
I'm using Gnome 3.30 and Pywal 3.1.0 and the Gnome update to 3.30 also brought a VTE update to version 0.54.

I filed a bug report with the VTE  team, but it turns out it's actually a bug in Pywal.

You can find my original bug report and the detailed answers of two of the maintainers of VTE here:

https://gitlab.gnome.org/GNOME/vte/issues/52

The VTE workaround can and should be removed as it is causing problems with the newest version of VTE. (And according to the two maintainers the workaround doesn't seem to be necessary anyway)

**Comment by mpolidori** [comment]
I was having the same issues described in your bug report after the GNOME 3.30 update. For now, I have commented out the VTE workaround in `sequences.py`, and everything is working as expected again.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by pycebs** [comment]
@dylanaraps Any idea when this will land on PyPI?
