### ISSUE TITLE
Re-implement -a

### ISSUE THREAD

**Issue by raulpegan** [dylanaraps/pywal#31]
Transparency is crucial for some of us. If you don't feel like implementing this, I should be able to.

**Comment by JoshuaRLi** [comment]
Same here, I'm an `urxvt` user and I need muh transparency XD

So I'm sticking to `wal-git` instead of `python-wal` for now. If someone doesn't implement this sooner or later, I might give it a try.

Thanks so much @dylanaraps for `wal`, by the way! I love it!

**Comment by dylanaraps** [comment]
Done, please let me know if there are any issues.

**Comment by JoshuaRLi** [comment]
Beautiful, it works perfectly for me (urxvt on Arch latest)! Thanks so much @dylanaraps, version bump this so the bleeding edge can propagate to pypi + AUR?

**Comment by dylanaraps** [comment]
Will do!

**Comment by dylanaraps** [comment]
Done, `0.5.0` has been released.

**Comment by JoshuaRLi** [comment]
LIT :fire: :fire: :fire: 

`pywal` has improved my quality of life so much

**Comment by twiclo** [comment]
It doesn't seem to change the transparency for me no matter what alpha I give it. Am I doing something wrong with urxvt perhaps? I've gotten transparency working with this terminal before
