### ISSUE TITLE
Pywal generating only two colors in Arch Linux 32

### ISSUE THREAD

**Issue by jtb20xx** [dylanaraps/pywal#310]
I recently resurrected an old Pentium 4 desktop from the garage and loaded up i3-gaps with pywal and have discovered that not only is w3m not generating images in ranger, my beloved pywal is only reading black and then the dominant color of any given image.

Excuse me if I’m being dense, maybe this is futile on 32-bit architecture, but I’d really like to know if I’m missing anything. I feel like I’ve exhausted everything and don’t normally resort to asking for help. :-)

**Comment by deviantfero** [comment]
have you tried switching backends?

pywal provides the option to use several different backends.
