### ISSUE TITLE
Terminal theme changes to default when terminal is reset

### ISSUE THREAD

**Issue by ohayondotio** [dylanaraps/pywal#313]
The terminal resets to its default non-pywal theme when it is reset. It can be observed on xfce4-terminal when issuing the command `reset`. It can also be triggered by doing things such as browsing for files with ranger, opening them in an editor, then closing the editor (same effect as `reset`).

**Comment by CodeMyst** [comment]
I have the same issue running `gnome-terminal`. I solved it by adding this at the end of my `.zshrc`, you can also do this in your `.bashrc`.
```sh
wal -r && clear
```

`wal-r` applies the theme and I added `clear` becase in `gnome-terminal` after changing the theme, the cursor (the thing where you type stuff) is at the bottom.

**Comment by ohayondotio** [comment]
Thank you for your suggestion. I just tested this with xfce4-terminal and zsh and it does not work. 

The portions of my .zshrc file that have to do with wal are as follows: 

```# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
(cat ~/.cache/wal/sequences &)

# Alternative (blocks terminal for 0-3ms)
cat ~/.cache/wal/sequences

# To add support for TTYs this line can be optionally added.
source ~/.cache/wal/colors-tty.sh```

**Comment by dylanaraps** [comment]
Fix:
```sh
alias reset="reset; cat ~/.cache/wal/sequences"
```

**Comment by ohayondotio** [comment]
This doesn't actually solve it, I still have to manually issue the reset command to get the theme back in my terminal.

**Comment by dylanaraps** [comment]
That's the only workaround I've got. There's nothing I can do to fix this on the `pywal` end.

**Comment by BurningFury** [comment]
> Fix:
> 
> ```shell
> alias reset="reset; cat ~/.cache/wal/sequences"
> ```

Been trying to implement a script that upon a command combination (i3) it would launch a new terminal, and run the alias to change colors. Got the variable set for now with
`pycol="$(reset; cat ~/.cache/wal/sequences > /dev/null 2>&1)" `

But after launching the terminal it doesn't change colors automatically. Any dieas?
