### ISSUE TITLE
Oomox theme generation error

### ISSUE THREAD

**Issue by aleprovencio** [dylanaraps/pywal#315]
I'm getting this since last upgrade to oomox `1.7.0.5-2` and pywal `3.1.0-2`:

```
"wsassc: error while loading shared libraries: libsass.so.0: cannot open shared object file: No such file or directory"
make: *** [Makefile:23: css_gtk3] Error 127
```

Maybe I should fill this issue upstream?

**Comment by ltgouvea** [comment]
What's your current setup? It seems reinstalling libsass could solve this error, if you are using an Ubuntu based distro, I suggest you check https://askubuntu.com/questions/849057/how-to-install-libsass-on-ubuntu-16-04

**Comment by den731** [comment]
I had a similiar issue on two machines. I had to downgrade libsass

**Comment by aleprovencio** [comment]
Thanks guys, you are both correct, downgrading libsass did the job.

Are you aware of already reported issues on this?

**Comment by ltgouvea** [comment]
@aleprovencio https://github.com/themix-project/oomox/issues/166

**Comment by aleprovencio** [comment]
Alright, this happens to be just fixed, updating Arch brings the latest versions of `sassc` and `libsass`.

`Oomox` and `pywal` play well again.
