### ISSUE TITLE
Please add suport for Dunst

### ISSUE THREAD

**Issue by Minda1975** [dylanaraps/pywal#322]
Hello. Thank you for your hard work with this project. I have one request. Would it be possible to extend the functionality of the program by adding dunst (it is a lightweight replacement for the notification-daemons provided by most desktop environments) support?

**Comment by ltgouvea** [comment]
You can customize and use this little script to reload dunst with wal colors with `-o reload_dunst.sh` (if I remember correctly I've dug this out of some old commits on this repository)
```
#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
 # Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

 reload_dunst() {
    pkill dunst
    dunst \
	-frame_width 0 \
        -lb "${color0}" \
        -nb "${color0}" \
        -cb "${color0}" \
        -lf "${color7}" \
        -bf "${color7}" \
        -cf "${color7}" \
        -nf "${color7}" &
}

reload_dunst
```

**Comment by Minda1975** [comment]
> You can customize and use this little script to reload dunst with wal colors with `-o reload_dunst.sh` 

Hello. It works partly. In urgency_low, theme changed, but in urgency_normal, not. [Here](https://image.ibb.co/jafCbV/Cheese-18-10-24-20-45-48.png) screenshot. I'm hoping this will help

**Comment by ltgouvea** [comment]
> > You can customize and use this little script to reload dunst with wal colors with `-o reload_dunst.sh`
> 
> Hello. It works partly. In urgency_low, theme changed, but in urgency_normal, not. [Here](https://image.ibb.co/jafCbV/Cheese-18-10-24-20-45-48.png) screenshot. I'm hoping this will help

Hmm, I can't reproduce this error, the script is working for me. I'm using Dunst version **1.3.0 (2018-01-05)**

**Comment by Minda1975** [comment]
> I'm using Dunst version 1.3.0 (2018-01-05)

I'm using Dunst version 1.1.0 (i am on Debian 9.5)...Maybe you could give advice on this? If not, it does not matter. It should be as it is 😄

**Comment by ltgouvea** [comment]
It seems dunst has deprecated such flags (https://github.com/dunst-project/dunst/issues/328) BUT here's the funny thing: Deprecation seems to have happened in version 1.2.0 according to their changelog, I'm using a later version and it's working, your using one pre-deprecation and getting this weird behaviour.....

**Comment by Minda1975** [comment]
> It seems Dunst has deprecated such flags 

It does not matter anymore. I made the configuration manually. Thank you for the help.

**Comment by Minda1975** [comment]
I will close this issue.

**Comment by GloverDonovan** [comment]
If anyone else is interested, I solved this issue by [writing](https://github.com/GloverDonovan/dotfiles/blob/eff7623a9a2e9c7ccedb2c95a1730ac4d523ed9c/wal/.config/wal/templates/dunstrc) my `dunstrc` as a [user template file](https://github.com/dylanaraps/pywal/wiki/User-Template-Files) and [symlinking](https://github.com/GloverDonovan/dotfiles/blob/eff7623a9a2e9c7ccedb2c95a1730ac4d523ed9c/wal/.config/wal/done.sh#L16-L36) the resulting cache file to `~/.config/dunst/dunstrc`.

**Comment by Minda1975** [comment]
>I solved this issue

Thank you for this idea. In the near future I will try.

**Comment by Minda1975** [comment]
> If anyone else is interested, I solved this issue by

Thank you,  GloverDonovan, very much for this tip. Now dunst working the way I wanted.

<a href="https://ibb.co/ki8wOA"><img src="https://thumb.ibb.co/ki8wOA/Cheese-18-10-26-16-50-11.png" alt="Cheese-18-10-26-16-50-11" border="0"></a>

**Comment by Minda1975** [comment]
Finally, with a calm heart😊💗, I can close this problem. Good luck.

**Comment by amenpunk** [comment]
> If anyone else is interested, I solved this issue by [writing](https://github.com/GloverDonovan/dotfiles/blob/eff7623a9a2e9c7ccedb2c95a1730ac4d523ed9c/wal/.config/wal/templates/dunstrc) my `dunstrc` as a [user template file](https://github.com/dylanaraps/pywal/wiki/User-Template-Files) and [symlinking](https://github.com/GloverDonovan/dotfiles/blob/eff7623a9a2e9c7ccedb2c95a1730ac4d523ed9c/wal/.config/wal/done.sh#L16-L36) the resulting cache file to `~/.config/dunst/dunstrc`.

ohhh ty! <3

**Comment by Rockenstien** [comment]
> If anyone else is interested, I solved this issue by [writing](https://github.com/GloverDonovan/dotfiles/blob/eff7623a9a2e9c7ccedb2c95a1730ac4d523ed9c/wal/.config/wal/templates/dunstrc) my `dunstrc` as a [user template file](https://github.com/dylanaraps/pywal/wiki/User-Template-Files) and [symlinking](https://github.com/GloverDonovan/dotfiles/blob/eff7623a9a2e9c7ccedb2c95a1730ac4d523ed9c/wal/.config/wal/done.sh#L16-L36) the resulting cache file to `~/.config/dunst/dunstrc`.

I am getting this error, I have done symlinking but still getting this error
WARNING: Invalid color string: '{foreground}'
WARNING: Invalid color string: '{background}'
WARNING: Invalid color string: '{color4}'
WARNING: Invalid color string: '{foreground}'
WARNING: Invalid color string: '{background}'
WARNING: Invalid color string: '{color4}'

**Comment by masonj188** [comment]
I know this is a year later, but @Rockenstien, you need to create the symlink to the generated file in `~/.cache/wal/dunstrc`, not the dunstrc file in `~/.config/wal/templates/dunstrc`. You have to run `pywal` at least once to get that file generated from the template.
