### ISSUE TITLE
cat sequences causes ]708;[100]#040805 to appear in new termite terminal

### ISSUE THREAD

**Issue by pucerpocok** [dylanaraps/pywal#329]
$ wal -v
wal 3.2.1

For me it seems that commit https://github.com/dylanaraps/pywal/commit/da0e2ff05a885422dfc61fc87ae3c68ec713751b introduced the issue.
In my opinion `set_color` should be used instead of `set_special` (at least for me that resolved it).
(Also adding `4;` before `708;` in .cache/wal/sequences solves the issue temporarily)

During the debugging of this I found another minor coding issue:
in `set_special()` the default value for alpha is `100` (the number), while later in the function the alpha is compared to the string `"100"`(in python the number and string 100 are different),
thus even if the alpha parameter is omitted and the value of it is 100 it will be added to the sequence.
(Again, this is nothing serious, just wanted to leave a note about it)

**Comment by Vichoko** [comment]
The same exactly string appears to me in all opened gnome-terminal and guake when i execute ```wal -R```

**Comment by schlerp** [comment]
same issue with me and termite, I set the 708 line in sequences.py to use set color rather than set special and everything appears to be working perfectly. I didnt read the code to fully understand what was going on, however i have tested a few applications now inside of termite and the colours are rendering properly. 

could a dev please explain the difference between those methods and if its a possible solution?

**Comment by aasril** [comment]
> The same formatted string appears to me in all opened gnome-terminal and guake instances when i execute `wal -R`. I have the same wal version.
> 
> The string printed in my case is:
> `�]708;[100]#0a0c16�\% `

executing `cat ~/.cache/wal/sequences` results on this line on gnome-terminal but not on urxvt and st.

I'm on Ubuntu 16.04. 
wal 3.2.1 (installed with pip)

**Comment by zver43** [comment]
confirm on ArcoLinux v18-10-4 / and new 18-11-2 beta, run i3wm -gaps-next  , Variety for wallpaper + pywal for fun :) 
this happens usually  if more than 1 'termite' terminal is is open - if it is idle *display neofetch or run some app - does not make much sense ,  -  noticed that xfce4-terminal and urxvt stay clean  
![arcolinux-2018-11-07-1541597001_screenshot_1920x1080](https://user-images.githubusercontent.com/44838393/48137799-7c730d80-e2ab-11e8-9db0-a033b81266bf.png)
![arcolinux-2018-11-07-1541597606_screenshot_1920x1080](https://user-images.githubusercontent.com/44838393/48137909-c0661280-e2ab-11e8-90e5-f921933e5c63.png)
![arcolinux-2018-11-07-1541583618_screenshot_1920x1080](https://user-images.githubusercontent.com/44838393/48137990-f3a8a180-e2ab-11e8-95b8-583fef395637.png)

**Comment by Makersmarx** [comment]
As mentioned from others, have same issue on Arch when opening terminal utilizing pywal. String is �]708;[100]#0a0c16�\%

**Comment by aasril** [comment]
@Makersmarx what do you update so the issue resolved itself?

**Comment by Makersmarx** [comment]
Sorry @aasril I should have specified. Termite had an update and that seemed to have resolved the issue for me.

**Comment by aasril** [comment]
@Makersmarx thanks for clarifying that. I don't think gnome-terminal will have an update on Ubuntu soon. But in the meantime the solution @pucerpocok mentioned seems to work without side effects that I can tell.

**Comment by Daniel-Vaz** [comment]
I am having the same problem. 
The fix that @pucerpocok suggested doesn't work for me. I still get the line "]708;[100]#100a18\" every time I source my .bashrc. Any ideas ?

**Comment by Vichoko** [comment]
The solution i found is to downgrade pywal's version with pip. Something like this:
$ pip install pywall==3.0.0

It worked for me.

Pd: i cant remember which version exactly, but anyone before 3.2.1 will work.

**Comment by impankratov** [comment]
> Sorry @aasril I should have specified. Termite had an update and that seemed to have resolved the issue for me.

Indeed, tried python-pywal 3.2.1 with termite 14.2 - got no extra output, everything is clean.

**Comment by aasril** [comment]
@Daniel-Vaz You need to rerun `wal` after making the change. By the way, I changed the 57th line into this.
`set_color(708, colors["special"]["background"]),`

**Comment by Daniel-Vaz** [comment]
> @Daniel-Vaz You need to rerun `wal` after making the change. By the way, I changed the 57th line into this.
> `set_color(708, colors["special"]["background"]),`

Ty worked for me.

**Comment by GijsVermarien** [comment]
Problem was there for me too, indeed rolling back to version 3.0.0 solved the problem for me too.

**Comment by dylanaraps** [comment]
Fixed in master. Use `--vte` with pywal. New release shortly.

**Comment by nomad-mystic** [comment]
On Ubuntu 18.04 (GNOME-terminal) getting this when running wal command. 
 ]708;#06121F\%

pywal version 3.3.0

As mentioned by Daniel-Vaz to modify my sequence.py file for the special characters to not show up on command run. 

sequence.py before: 
def create_sequences(colors, vte_fix=False):
    """Create the escape sequences."""
    alpha = colors["alpha"]

    # Colors 0-15.
    sequences = [set_color(index, colors["colors"]["color%s" % index])
                 for index in range(16)]

    # Special colors.
    # Source: https://goo.gl/KcoQgP
    # 10 = foreground, 11 = background, 12 = cursor foregound
    # 13 = mouse foreground, 708 = background border color.
    sequences.extend([
        set_special(10, colors["special"]["foreground"], "g"),
        set_special(11, colors["special"]["background"], "h", alpha),
        set_special(12, colors["special"]["cursor"], "l"),
        set_special(13, colors["special"]["foreground"], "l"),
        set_special(17, colors["special"]["foreground"], "l"),
        set_special(19, colors["special"]["background"], "l"),
        set_color(232, colors["special"]["background"]),
        set_color(256, colors["special"]["foreground"])
    ])

    if not vte_fix:
        sequences.extend(
            set_special(708, colors["special"]["background"], "l", alpha)
        )

    if OS == "Darwin":
        sequences += set_iterm_tab_color(colors["special"]["background"])

    return "".join(sequences)
``

sequence.py after: 
```
def create_sequences(colors, vte_fix=False):
    """Create the escape sequences."""
    alpha = colors["alpha"]

    # Colors 0-15.
    sequences = [set_color(index, colors["colors"]["color%s" % index])
                 for index in range(16)]

    # Special colors.
    # Source: https://goo.gl/KcoQgP
    # 10 = foreground, 11 = background, 12 = cursor foregound
    # 13 = mouse foreground, 708 = background border color.
    sequences.extend([
        set_special(10, colors["special"]["foreground"], "g"),
        set_special(11, colors["special"]["background"], "h", alpha),
        set_special(12, colors["special"]["cursor"], "l"),
        set_special(13, colors["special"]["foreground"], "l"),
        set_special(17, colors["special"]["foreground"], "l"),
        set_special(19, colors["special"]["background"], "l"),
        set_color(708, colors["special"]["background"]),
        set_color(232, colors["special"]["background"]),
        set_color(256, colors["special"]["foreground"])
    ])

    if OS == "Darwin":
        sequences += set_iterm_tab_color(colors["special"]["background"])

    return "".join(sequences)
```

**Comment by aasril** [comment]
@nomad-mystic Adding `--vte` option not fixing it for you? It works for me.
