### ISSUE TITLE
[SOLVED] Issue with Pywall not Generating full OOMOX Theme when Running wal -g /Desktop/HKE.jpeg

### ISSUE THREAD

**Issue by sporebean22** [dylanaraps/pywal#333]
Hi Guys, 
i am experiencing an issue which is very likely PEBKAC since i am a little unexperienced, sorry about that.
So i installed Pywal and Python3 and whenever i run the regular
`wal -i /Desktop/HKE.jpeg` 
(HKE.jpeg is an image on my Desktop) 
the Commandline colour scheme changes which is wonderful, 
however when i run the following: 
`wal -g /Desktop/HKE.jpeg` 
it does not generate a full UI Theme for my Ubuntu 10.04 Version, i have installed OOMOX but is still does not work for me. what do you guys Suggest? Thank you

**Comment by sporebean22** [comment]
The OOMOX GUI Opens however i would be open to the idea that i may have installed it wrong, Thank you

**Comment by sporebean22** [comment]
Thank you for Answering! 
when i run the 
`wal -i /Desktop/HKE.jpeg -g`
this happens:
![image](https://user-images.githubusercontent.com/33837889/47956599-ba67ed00-df9e-11e8-8999-492dd9a554fd.png)

**Comment by sporebean22** [comment]
Whilst the Theme is still the same:
![image](https://user-images.githubusercontent.com/33837889/47956611-e2575080-df9e-11e8-9d05-315e65cecdb1.png)
Thanks

**Comment by ltgouvea** [comment]
Check if you're setting the generated theme using `lxappearance` or any other theme manager you use, here's my current setting:

![print_03_11_2018_16 32 42](https://user-images.githubusercontent.com/12522078/47956643-5afde300-df86-11e8-828a-a4633c8f70db.png)

**Comment by sporebean22** [comment]
Thank you very much for the help, i feel like i am so close to figuring this out with your help.
i installed lxappearance, and lo and behold wal was one of the options available, however everytime i click on apply - nothing happens and when i close & reopen lxappearance it goes back to the standard clearlooks Ubuntu base theme, what do you suggest, thank you very much

**Comment by sporebean22** [comment]
![image](https://user-images.githubusercontent.com/33837889/47964373-fea3cd80-e030-11e8-9a14-014695a8dd6d.png)

**Comment by sporebean22** [comment]
none of the Themes seem to have an effect for whatever reason, whenever i click on another theme and apply, it doesn't do anything, am i missing something? thank you

**Comment by sporebean22** [comment]
Thank you very much for the Help guys, i figured out what the issue was after all!
what happened before i installed pywal was that i installed the unity tweak tool! so i had unity tweak, OOMOX and Lxappearance reigning for the top spot, however i assume since i installed unity tweak first it took priority, so i went to unity tweak in the themes and wal was an option and that is how it worked for me!!! thanks guys

**Comment by sporebean22** [comment]
now look at this Spanking theme i've got thanks guys!!! 
![image](https://user-images.githubusercontent.com/33837889/47965089-50048a80-e03a-11e8-8e35-67335a33ad70.png)

**Comment by lasers** [comment]
Also, `nautilus` can be running in the background. Use `nautilus -q, --quit` to kill it completely before you try opening a window... Otherwise, you opened one with same theme... which could be the issue too. 


This should be closed. Thanks.

**Comment by dylanaraps** [comment]
oomox support has been removed. I don't use it so I don't keep it up to speed. 

Use wpgtk which supports full themes.
