### ISSUE TITLE
Ugly non-transparent borders in URxvt

### ISSUE THREAD

**Issue by KuxaBeast** [dylanaraps/pywal#334]
I've this small issue, where the alpha value is not applied to background border. Actually values from `xrdb -query` are right, but when applied with `wal -i img.jpg -a alphaval` it makes transparent only background of terminal windows without borders.

When I added an alpha property to color no. 708 in `sequences.py` func. `create_sequences`:
```
# Special colors.
# Source: https://goo.gl/KcoQgP
# 10 = foreground, 11 = background, 12 = cursor foregound
# 13 = mouse foreground, 708 = background border color.
sequences.extend([
    set_special(10, colors["special"]["foreground"], "g"),
    set_special(11, colors["special"]["background"], "h", alpha),
    set_special(12, colors["special"]["cursor"], "l"),
    set_special(13, colors["special"]["foreground"], "l"),
    set_special(17, colors["special"]["foreground"], "l"),
    set_special(19, colors["special"]["background"], "l"),
    set_special(708, colors["special"]["background"], "l", alpha),
    set_color(232, colors["special"]["background"]),
    set_color(256, colors["special"]["foreground"])
]
```
everything appears to work right. Is this intentional or just a mistake?
I really don't know if there is anything this change could break, but if not, I'd love to see this small fix in next update.

EDIT: Oh, I see now. In this (last) commit: [https://github.com/dylanaraps/pywal/commit/da0e2ff05a885422dfc61fc87ae3c68ec713751b](https://github.com/dylanaraps/pywal/commit/da0e2ff05a885422dfc61fc87ae3c68ec713751b), this line was just added.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by edbizarro** [comment]
i notice that in the last days this started to happen again :/

![screenshot-2021-04-1818:19:47](https://user-images.githubusercontent.com/84926/115161221-c9f62600-a072-11eb-9520-a461841e1705.png)
