### ISSUE TITLE
Wal-set script, change dunst color settings

### ISSUE THREAD

**Issue by Antharia** [dylanaraps/pywal#342]
It seems like your wal-set script, linked in customization wiki page, change openbox color settings, and not dunst or lemonbar as written.

**Comment by GloverDonovan** [comment]
I don't use lemonbar, but to change dunst colors all you need to do is create a [User Template File](https://github.com/dylanaraps/pywal/wiki/User-Template-Files) for `dunstrc`, then use `-o` to run a script that restarts dunst on color scheme change. [Here's how I do it](https://github.com/GloverDonovan/.files/blob/0.2.0/dunst/.config/dunst/wal.sh).
