### ISSUE TITLE
[Feature Request] Alternative Export Directory

### ISSUE THREAD

**Issue by simeir** [dylanaraps/pywal#343]
Hello there,

I love the effect of `wal`. Thank you so much for your great work. However, it makes me a little uncomfortable that all files are exported into `$HOME/.cache`. At least from the wiki and the help message I didn't see a way to use an alternative export directory. I expect all files in `$HOME/.cache` are for short-term usage and can be deleted safely at any time. It is also suggested [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) that only "non-essential" data should be stored should be stored in this directory. The files generated by `wal` don't seem to be "non-essential" for me. Some of the files will be loaded again and again, like `colors.sh` for `bspwm`. Missing some of the files will cause applications to malfunction. For example, `rofi` cannot start if it cannot find its theme file. Therefore, I hope there can be a flag to specify an alternative path for the export directory.

**Comment by GloverDonovan** [comment]
If you want a temporary workaround, you should just be able to change `CACHE_DIR` in `settings.py`.

**Comment by dylanaraps** [comment]
Added an environment variable you can set which adds this behavior.
