### ISSUE TITLE
xst not changing background

### ISSUE THREAD

**Issue by dab** [dylanaraps/pywal#347]
Hi there, experimenting with `pywal` and `xst` fork, working well in general, but when executing `wal --theme random` all the colors changing except background color. When opening new `xst` instance it shows proper background. Any suggestions how to fix this?

**Comment by GloverDonovan** [comment]
Sounds like a problem with xst and not pywal. The [README](https://github.com/gnotclub/xst/blob/2b68772aee6311f2597468b09893b9f44c3c2c13/README.md) says that the fork is in progress, and there's a [list of things](https://github.com/gnotclub/xst/blob/v0.7.1/doc/TODO.md) that aren't done yet.
