### ISSUE TITLE
wal: command not found in ~/.xprofile (Ubuntu/Gnome)

### ISSUE THREAD

**Issue by egeogretmen** [dylanaraps/pywal#350]
Hello,

I'm using Ubuntu/Gnome and to make the colorscheme persist I created the file ~/.xprofile (as it did not exist before) and added the line `wal -R`. However when I reboot, I get the message that the wal command not being found. Here is where wal is located: `/home/ege/miniconda3/envs/minico/bin/wal`. So should I invoke using the full path or is this just a workaround?

Best,
Ege

**Comment by GloverDonovan** [comment]
You should probably install pywal with your package manager instead of relying on a bin directory in your `$HOME`. If wal is not in your `$PATH`, then you will have to use the full location as expected.

**Comment by egeogretmen** [comment]
Why is this issue closed?

**Comment by dylanaraps** [comment]
Not an issue with pywal.

**Comment by egeogretmen** [comment]
I understand. Then it would be good to know what the issue is about and how I can fix it.

**Comment by dylanaraps** [comment]
Install pywal with your package manager.
