### ISSUE TITLE
Remove the need for urgent-border patch

### ISSUE THREAD

**Issue by hollystandring** [dylanaraps/pywal#356]
I was wondering if the requirement for the urgent-border patch could be removed for DWM as the patch is currently pretty out of date and will not patch without a lot of tinkering on multiple machines I have tested on.

**Comment by SynKronus** [comment]
To use the colors generated by pywal when it is restored with the command: wal -R

It is not necessary to have the urgent border patch, the idea is that whenever the theme is changed and restored, the last line of the urgent borders ends up being added and as the dwm is the last to be executed in .xinitrc it ends up not compiling .

The only change required is to apply the patch below that works in the current version of dwm 6.1.

Of course this is just a patch: P, but it will be working as soon as it's applied.

Remember that this will only work if done the steps described in the wiki correctly: https://github.com/dylanaraps/pywal/wiki/Customization#dwm.

[wal.patch.zip](https://github.com/dylanaraps/pywal/files/2751452/wal.patch.zip)

**Comment by SynKronus** [comment]
it works!

![2019-01-11-214053_1280x1024_scrot](https://user-images.githubusercontent.com/46579395/51065027-e2e91480-15e9-11e9-847f-16b0a84e2db4.png)
![2019-01-11-214105_1280x1024_scrot](https://user-images.githubusercontent.com/46579395/51065029-e2e91480-15e9-11e9-8501-2ade94824674.png)
