### ISSUE TITLE
colors.Xresources isn't updated

### ISSUE THREAD

**Issue by Jafarov95** [dylanaraps/pywal#359]
I'm having a problem with my config. Pywal doesn't seem to be updating `colors.Xresources` in `~/.cache/wal/` when I run `wal -g -i [image]`. Even when I delete the file, it reloads with the same colors when I run wal again. My urxvt, gtk and rofi colors update and change everytime but not my polybar colors. Running `xrdb -query` returns the old repeating colors as well. I'm not sure where pywal is even getting these colors from. 

I'm running Arch with `wal 3.2.1-2` from the official repos. Let me know if any other details are needed.

**Comment by deviantfero** [comment]
do you have any colors defined in your `.Xresources`?

**Comment by Jafarov95** [comment]
No, here is my Xresources. It used to have colors defined but I removed them a while ago trying solve this problem. 

```
URxvt*scrollBar:         false
URxvt*scrollBar_right:   false

URxvt*transparent:       false

URxvt.font: xft:cherry-13-r
URxvt.letterSpace: 0

*antialias:  true
*autohint:   false

URxvt.perl-ext-common: default,matcher
URxvt.url-launcher: Firefox
URxvt.matcher.button: 1
```

**Comment by Jafarov95** [comment]
Figured it out. For some reason I had put a copy of my old Xresources file in the templates folder.
