### ISSUE TITLE
Easier method of overriding color schemes

### ISSUE THREAD

**Issue by undying-fish** [dylanaraps/pywal#36]
Sometimes you're lumped with a wallpaper that only uses two colours, say, and that's always been a weak point of `wal`. In that case, I've got a suggestion - a flag that defines only the foreground and background colors. Predefined color schemes such as the ones available on terminal.sexy would fill the rest of the colors.

**Comment by dylanaraps** [comment]
I think that this over complicates things, `wal` is meant to be as simple as possible. 

`wal` is really dumb in the sense that it doesn't "know" what colors are. It just repeatedly calls `imagemagick` till it gets 16 colors and then blindly maps those colors to a scheme. `wal` doesn't know if the generated colors will work well together or not it doesn't care. 

`wal` makes various assumptions on the list of colors. It assumes that there'll be enough contrast between color 0 and color 15 to make them background and foreground colors. It assumes that the colors 9-14 will be legible on color 0 as a background.

These assumptions work for 99% of images but there are the images that slip through and provide mediocre results. This is what makes `wal` so great in my eyes, despite it being so simple it gives amazing results.

Now taking only 2 colors from an image is where things will get messy, we can't assume that the scheme we mix with the 2 colors will work well. We can't even assume if the 2 colors from the image will work together as background and foreground colors.

What I can look into is taking one of the 2 colors and generating a palette based on brightness. If the color is red we'll generate a palette that is just reds from dark to light etc. I'm not sure about how well this will work but it should help fill that 1% gap.
