### ISSUE TITLE
Add I3status suport

### ISSUE THREAD

**Issue by annata83** [dylanaraps/pywal#361]
How are you doing? Do you think it will be nice to have a tutorial on how to ad pywal into i3 status?
I did it like this:
in .Xresources i added:
*color0: {color0)
*color1: {color1}
*color2: {color2}
*color3: {color3)
*color4: {color4}
*color5: {color5}
*color6: {color6)
*color7: {color7}
*color8: {color8}
*color9: {color9)
*color10: {color10}
*color11:{color11}

and then I create the colors in i3 with:
set_from_resources $color0 color0
Finally, I just pick the colors for i3status with something like this inside bar:

colors {
  background $color0
and so on!!...
It works very well on my end!

**Comment by dylanaraps** [comment]
Add it to the wiki, I don't use i3 so I have no interest in doing this myself.
