### ISSUE TITLE
Sway command for setting the wallpaper

### ISSUE THREAD

**Issue by Kaligule** [dylanaraps/pywal#362]
Currently [we use](https://github.com/dylanaraps/pywal/blob/master/pywal/templates/colors-sway#L1) `set $wallpaper {wallpaper}` for changing the wallpaper in sway. This doesn't work for me (the wallpaper just doesn't change.

Sways documentation (`man 5 sway` ) tells us that the wallpaper should be set with the output cummand:

>        output <name> <background|bg> <file> <mode>
>            Sets the wallpaper for the given output to the specified file, using the given scaling mode (one of "stretch", "fill", "fit", "center", "tile")

And indeed running this line works fine for me:

```
output "*" background path/to/wallpaper/jpg fill
```

Honestly I am not sure how the current setup could ever have worked. Can anyone confirm what is going on here? Should we just replace the line with `output "*" background {wallpaper}`? I am happy to do a pullrequest, but I would like for someone more familiar with pywal (and perhaps even sway) to look over this. (@ranisalt or @dylanaraps perhaps?)

**Comment by dylanaraps** [comment]
I don't use sway, maybe it changed in a newer version. Anyway, I'm happy to accept a PR.

**Comment by Kaligule** [comment]
I just realized that I just didn't read the documentation well enough: https://github.com/dylanaraps/pywal/wiki/Customization#sway

The line I discussed isn't for setting the wallpaper, it is just for setting the variable which is later used to set the wallpaper. Stupid me.

Evrything seems right now. Thank you :)
