### ISSUE TITLE
Support for remote images

### ISSUE THREAD

**Issue by Kaligule** [dylanaraps/pywal#364]
If the path to the image is an url to an image (like in `wal -i https://3.bp.blogspot.com/-mXkypTgOshE/WN_w2bxPThI/AAAAAAAAA20/1d0k2YUy6C40B8qF0IutEy-XBZanRqdLACEw/s1600/198.jpg`) then pywal should download the image to .cache/wal and use it from there.

This would allow to go through places like /r/wallpaper and generate themes fast until an especially great one is found.

**Comment by dylanaraps** [comment]
What's required here dependency wise?

Also you can very easily script this with `wget` or `curl`.

**Comment by dylanaraps** [comment]
Closing this as I feel its out of scope. This can easily be done with a script.
