### ISSUE TITLE
Pywall and yakuake 

### ISSUE THREAD

**Issue by Migacz85** [dylanaraps/pywal#367]
After installing pywall, every time when running command:
wal -R
is producing unexpected result of writing "\\\\\\\\" in to yakuake:
![screenshot_20190117_165637](https://user-images.githubusercontent.com/25789997/51335042-fdebd680-1a78-11e9-9054-e9833cdeeba4.png)

I'm not quite sure what is going on here.

**Comment by dylanaraps** [comment]
This is fixed in master with the flag (`--vte`).

This is an issue with older VTE versions and a specific escape sequence.
