### ISSUE TITLE
debian sid : [I] sequences: Set terminal

### ISSUE THREAD

**Issue by ycf83** [dylanaraps/pywal#368]
hi i get this with pywal 

↳ wal -g -i ~/wallpaper/wallx103.jpg
[I] image: Using image wallx103.jpg.
[I] theme: Set theme to _home_d-ina_wallpaper_wallx103_jpg_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
]708;[100]#0a0910\[I] sequences: Set terminal
[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
[W] reload: Oomox not found, skipping.

i get this ]708;[100]#0a0910\ , i don't know way, and always , i run termite:
i get this

]708;[100]#0a0910\]708;[100]#0a0910\%

**Comment by dylanaraps** [comment]
Fixed in master. Use `--vte`.

**Comment by ycf83** [comment]
thnk's for replay, can u please show me how to do , i don't know how to use --vte
