### ISSUE TITLE
Running on my Mac messed up some core functionality

### ISSUE THREAD

**Issue by Sammyalhashe** [dylanaraps/pywal#369]
I recently tried running on my Mac (Mojave 10.14.2). After running, it turned my wallpaper black and I cannot change it back. In addition, I can no longer make applications go fullscreen mode. 

The command I ran was `wal -i {path_to_picture}`

Any help with this would be greatly appreciated.

**Comment by Sammyalhashe** [comment]
Thank you for that, it fixed it for me (so far). I am impressed with pywal, and I'll gladly use it once these mac issues have been sorted out.

**Comment by deviantfero** [comment]
You can also avoid setting a wallpaper with pywal, which I think it's the root cause of the issue, everything else should work fine.
