### ISSUE TITLE
Alacritty doesn't seem to be working with wal

### ISSUE THREAD

**Issue by omrisim210** [dylanaraps/pywal#37]
I installed Void Linux today and finally managed to get pywal working (it only has py3.5 so I compiled 3.6.1 with pyenv) and since it doesn't have Termite (my go-to terminal) in it's repos I decided to try [Alacritty](https://github.com/jwilm/alacritty) (it's supposed to be fast). So turns out it's dash-fast, as in "lacks too many useful features" (probably because it's still in alpha). The `printf "%b" "\033]11;#ff0000\007"` does nothing so I guess you should add it to the list. I tried to make it work with wal by having a `config.yml` that contains non-color options and an auto-generated `colors.yml` that has colors (used [termcolors](https://github.com/stayradiated/termcolors) to convert to Alacritty's format), what I did was add this function:

```
function fix_alacritty() {
	local dir="${HOME}/.config/alacritty"
	rm "${dir}/alacritty.yml"
	cat "${dir}/config.yml" "${dir}/colors.yml" >> "${dir}/alacritty.yml"
}

```
And call it in the script that gets executed after wal, turns out Alacritty needs everything to be in specific positions for the thing to work (it is possible with some mad regex-foo or yaml parsing, both of which I'm no good at and not going to try doing since the benefits aren't that good, not being able to change colors on the fly is a bummer)

So I guess it's not really an issue with wal but I'm just letting you know

**Comment by dylanaraps** [comment]
Thanks for doing all of this testing!

We could try and open an issue on Alacritty's bug tracker, I did a quick search and couldn't find anything.

**Comment by dylanaraps** [comment]
Issue opened on Alacritty's repo: https://github.com/jwilm/alacritty/issues/656

**Comment by dylanaraps** [comment]
Alacritty is now supported! :D

**Comment by Cakedy** [comment]
So, how would I add wal to alacritty? It does work, but I need to re-run wal every-time I open a new alacritty instance.

**Comment by omrisim210** [comment]
You should be able to just add `wal` (and whatever parameters you pass to it) to your shell's rc file, for Bash it's `~/.bashrc`.

**Comment by Cakedy** [comment]
So what you're telling me is that I should just add the `wal` command to my shell rc file?

(e.g. `wal -i /path/to/wallpaper in .zshrc`)

**Comment by omrisim210** [comment]
Something like that. Maybe only do it when running in a graphical session, I haven't used wal in a long time so I can't remember what I used to do.

**Comment by Cakedy** [comment]
It worked! Thanks.

**Comment by FranciscoJRSantos** [comment]
[MacOS] I've recently installed alacritty, and pywal doesn't seem to be working! Am I missing something? 
I've got the command `(cat ~/.cache/wal/sequences &)` in my .zshrc file
Whenever I try to `wal -i /path/to/wallpaper` it just does nothing.

**Comment by dylanaraps** [comment]
I have no way of debugging macOS. Alacrity works just fine on my Linux install. 

Are you using the latest version of Alacritty?

**Comment by FranciscoJRSantos** [comment]
Just reinstalled Alacritty to make sure I have the latest version but the same problem still arises. Whenever I use `wal -i` it reads the wallpaper but the colors never change. Is there a log file or something alike that I can check to know more details about the problem?

**Comment by dylanaraps** [comment]
What version of alacritty are you using?

**Comment by FranciscoJRSantos** [comment]
I'm using the latest on their repo, can't really give you a number as I don't know any command the shows me the Alacritty version nor have they got any releases or tags on the repo.

**Comment by Amar1729** [comment]
This is still a problem with a fairly recent (march 01) [version of Alacritty](https://github.com/jwilm/alacritty/commit/475ebecfc4e0648242e82e256dee1489f3a3fe81) on macOS.

Oddly enough `printf "%b" "\033]11;#ff0000\007"` does change the background to red, but `cat sequences` does nothing. Running `wal -i <file>` changes the colors of iTerm2 windows but not Alacritty.

**Comment by dylanaraps** [comment]
It might be worth opening a bug on their tracker. Alacritty works fine on Linux.

**Comment by egeesin** [comment]
I just wrote a workaround that may help Mac users who want wal colors in Alacritty: https://github.com/egeesin/alacritty-color-export

**Comment by rugglcon** [comment]
@egeesin this is confirmed working for me on MacOS 10.15.2, alacritty 0.3.3

**Comment by rugglcon** [comment]
@dylanaraps if you don't mind, I'd like to add this to the Wiki as a section under the terminal customization, something like "Alacritty on MacOS".

**Comment by dylanaraps** [comment]
Go ahead! :+1:

**Comment by rugglcon** [comment]
Done 😃
