### ISSUE TITLE
wal 3.3.0 bug persiste 

### ISSUE THREAD

**Issue by ycf83** [dylanaraps/pywal#370]
i always get this with last pywal & termite

![2019-01-21-211721_1570x820_scrot](https://user-images.githubusercontent.com/39797567/51497005-1124dc00-1dc2-11e9-8da0-41f15be99266.png)

**Comment by deviantfero** [comment]
have you tried using `--vte`?

**Comment by ycf83** [comment]
no, i don't know how to do ?
i use this : wal  -i ~/wallpaper/wallx103.jpg
how to add --vte

**Comment by ycf83** [comment]
all okay
