### ISSUE TITLE
Why dropping oomox ?

### ISSUE THREAD

**Issue by Fuzzbox999** [dylanaraps/pywal#374]
Wpgtk may be nice (and bloated ?), but why breaking users scripts making use of wal + oomox and who were happy with that ? Were they mutually exclusive ?

**Comment by Fuzzbox999** [comment]
Thank you for taking the time to answer me, and for your suggestions. 
I've downgraded pywal for now, but I'll have a closer look to wpgtk, especially after its upgrade.

**Comment by deviantfero** [comment]
You can open an issue un wpgtk just for me to help you out, I'd be glad to,
don't really know why the wal -R tho, it does not seem necessary

**Comment by actionless** [comment]
oomox dev here:
yes, i can confirm what integration part was very out-of-date (somewhere for oomox ver 0.3-0.4), it not supports choosing themes other (Arc, Materia) than default and all the possible options for default theme. not supports icons, spotify.

if you want to continue using oomox:
1) consider either importing colors from image right in the oomox GUI
2) or generate xresources theme in wal and using xresources oomox themes (currently importing xrsources themes a bit limited in options but some more options can be added if it will have interest)
