### ISSUE TITLE
Update GTK2/3 Theme Generation Instructions

### ISSUE THREAD

**Issue by paanvaannd** [dylanaraps/pywal#375]
I followed the instructions on the wiki for GTK2/3 theme generation using `wal` and was confused as to why I was hitting errors when running the command with the `-g` flag when the wiki told me to do so yet the app didn't seem to recognize the flag at all.

I learned from #374 that `oomox` support is being dropped, and the wiki should reflect that so as not to confuse future users.

**Comment by dylanaraps** [comment]
Fixed.
