### ISSUE TITLE
Polybar boot

### ISSUE THREAD

**Issue by fwanky** [dylanaraps/pywal#377]
Is there some setting i'm missing to have polybar keep the new colourscheme settings upon boot? 

I normally just have `exec_always --no-startup-id $terminal wal -i Pictures/Wallpapers/031.jpg -n` in my i3 config to get it to set on boot, but i'm probably doing this stupidly and missing a section from the wiki..

**Comment by dylanaraps** [comment]
How are you using the colors with polybar?
