### ISSUE TITLE
[enhancement request] Allow Reload of Waybar

### ISSUE THREAD

**Issue by weasnerb** [dylanaraps/pywal#379]
Currently pywal reloads things like gtk, xrdb, i3, sway, polybar. I would like it to also reload [Waybar](https://github.com/Alexays/Waybar)

I tried adding
```python
def waybar():
    """Reload waybar colors."""
    if shutil.which("waybar") and util.get_pid("waybar"):
        util.disown(["pkill", "-USR1", "waybar"])
```
to the reload.py, however I did not get the expected results, and doing
```python
def waybar():
    """Reload waybar colors."""
    if shutil.which("waybar") and util.get_pid("waybar"):
        util.disown(["pkill", "waybar"])
        util.disown(["waybar"])
```
closed waybar, but did not restart it :disappointed: 

I could see this becoming a feature request if we wanted to add a flag that allows the user to input the name/names of a process they would like to reload.

**Comment by SethBarberee** [comment]
How are you currently running waybar in your config?

Currently I do
```
bar {
     swaybar_command waybar
}
```

This config reloads waybar when sway is reloaded

**Comment by weasnerb** [comment]
I have had to use `exec waybar` because for some reason as what you have (and is recommended in the waybar docs) doesn't work for me, and I have no idea why it doesn't.

**Comment by weasnerb** [comment]
I updated my waybar-git package, and it seems to work now the way that you described, thanks!
