### ISSUE TITLE
random output when using wal

### ISSUE THREAD

**Issue by spyrotecher** [dylanaraps/pywal#381]
When using wal -i and chnging it would usually output some 3 random numbers followed by the first hex value of the first pallete it generated

**Comment by spyrotecher** [comment]
[I] theme: Set theme to colors.json.
]708;#0B0909\[I] sequences: Set terminal colors.

                                
                                

[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.

**Comment by spyrotecher** [comment]
And the ]708;#0B0909 for some reason just outputs even if i run wal -i "some/image/path" >/dev/null

**Comment by dylanaraps** [comment]
Use `--vte` with `pywal`. If the option doesn't exist, update `pywal`.

**Comment by spyrotecher** [comment]
Thanks, worked like a charm
