### ISSUE TITLE
New colors are not generated when file name stay the same, but file itself changes.

### ISSUE THREAD

**Issue by Migacz85** [dylanaraps/pywal#385]
wal 3.2.1

New colors are not generated when file name stay the same, but file itself changes.

1. Take image file run wal on it
2. Change the file but keep filename same
3. Run wal on it again, 

wallpaper is changing but color schemes are from First file.

**Comment by dylanaraps** [comment]
I've been aware of this for a while. The issue is fixing this in a performant way.

**Comment by Migacz85** [comment]
performant way ? Is there a method or something that I can run after to force pywall to recalculate the colors on the file? I belive this is some kind of "caching" inside pywall.

**Comment by Migacz85** [comment]
For me this is huge issue. I have keys binded to light and dark versions of terminal based on colorschemes that pywall produced. I was beleving that after I will just simply change files itself and I would have easy modificable system for managing themes for console.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by Migacz85** [comment]
@dylanaraps  Brilliant thank you!, when the new version of pywall will be avaliable on AUR packages for arch with that fix ?

**Comment by guilhermecomum** [comment]
Hi I'm still getting this issue using 3.3.0 version =
