### ISSUE TITLE
[Feature suggestion] Razer peripherals colors/reload

### ISSUE THREAD

**Issue by LoLei** [dylanaraps/pywal#391]
I recently made a rudimentary [script](https://github.com/LoLei/dotfiles/blob/master/set-keyboard-color.py) to use pywal's colors to change the colors of my Razer peripherals (keyboard and mouse). This doesn't use pywal as a module, but just the current colors in the Xresources, which have previously been set via pywal.

I was wondering whether it's feasible to include this in pywal? Maybe as an optional parameter, since [openrazer](https://github.com/openrazer/openrazer) is then required. I could see it being included in the [`reload.py`](https://github.com/dylanaraps/pywal/blob/master/pywal/reload.py) functionality.

If @dylanaraps says it's a feature that fits pywal I could create a PR for it, if it's a bad idea I won't bother, so that's why I'm making this preliminary investigation. Also, other users, feel free to chime in.

**Comment by dylanaraps** [comment]
This is best kept as an external script imo. Pop it in its own repo and add it to the wiki here. :)

**Comment by LoLei** [comment]
Good idea, I'll do it that way then!
