### ISSUE TITLE
colors.sh cannot read filenames containing single quotes

### ISSUE THREAD

**Issue by iwconfig** [dylanaraps/pywal#392]
Please consider using double here instead:

https://github.com/dylanaraps/pywal/blob/975c00f30e7a9e0a40afc7bf0f2c1f2d06419867/pywal/templates/colors.sh#L3

If the filename contains single quotes, for example "jackal's", the `wallpaper` variable in my generated colors.sh looks like this:

    wallpaper='/home/ludde/.background-jackal's'

By which I of course get this error:

    /home/ludde/.cache/wal/colors.sh: line 26: unexpected EOF while looking for matching `''
    /home/ludde/.cache/wal/colors.sh: line 34: syntax error: unexpected end of file

I tried escaping the single quote but no luck. Also, I use a script which generates a background without me knowing the filename. Of course I could work around this with a little ambition but changing to double quotes is a much simpler solution to my problem.

**Comment by dylanaraps** [comment]
Fixed :+1:

**Comment by iwconfig** [comment]
Great! Awesome piece of software btw. Thanks!
