### ISSUE TITLE
macOS: iTerm crash, UI elements gone

### ISSUE THREAD

**Issue by phlind** [dylanaraps/pywal#398]
I used pywal on my MacBook and have a significant problem now. First, iTerm crashed, then the desktop wallpapers went black and all the OS elements like the dock and the ability to switch between apps with Cmd-Shift etc. or the window overview (F3) are gone resp. don't work anymore. I also can't set any wallpaper with the settings app.

 iTerm seems to be connected to the problem. It wanted to do something like a benchmark or similar when it crashed (I couldn't really read it, but it said something like "CPU test" or similar.) Anyway, if I start iTerm now, it doesn't work, no window shows up. 

I already logged out and back in, nothing changed.

Does anyone have an idea what process could be connected? I already tried `killall` dock and it says "no process found". I also restarted the WindowServer by `sudo killall -HUP WindowServer`, but no change.

I ask here, because someone might know with which processes pywal communicates when changing the wallpaper in OSX. 

Thanks

**Comment by robwaz** [comment]
What version of MacOS are you running?

**Comment by phlind** [comment]
I used Mojave (10.14.4) and I found that the issue was already discussed here: https://github.com/dylanaraps/pywal/issues/330

So, the solution was to delete this file:

`rm ~/Library/Application Support/Dock/desktoppicture.db`

**Comment by llhhaa** [comment]
For copy-pasters, the command is missing a slash:

`rm ~/Library/Application\ Support/Dock/desktoppicture.db`
