### ISSUE TITLE
Cache files change but DWM colors do not

### ISSUE THREAD

**Issue by joestandring** [dylanaraps/pywal#399]
Hey so I'm trying to use pywal with DWM and I'm coming across and issue where my DWM color scheme does not update (although the file in ~/.cache/wal does). As I had a lot of issues with it I gave up using the urgent-borders patch and created a new colors-wal-dwm.h template removing references to urgent border so it is only containing this:
```
static const char norm_fg[] = "{color15}";
static const char norm_bg[] = "{color0}";
static const char norm_border[] = "{color8}";

static const char sel_fg[] = "{color15}";
static const char sel_bg[] = "{color2}";
static const char sel_border[] = "{color15}";

static const char *colors[][3]      = {{
    /*               fg           bg         border                         
    [SchemeNorm] = {{ norm_fg,     norm_bg,   norm_border }}, // unfocused wins
    [SchemeSel]  = {{ sel_fg,      sel_bg,    sel_border }},  // the focused win
}};
```
I have also followed the customization page and modified my dwm config.h file appropriately, and using the unmodified colors-wal-dwm.h file works.

**Comment by joestandring** [comment]
Ok it seems running sudo make clean install updates the colors _once_, but it needs to be run every time a new cache file is generated to use the colors

**Comment by joestandring** [comment]
Oh right it would help if I mentioned im running wal from .xinitrc

**Comment by dylanaraps** [comment]
Yes, you need to rebuild it every time. Yucky, I know.

**Comment by nullst8** [comment]
has it been fixed or do I still need to recompile it everytime?
