### ISSUE TITLE
Problems Using pywal with Gnome-Terminal

### ISSUE THREAD

**Issue by edward-teixeira** [dylanaraps/pywal#404]
I'm having trouble making pywal work with gnome-terminal. I'm having these errors text everytime i open my terminal. I'm using i3wm.

![Gnome-pywal-error](https://user-images.githubusercontent.com/45992962/55583135-8af91000-56f7-11e9-81a2-e648488cc2be.png)

**Comment by kaewhyes** [comment]
This can be solved by running pywal with the flag `--vte`

**Comment by edward-teixeira** [comment]
Solved, thanks!
