### ISSUE TITLE
flash when opening terminal shows old colourscheme (i think)

### ISSUE THREAD

**Issue by ghost** [dylanaraps/pywal#407]
You should be able to see it here in this video;
https://0x0.st/zZpm.mp4
I have everything set in my .bashrc and so on. 
Terminal is urxvt, could it be because of the terminal?

**Comment by zzzeyez** [comment]
it happens to me too with `zsh`.  it is somewhat alleviated by putting it at the top of my `.zshrc` instead of the bottom.  i don't remember it happening with `fish`

**Comment by LoLei** [comment]
Happens to me too on `urxvt` and `zsh`, it's most likely just all my `zsh` config loading before I execute the `wal` reload.

**Comment by dylanaraps** [comment]
Put the `wal` command near the start of your shell config.
