### ISSUE TITLE
wal: Imagemagick couldn't generate a palette

### ISSUE THREAD

**Issue by mlisitsky** [dylanaraps/pywal#417]
I seem to be experiencing a similar problem to issue #232 and issue #131, however, none of the fixes mentioned in those issue reports have seemed to work for me. I had been using pywal for a couple years with no issues, but I had not run the command for the last couple of months. 

I have tested the wal command with dozens of pictures, clearing the cache each time with wal -c and trying the commands with and without --vte.

I am using Arch Linux 64-bit, with i3 version 4.16.1 as my window manager. I have tested this with the python-pywal package in the arch repository, and with manually installing pywal from git. (3.3.0) I have tested it with Imagemagick (7.0.8.47-1) and Imagemagick-git (7.0.8.45). Every time I run the command, I get the following error, reposted below for completeness. 

```
wal -i (IMAGE_PATH)
[I] image: Using (IMAGE_PATH)
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 16
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 17
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 18
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 19
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 20
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 21
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 22
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 23
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 24
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 25
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 26
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 27
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 28
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 29
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 30
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 31
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 32
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 33
[W] wal: Imagemagick couldn't generate a palette.
[W] wal: Trying a larger palette size 34
[E] wal: Imagemagick couldn't generate a suitable palette.
```

**Comment by deviantfero** [comment]
what is the image in question?

**Comment by mlisitsky** [comment]
I tested it with each of the images in this album and got the same result for all of them.

https://imgur.com/a/MTDcNiL

The images seem to contain a wide variety of colour palettes and art styles, so I don't think the issue is with any specific picture.

**Comment by dylanaraps** [comment]
Have you tried another `pywal` backend? There may be an issue with `imagemagick` on your machine.

To try `colorz` just install it and run `wal --backend colorz etc etc`.

```sh
pip3 install --user colorz
```
