### ISSUE TITLE
Zshrc lines not working

### ISSUE THREAD

**Issue by raphaelfournier** [dylanaraps/pywal#420]
I have placed the required line `(cat ~/.cache/wal/sequences &)` in my .zshrc, but new terminals starts with the result of this `cat` (i.e., it prints the content of the file). The colors of urxvt are not changed. I would obviously like to have the reversed, colors changed and not line at the start of a new terminal.
How can I investigate this undesired behavior?

**Comment by deviantfero** [comment]
what is the content that gets print out into the terminal?

**Comment by raphaelfournier** [comment]
Oh, I have just solved the problem by answering your question! My `cat` utility is aliased to `bat` (https://github.com/sharkdp/bat), and if I use `\cat .cache/wal/sequences` (with a backslash to have the real cat), I get the expected behavior (ie, a theme change). 

For reference, here is the content of the file:
`4;0;#14140b4;1;#7487924;2;#7993A34;3;#8D92924;4;#99A1A44;5;#AFB1B04;6;#C1BCB44;7;#e1dbd24;8;#9d99934;9;#74│87924;10;#7993A34;11;#8D92924;12;#99A1A44;13;#AFB1B04;14;#C1BCB44;15;#e1dbd210;#e1dbd211;85]#14140b12;#e1db│d213;#e1dbd217;#e1dbd219;#14140b4;232;#14140b4;256;#e1dbd2708;[85]#14140b`

Thank you!

**Comment by AmithKumar1** [comment]
Pywal is not changing at real-time, I have to do that manually. how can I solve this
