### ISSUE TITLE
Terminator with pywal. First line shows strange symbols 708;#0f0f10\]708;#0f0f10\% 

### ISSUE THREAD

**Issue by Minda1975** [dylanaraps/pywal#422]
Hello. I use pywal (version 3.3.0) with terminator (version 1.90+bzr-1705-1) in Debian 9.9. In others terminals (xterm, st and rxvt-unicode-256color) pywal works very well. Maybe someone could advise how I can solve this problem?
P.S.
I tried ` wal -c` and then `wal -i img` but that didn't help.

P.S.S.
Here screenshot:
![2019-06-04-05-45-35](https://user-images.githubusercontent.com/16372284/58889081-0fb0dc00-86f1-11e9-9cf4-b2f886b776bd.png)

**Comment by dylanaraps** [comment]
Use `--vte` with all commands.
