### ISSUE TITLE
Terminator and pywall 

### ISSUE THREAD

**Issue by Minda1975** [dylanaraps/pywal#423]
Hello. Sorry for noob question.

 I solve the problem #422, with adding lines  `wal --vte -i img`. Thank you for the tip. But now i have another problem. 

After rebooting, terminator again shows these  strange symbols 708;#0f0f10\]708;#0f0f10\% (issue #422).

I use .zshrc for shell's start up file with these lines `(cat ~/.cache/wal/sequences &)` and wall command for making the color scheme persist on reboot (restores the last color scheme that was in use.) `wal -R`

How I can solve this problem?

Thank you.

**Comment by dylanaraps** [comment]
You need to add `--vte`  to all `wal` commands.

**Comment by Minda1975** [comment]
> You need to add `--vte` to all `wal` commands.

Hello. You mean like that:

`wal  --vte -R` ?
