### ISSUE TITLE
Error with backend

### ISSUE THREAD

**Issue by emorevival** [dylanaraps/pywal#424]
EDIT: https://pastebin.com/NvcY4zq5 for readability 

When I try to specify the backend, I get an error: 

`✗ Pictures wal --backend colorz -i "coolPicture.jpg"
[I] image: Using image coolPicture.jpg.
[I] colors: Generating a colorscheme.
/usr/lib/python3.7/site-packages/PIL/Image.py:115: RuntimeWarning: The _imaging extension was
built for another version of Pillow or PIL:
Core version: 5.3.0.post1
Pillow version: 6.0.0
  warnings.warn(str(v), RuntimeWarning)
[E] colorz: colorz wasn't found on your system.
[E] colorz: Try another backend. (wal --backend)
✗ Pictures`

No matter which backend I use, it's the same error, and yes I've correctly installed the backends through pip3. Googling the issue didn't help much, as the answers suggested installing packages which I already had. I'm sorry if this is a known/easy fix, but I'm clueless. I wanted to use haishoku initially. 

`wal --backend` does list all the backends.
I have installed all backends that I've tried, except schemer2 because it wouldn't install.

**Comment by dylanaraps** [comment]
This is an issue with your system.
