### ISSUE TITLE
Pip3 install pywal does not install the latest version? [Mac OSX]

### ISSUE THREAD

**Issue by nraiha** [dylanaraps/pywal#425]
I get the (already fixed) error:

> pidof: illegal option -- s

I have installed pywal through pip3 and `pip3 show pywal ` tells me the version is 3.3.0.
When inspecting the code in `/usr/local/lib/python3.7/site-packages/pywal/util.py`, the code is not the same as it is in the github's latest version. 

Manual installation works just fine but I could mention I had to add ~/Library/Python/3.7/bin/ to path, instead of /.local/bin/

**Comment by dylanaraps** [comment]
I will make a new `pywal` release soon. Till then you can run the following command.

```sh
pip install --user https://github.com/dylanaraps/pywal/archive/master.zip
```

**Comment by ryuta69** [comment]
@dylanaraps 
Hi, I really love this OSS, thank you very much.

This issue seems to continue still now.
Do you plan to update, or is there something should be fixed before update?
