### ISSUE TITLE
Problems with cache after changing wallpaper on i3

### ISSUE THREAD

**Issue by GreyDireWolf** [dylanaraps/pywal#429]
I use ranger with feh to setup wallpaper which sets up wallpaper and copies it to ```~/.config/wall.png```. In my i3 config feh sets up wallpaper which is in ```~/.config/wall.png``` and then wal is called to change colorscheme. But when I change the wallpaper wal rolls back to colorscheme of previous wallpaper. I guess this is because new wallpaper has same name and location. I have to explicitly delete ```~/.cache/wal/schemes``` to apply new colorscheme.

**Comment by ramenbroth** [comment]
Just experienced the same thing and was about to open an issue, if you swap an image for another but keep the name, cache will ignore the fact that it's a new image.

**Comment by dylanaraps** [comment]
This is fixed in master.
