### ISSUE TITLE
Set some colours back to default

### ISSUE THREAD

**Issue by jerpint** [dylanaraps/pywal#432]
I really like this plugin. However, sometimes, the colours I use don't make sense in certain programs in my terminal. For example, when I use diffs in terminal, the colours no longer make sense to me compared to the defaults I used to have (i.e. green and red). How can I revert colours back for certain programs? In the case of diffing, these are the settings I use:

```
git config --global color.diff-highlight.oldNormal    "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal    "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

git config --global color.diff.meta       "yellow"
git config --global color.diff.frag       "magenta bold"
git config --global color.diff.commit     "yellow bold"
git config --global color.diff.old        "red bold"
git config --global color.diff.new        "green bold"
git config --global color.diff.whitespace "red reverse"
```

However they seemed to be overridden by pywal.

Thanks!

**Comment by dylanaraps** [comment]
You can use `reset` to reset the colorscheme to your terminal's default.

**Comment by Dinduks** [comment]
Hi @jerpint. Got the same problem as you, diffs are unreadable.

What did you end up doing?
