### ISSUE TITLE
[enhancement request] Add a brightness option

### ISSUE THREAD

**Issue by malyutinegor** [dylanaraps/pywal#434]
It would be nice to have color schemes with more (or less) brightness.

**Comment by dylanaraps** [comment]
I recommend using wpgtk for this.

**Comment by atagen** [comment]
hey, is this considered totally undesirable in pywal itself? if not, I have a PR for a `--brightness` option ready to go, using the existing lighten/darken functions and similar syntax+caching to `--saturate`.
