### ISSUE TITLE
[i3-wm] Weechat restored colours after i3 reload

### ISSUE THREAD

**Issue by ae00** [dylanaraps/pywal#438]
When i press mod+shift+r to reload i3 it changes the weechat colours to the default ones. Not the colours generated with pywal.

**Comment by ae00** [comment]
it does get restored to the pywal colours after typing **wal -R** though

**Comment by 927589452** [comment]
suggestion for a fix might be to add a `exec wal -R` to your i3 config.

@dylanaraps I would guess Weechat reloads the colors on the fly (which is kinda nice!) but a i3 reload only sources the colors defined in the .Xresources

**Comment by ae00** [comment]
If i open a new window / terminal on the same workspace that the weechat window is on it will also restore to the default colours (not pywal colors).

**Comment by 927589452** [comment]
> If i open a new window / terminal on the same workspace that the weechat window is on it will also restore to the default colours (not pywal colors).

you can do a `xrdb -query` before and after reloading i3;
if the output changes, your system forgets the `wal` colors, whenever you reload i3

**Comment by dylanaraps** [comment]
Closing as there is nothing I can do here.
