### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by sphaugh** [dylanaraps/pywal#44]
Hello, I added a package for pywal to the AUR: https://aur.archlinux.org/packages/python-pywal/

You could add it to the README. Let me know if there's anything I should add or change. I can include you as a co-maintainer if you like.

**Comment by dylanaraps** [comment]
LGTM :+1:

We should write a wiki page and move the install instructions there. (Similar to what I've done for Neofetch https://github.com/dylanaraps/neofetch/wiki)

**Comment by dylanaraps** [comment]
Thanks for writing the wiki page. :)

**Comment by sphaugh** [comment]
Np! Sorry I kinda half assed it :p

**Comment by dylanaraps** [comment]
Can you add me as a co-maintainer? My username on the AUR is `dylan`. :)

**Comment by sphaugh** [comment]
Done!

On Jul 25, 2017 8:42 PM, "Dylan Araps" <notifications@github.com> wrote:

Can you add me as a co-maintainer? My username on the AUR is dylan. :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dylanaraps/pywal/issues/44#issuecomment-317921928>, or mute
the thread

**Comment by dylanaraps** [comment]
The `python-pywal` aur package should be renamed to `python-pywal-git` as it grabs the latest master. We should then create a second package called `python-pywal` which tracks the latest release.

Here's the PKGBUILD for `python-pywal`:

```sh
# Maintainer: Sean Haugh <seanphaugh@gmail.com>
pkgname=python-pywal
pkgver=0.5.7
pkgrel=2
pkgdesc="Generate and change colorschemes on the fly"
arch=('any')
url="https://github.com/dylanaraps/pywal/"
license=('MIT')
depends=(
  'python'
  'imagemagick'
)
optdepends=(
  'feh: set wallpaper'
  'nitrogen: set wallpaper'
)
provides=("python-pywal=${pkgver}-${pkgrel}")
source=("https://github.com/dylanaraps/${pkgname#python-}/archive/${pkgver}.tar.gz")
md5sums=('a2231b4f54595db4fa028f7fbccec987')

package() {
  cd "${srcdir}/${pkgname#python-}-${pkgver}"
  python setup.py install --prefix=/usr --root="${pkgdir}/" --optimize=1
  install -Dm644 "${srcdir}/${pkgname#python-}-${pkgver}/LICENSE.md" \
                 "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}

# vim:set ts=2 sw=2 et:
```

**Comment by sphaugh** [comment]
Fixed, and I've added you as co-maintainer to the other as well.

**Comment by dylanaraps** [comment]
Thanks!

**Comment by sphaugh** [comment]
Hey just a small nit on your update, `pkgrel` should be reset to 1 for distributions of a new release. You can read more here: https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel

**Comment by dylanaraps** [comment]
Fixed, thanks!
