### ISSUE TITLE
Is it possible to output only color palette?

### ISSUE THREAD

**Issue by ashrasmun** [dylanaraps/pywal#444]
Hello,

When I execute wal with proper arguments, I get such output:

`wal -i futuristic_industry.jpg`
![wal_full_output](https://user-images.githubusercontent.com/12000269/63647579-c090ab00-c723-11e9-9f7c-192d708bc092.png)

When I use the quiet option, I get this output:

`wal -q -i futuristic_industry.jpg`
![wal_quiet_output](https://user-images.githubusercontent.com/12000269/63647594-ec139580-c723-11e9-91f1-33cbfbddb2e2.png)

Is it possible to get colors only in the output?

`wal ? -i futuristic_industry.jpg`
![wal_colors_only](https://user-images.githubusercontent.com/12000269/63647603-0cdbeb00-c724-11e9-8597-c1078582160d.png)

I tried greping out lines with square brackets, but that removes colors too.

Thanks in advance :)

**Comment by dylanaraps** [comment]
You can use `wal --preview` to display the current palette.

**Comment by ashrasmun** [comment]
Looks like I wasn't using the newest version of pywal - 3.1.0. I upgraded to 3.3.0 and everything works fine now. Thank you! :)
