### ISSUE TITLE
st does not change background when compiled with transperancy

### ISSUE THREAD

**Issue by cemkeylan** [dylanaraps/pywal#447]
When compiled with the default pywal template for st, it changes background with the colorscheme as it should. When the template is changed as adviced in the [third note of st customization](https://github.com/dylanaraps/pywal/wiki/Customization#st), it only shows the background of the color-scheme in use during the initial compile.

Left terminal is pre-compile, and the right terminal is post-compile

![first color-scheme](https://user-images.githubusercontent.com/32103268/64067048-521f8180-cc2a-11e9-9269-90389ddbe946.jpg)

The image above is before I change my color-scheme.

![second color-scheme](https://user-images.githubusercontent.com/32103268/64067057-767b5e00-cc2a-11e9-9f5d-1991213d7534.jpg)

This one is after I change my color-scheme, you can notice that the background for the pre-compiled st is changed but the post-compiled is remaining the same.

**Comment by ashrasmun** [comment]
This is most likely related to #445 and #446 as similar issues are presented there.

**Comment by dylanaraps** [comment]
There is nothing I can do about this.
