### ISSUE TITLE
Incorrect colours in exported vim scheme

### ISSUE THREAD

**Issue by maxigaz** [dylanaraps/pywal#449]
Following the advice given [here](https://github.com/dylanaraps/wal.vim/issues/15#issuecomment-485408548), I copied `~/.cache/wal/colors-wal.vim` to `~/.config/nvim/colors`.

If I add `colorscheme colors-wal` to `init.vim`, most colours don’t seem to be correct. (I get the same results if I deliberately set a scheme name that doesn't exist.)

![vim-walexport_20190907_121817](https://user-images.githubusercontent.com/10419911/64474119-32c7ad80-d170-11e9-8da7-fac7543e2e3f.png)

However, if I change the scheme with `colorscheme wal` (with wal.vim installed), I get the correct colours.

![vim_wal_20190907_122044](https://user-images.githubusercontent.com/10419911/64474121-4115c980-d170-11e9-8297-3f4349cf72fb.png)

By the way, I ran wal 3.3.0 on [this](https://upload.disroot.org/r/zI5ojyhE#pOEbyNnOYUbxeydUB5m8Wd2E0DkHHjq3J1dU7cHCH3E=) wallpaper with `wal -i 23.jpg`.

I also uploaded the contents of the generated .vim file [here](https://bin.disroot.org/?51f678f602af0747#JhyCjMg477SLZXqt1zhEwD1RsMUdJ7zGYUx9l9sIBi0=).

**Comment by dylanaraps** [comment]
`colors-wal.vim` is not a `vim` color-scheme but a `vimscript` which defines variables for each of the colors for use in scripting. `wal.vim` **is**  a color-scheme.
