### ISSUE TITLE
CCMAKE cursor invisible. Ubuntu 18.04

### ISSUE THREAD

**Issue by DBunce1027** [dylanaraps/pywal#462]
I use ccmake to toggle cmake options for my company's software. With pywal the cursor is invisible and I cannot tell which line I am editing easily without the aid of the text description for each option at the bottom.

**Comment by dylanaraps** [comment]
I don't know if this is a `pywal` bug or a `ccmake` bug as `pywal` sets the cursor color to `color15` (typically white). Will do some digging in the `ccmake` source.

**Comment by dylanaraps** [comment]
May I also ask which terminal emulator you are using?

**Comment by dylanaraps** [comment]
![](https://visp-doc.inria.fr/doxygen/visp-2.10.0/img-ccmake-ubuntu.png)

Ah. The issue is that the cursor is set to white when it should be a different color?

**Comment by dylanaraps** [comment]
This seems like the same or similar: https://stackoverflow.com/questions/50720474/how-can-i-change-the-appearance-of-the-cursor-in-terminal-only-for-a-certain-app

**Comment by dylanaraps** [comment]
This also seems like the same issue: https://cmake.org/Bug/view.php?id=4025

**Comment by dylanaraps** [comment]
Does running this before `ccmake` retain the changed cursor color?

```sh
# Should make cursor RED.
printf '\033]12;%s\033\\' "ff0000"
ccmake
```

**Comment by DBunce1027** [comment]
It did not retain the changed cursor color. I am using terminator with zsh and oh-my-zsh for shell

**Comment by DBunce1027** [comment]
![Screenshot from 2019-11-04 12-36-50](https://user-images.githubusercontent.com/14945665/68147615-088c3500-ff00-11e9-8ae5-9e142b18f666.png)

**Comment by DBunce1027** [comment]
This color scheme was built using wal on the default background of ubuntu 18.04, the bionic beaver
![warty-final-ubuntu](https://user-images.githubusercontent.com/14945665/68147650-1e015f00-ff00-11e9-99fc-aadf63324d1d.png)

**Comment by dylanaraps** [comment]
I don't think there's anything I can do on my end to fix this. It is worth opening an issue upstream to hear their thoughts on the issue. For now, `reset; ccmake` is most likely the only and simplest workaround.

**Comment by DBunce1027** [comment]
reset doesn't undo all the changes it seems so reset is not sufficient.

**Comment by dylanaraps** [comment]
There is nothing I can do about this.
