### ISSUE TITLE
Getting HEX code and number printed each start the terminal

### ISSUE THREAD

**Issue by DaekTwentri** [dylanaraps/pywal#463]
![Numbers](https://user-images.githubusercontent.com/29705559/68409518-931da000-015d-11ea-883e-2d9fb601ebad.png)

So this isn't really a massive issue but it's pretty annoying and unpleasant to look at. I've set my xinitrc to run wal -R each time and it almost always pops this weird garble behind the username and hostname. using the -q argument doesn't get rid of it either. 

How do you be rid of it so that each time I start the terminal I don't have to see it but instead see my cute new terminal?

**Comment by dylanaraps** [comment]
Use the `--vte` flag with all `wal` commands.
