### ISSUE TITLE
Ubuntu 18.04 Cant change wallpaper size

### ISSUE THREAD

**Issue by DBunce1027** [dylanaraps/pywal#466]
When pywal loads the wallpaper based on an image, the image is stretched. But Tweaks cant seem to adjust the wallpaper settings. Setting it to "zoom" or "centered" doesn't change the image at all despite having an image that is the same resolution as my screen. # #

**Comment by dylanaraps** [comment]
You can tell pywal to disable setting the wallpaper and then use `-o /path/to/script` to launch the wallpaper setter of your choosing.
