### ISSUE TITLE
rofi error

### ISSUE THREAD

**Issue by 404cn** [dylanaraps/pywal#469]
**wal 3.3.0**

**rofi  Version: 1.5.4**

**Arch Linux, i3wm**

**config.rasi**

```theme: "~/.cache/wal/colors-rofi-dark.rasi";```

And my templates file is default file from repo.

**Error while parsing theme:** _~/.config/rofi/config.rasi_
Parser error: __syntax error, unexpected invalied element theme, "bracket open ('{')" or "Selector separator (',')"
Location: Line 1 Column 6 to Line 1 Column 7
File: '~/.config/rofi/config.rasi'

**Comment by Vinhocent** [comment]
solution to this is instead of adding 
`theme: "~/.cache/wal/colors-rofi-dark.rasi";`

add this instead:

`@import "/home/kaiten/.cache/wal/colors-rofi-dark.rasi"`

**Comment by leo1994** [comment]
@dylanaraps can change on wiki ?

**Comment by dylanaraps** [comment]
The Wiki should be open to everyone, no need to wait for me.

**Comment by Abraxas-Knister** [comment]
adding `@import "~/.cache/wal/colors-rofi-dark.rasi"`

doesn't work for me, invoking rofi via `rofi -modi drun,run -show drun` results in 
{{{
Parser error: "syntax error, unexpected invalid property name, expecting "bracket close ('}')"
}}}

**Comment by EricPezzulo** [comment]
I have the same issue

**Comment by diegoOG09** [comment]
Yep, same issue here.
Error while parsing theme: "bracket close('}')

**Comment by waa** [comment]
I have the same issue after upgrading my Arch system last night.

syntax error, unexpected invalid property error, expecting "bracket close('}')

**Comment by waa** [comment]
Hmmm, Fixed using this 'new' format as shown on the archwiki rofi page: https://wiki.archlinux.org/title/Rofi

configuration {
 modi: "window,drun,ssh,combi";
 font: "hack 10";
 combi-modi: "window,drun,ssh";
 }
@theme "solarized"

**Comment by EricPezzulo** [comment]
That worked for me, I got the slate theme back. weird.

**Comment by AdrianeTroyRoa** [comment]
Instead of **@theme** "solarized", it should be **@theme** "~/.cache/wal/colors-rofi-dark.rasi" if you want the pywal theme.

**Comment by MykolaVaskevych** [comment]
>  it should be ```@theme "~/.cache/wal/colors-rofi-dark.rasi" ```

I tried, ```syntax error, unexpected invalid element name, expecting Element name```

**Comment by AdrianeTroyRoa** [comment]
> > it should be `@theme "~/.cache/wal/colors-rofi-dark.rasi" `
> 
> I tried, `syntax error, unexpected invalid element name, expecting Element name`

Please try to see if the path I added as value of @theme exists. I'm a beginner as well. I tried this one out and it worked so decided to share it here.
