### ISSUE TITLE
pywal not finding i3 pid to reload i3

### ISSUE THREAD

**Issue by ktsuttlemyre** [dylanaraps/pywal#472]
I am running raspbian lite with minimal installs. I have to manually reload i3 because the line in `reload.py` @ 47 returns false from `util.get_pid('i3')` Here is a sample of my htop filtered by `i3` string

![2019-11-30-180451_1920x1080_scrot](https://user-images.githubusercontent.com/1229777/69904483-cb03b600-139e-11ea-8d2e-af041e53dcaa.png)

**Comment by dylanaraps** [comment]
Where's the `i3` process? I can see a bunch of `i3` related utilities but the window manager itself seems to be missing.

**Comment by ktsuttlemyre** [comment]
Yeah, i3 must have been in a really weird state. Rebooting caused the whole WM to break. Reformatted and started over. You can close this out. Sorry for the inconvenience.
