### ISSUE TITLE
Possible to modify (Neo)vim theme to support termguicolors?

### ISSUE THREAD

**Issue by khughitt** [dylanaraps/pywal#475]
Greetings!

Is there any possibility that the vim theme could be modified so that `set termguicolors` could be used?

It is required by many themes for truecolor support, so removing it ends up breaking other themes that one may switch to using something like [vim-colorscheme-switcher](https://github.com/xolox/vim-colorscheme-switcher).

**Comment by dylanaraps** [comment]
You will have to write your own theme or turn off `set termguicolors` when using `pywal`.
