### ISSUE TITLE
ST terminal support 

### ISSUE THREAD

**Issue by SeungheonOh** [dylanaraps/pywal#478]
Not sure if its fixed by any other methods, if not, here's a way:
So ST does support full Xterm system control codes; it only has internal command for color changes. The background is linked to the color index 256; The foreground is linked to the color index 257.

Therefore...
```
\033]4;256;#(COLOR)\007 <= for background
\033]4;257;#(COLOR)\007 <= for foreground
``` 
should fix most of ST related problems, and it did fix all problems with ST for me + There was no conflict between other terminal emulators. Maybe you can just hop this part on ```sequence.py```

**Comment by dylanaraps** [comment]
Seems to be the other way around (?).

**Comment by SeungheonOh** [comment]
Oh, that makes sence. Last time I tried it the background and foreground was swaped

**Comment by SeungheonOh** [comment]
How about adding some note about ST color since its configure able and can be changed based on each configuration? 

ST bg and fg color can be configured in its config.h file by changing variable named defaultfg and defaultfg
