### ISSUE TITLE
pywal/bash/ls_colors problems

### ISSUE THREAD

**Issue by hedich** [dylanaraps/pywal#486]
is the colors.sh actually working? i saw that there is a line like this:

```
# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
```
is it supposed do set different colors? 

i am using `(cat ~/.cache/wal/sequences &)` in my .bashrc file and that is working
to set colors but my ls colors are still only one color, i am a bit new to ls colors and are trying to figure out what is going on. (is pywal even supposed to set more then one color for ls?)

took a look at nord dir colors and they are using a file (.dir_colors) and then
`test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)` 
would it not be more simple for pywal to do this as well?

i am a bit new to linux so i am probably missing something obvious here

**Comment by dylanaraps** [comment]
You need to ad `. /path/to/colors.sh` to your shellrc.
