### ISSUE TITLE
Colorscheme doesn't work if I open a terminal from .sh

### ISSUE THREAD

**Issue by DennisDv24** [dylanaraps/pywal#490]
I am using xfce4-terminal. If from the script I execute a normal command (like ls) it works fine. But if I run from my .sh a terminal that runs another .sh the colorscheme does not apply to the terminal that will be opened by that .sh. For example, if I run from my .sh script this:
```
xfce4-terminal -e pacman -Syu
```
the colors apply, but with: 
```
xfce4-terminal -e pipes.sh
```
they don't

**Comment by dylanaraps** [comment]
Nothing I can do about this. :woman_shrugging:
