### ISSUE TITLE
Shebang interpreter should point to python3

### ISSUE THREAD

**Issue by danielx** [dylanaraps/pywal#5]
Since **pywal** is only compatible with python>=3.6 the script should be instructed to run using `python3` instead of `python`. 

See [PEP 394](https://www.python.org/dev/peps/pep-0394/)

> # Abstract
> This PEP provides a convention to ensure that Python scripts can continue to be portable across *nix systems, regardless of the default version of the Python interpreter (i.e. the version invoked by the `python` command).
> * `python2` will refer to some version of Python 2.x.
> * `python3` will refer to some version of Python 3.x.
> * for the time being, all distributions should ensure that `python` refers to the same target as `python2`.
> * however, end users should be aware that `python` refers to `python3` on at least Arch Linux (that change is what prompted the creation of this PEP), so `python` should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3.
> * in preparation for an eventual change in the default version of Python, Python 2 only scripts should either be updated to be source compatible with Python 3 or else to use `python2` in the shebang line.

**Comment by dylanaraps** [comment]
Thanks for opening this issue!
