### ISSUE TITLE
Terminology not supported?

### ISSUE THREAD

**Issue by SaintFenix** [dylanaraps/pywal#50]
Attempted to use it in Terminology: https://www.enlightenment.org/about-terminology

and didn't have any luck with the test string to turn the terminal background red.

Just wanted to give a heads up. Apologies if this is in the wrong place, I'm very very new to Github.

**Comment by dylanaraps** [comment]
I did some testing and it looks like it doesn't support the escape sequences needed to change the colors. I'll add it to the list in the README.

**Comment by thierrybo** [comment]
I just tested the test string with terminology 1.8.1 on Debian testing and it works :+1: 
[https://youtu.be/vVfa3MaPn9M](https://youtu.be/vVfa3MaPn9M)
