### ISSUE TITLE
question: how to "change" colors on conky?

### ISSUE THREAD

**Issue by icf20** [dylanaraps/pywal#51]
hello, is there anyway to use the colours generated by wal in conky ?

**Comment by dylanaraps** [comment]
I've never used conky before, this gives me an excuse to try it. :)

We should be able to reload the config with the following command: `killall -SIGUSR1 conky` The tricky part now is figuring out how to change the colors.

**Comment by icf20** [comment]
well conky restarts and reload the conyrc file after a change 

just start conky like this `conky -c bla/bla/conkyrc`

part of my conky 

```
#########################
# - Graphics settings - #
#########################
draw_shades no

default_color D6D6D6

color0 ${xrdb:color0}
color1 ${xrdb:color1}
color2 ${xrdb:color7}
color3 ${xrdb:color8}
```

**Comment by icf20** [comment]
closed because is not longer pywal issues is conky issue
