### ISSUE TITLE
Keep getting this error when trying to run wal -i "path/to/image/.jpg"

### ISSUE THREAD

**Issue by co1ncidence** [dylanaraps/pywal#511]
I have installed pywal and made sure i have all the dependencies, but whenever i try to run the wal -i command and generate a colorscheme i keep getting this error message:

subprocess.CalledProcessError: Command '['magick', 'convert', '/home/co1ncidence/Pictures/Sweet-space.png[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.

(co1ncidence is my username btw)

I have tried searching for a solution but cannot find one, i am new to linux so any help would be greatly appreciated.

**Comment by Bappamaiti** [comment]
Hello
Is this issue solved?

I am facing the same kind of issue.

I'm on windows 10 64bit.
![image](https://user-images.githubusercontent.com/81735229/114697948-22a88480-9d3c-11eb-912c-8d23cbbe8833.png)

Unable to generate colors.json file

**Comment by co1ncidence** [comment]
build imagemagick from source it fixes the problem.

also dont use pywal bro it is cringe.

**Comment by Bappamaiti** [comment]
Hi bro thanks for your response.
actually i was trying to use pywalfox addon on thunderbird , if i do not use pywal, then is there any way to use it for thunderbird??

**Comment by co1ncidence** [comment]
Pywalfox themes look like ass wherever you use them. I recommend using an actual curated thunderbird theme instead. Otherwise your email client will become basically unusable.
