### ISSUE TITLE
Problems with some terminals

### ISSUE THREAD

**Issue by e3172** [dylanaraps/pywal#513]
With kitty and termite the colours are removed after a new window was opened:
Here is what it looks like with kitty terminal:
![2020-04-18-095928_1920x1080_scrot](https://user-images.githubusercontent.com/63252513/79633324-397dc080-8154-11ea-8254-2933ed00f034.png)

**Comment by dylanaraps** [comment]
Yes. You need to add a specific line to your shellrc file. See the installation/setup instructions.
