### ISSUE TITLE
wal breaks Dock and Mission Control on MacOS

### ISSUE THREAD

**Issue by dawsoneliasen** [dylanaraps/pywal#514]
On MacOS Catalina 10.15, and iTerm2 I did `wal -i`. The colors in iTerm2 changed. Then Dock/Mission Control stopped working. I noticed that there was a problem when my keyboard shortcut to switch desktops stopped working and just sent the key codes to the terminal. 

It wasn't obvious that wal had caused the problem, so I googled "restart Mission Control." Results instructed me to do a `killall Dock`, but the response was that there were no active Dock processes. I searched in the Activity Monitor for "Dock", nothing came up. Restarted my MacBook a couple times, no change. 

I was able to restore Dock and Mission Control using the accepted answer from [this](https://apple.stackexchange.com/questions/334077/revert-killall-kill-dock) thread. It seems that wal might be creating some sort of corrupted wallpaper file?

**Comment by AWOLASAP** [comment]
HOLY HECK, I had this same issue. I have been testing things with backups and such, so I will have to try that link as soon as possible. Did you have SIP enabled or disabled?

**Comment by dawsoneliasen** [comment]
I'm not exactly sure, is there a way to check? It seems like the sort of thing I may have disabled at one point, but I can't remember.

**Comment by robwaz** [comment]
SIP does not need to be disable for Pywal to work.  In general, SIP should not be disabled without a very good reason.  Please use #515 to discuss this issue and I will try to resolve it.

**Comment by dawsoneliasen** [comment]
Okay, I'll close this issue and paste my info there.
