### ISSUE TITLE
[SchemeUrg] =  { urg_fg,      urg_bg,    urg_border },

### ISSUE THREAD

**Issue by plasmoduck** [dylanaraps/pywal#516]
How to stop pywal adding line:
[SchemeUrg] =  { urg_fg,      urg_bg,    urg_border },
to ~/.cache/wal/colors-wal-dwm.h
So I don't have to manually remove it each time I change theme and compile dwm?

**Comment by dylanaraps** [comment]
Check the template file it is being generated from. Pywal won't just randomly add lines of information to templates. :+1:

**Comment by plasmoduck** [comment]
WHich template file sorry?

**Comment by plasmoduck** [comment]
The /location/to/file please?
