### ISSUE TITLE
Changing Konsole color scheme opacity prevents "Colorscheme generetad by wal" from updating

### ISSUE THREAD

**Issue by BurnedPixel** [dylanaraps/pywal#520]
When linking the wal color scheme with Konsole it works as intended, the color pallet updates when you reboot the terminal.
If you change the opacity value it breaks the chain and the color scheme stops updating when you update colors with wal.
I've been copying the wal generated colors, and changing the opacity on the newly created file to prevent the "Colorscheme generated by wal" from updating.

**Comment by dylanaraps** [comment]
I don't think there's anything I can do to fix this. Remember, pywal is a kinda hack which actually works well in most scenarios. Some terminals just do not play well with it however. Thanks for opening this issue.
