### ISSUE TITLE
wal: error: unrecognized arguments: -g

### ISSUE THREAD

**Issue by erdemgazeloglu** [dylanaraps/pywal#521]
when I enter this command wal -i ~ / Pictures / natalia-bielawska-by-natalia-bielawska-synth-retrowave-synth.jpg -g it returns wal: error: unrecognized arguments: -g

**Comment by dylanaraps** [comment]
Yeah. `-g` isn't an argument.

**Comment by erdemgazeloglu** [comment]
but it worked on this site : https://linuxconfig.org/how-to-customize-your-gtk-desktop-with-oomox-and-pywal

**Comment by katacarbix** [comment]
@erdemgazeloglu That guide was for an older version of wal (See  #374).
