### ISSUE TITLE
'Skip changing colors in terminals' not working

### ISSUE THREAD

**Issue by shahzebs** [dylanaraps/pywal#526]
I like the color scheme generation feature of this project, which is why I would like to use it for just that. I found that the options `-n` and `-s` skip setting the wallpaper and terminal colors, respectively. Although `-n` does work as intended, `-s` does not seem to work for me. 

I am using st as my terminal emulator and have defined my preferred terminal colors in my .Xresources file.

Whenever I run `wal -s -i path/to/image` the color scheme gets generated. Launching a new terminal window client reveals that the colors have been changed.  

Any help resolving this issue would be appreciated.

**Comment by shahzebs** [comment]
I seems I have misunderstood the `-s` option. It only skips setting the terminal colors when generating a new color scheme. However, I guess it is supposed to change the colors for any new terminal window? 

Is there a way to only generate a color scheme without ever applying it?

**Comment by iofq** [comment]
wal -ste is working for me
