### ISSUE TITLE
Reset Colours

### ISSUE THREAD

**Issue by sabrehagen** [dylanaraps/pywal#549]
How do I reset my terminal colours to the default colours i.e. before wal applied a theme. So far I've tried the following to no avail:

`reset`
`stty sane`
`tput init`
`tput reset`

**Comment by robwaz** [comment]
Assuming you persisted the colors using the process shown [here](https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals), I would remove the relevant line from your relevant rc file.

**Comment by sabrehagen** [comment]
Incorrect assumption; after running running `wal -R` how can I restore the system default colours to a terminal without restarting the terminal?
