### ISSUE TITLE
Supress pywal output when opening a terminal

### ISSUE THREAD

**Issue by sunnyhasija** [dylanaraps/pywal#553]
Right now whenever I open a new terminal, I get a litany of things that pywal did and a swatch of the color palette. Is there a way to suppress that so that when the terminal starts there is no output in the terminal window?

**Comment by dylanaraps** [comment]
Add `>/dev/null 2>&1` to the command or just pass `-q` to `wal`.

**Comment by xpat** [comment]
```wal -R >/dev/null 2>$1``` in ```~/.bashrc``` suppresses the output on new tabs as well.  It would be nice if the  information lines [I] could be suppressed (and optionally the warnings [W}) but not the swatch of the color palette.
