### ISSUE TITLE
 [Feature Request] Reload: anything and everything

### ISSUE THREAD

**Issue by sesar54** [dylanaraps/pywal#556]
I have a build of dwm which can reload from .Xresources. Now I just need to trigger it from wal. It's a custom build with an unusual method of communicating with the main process.
My suggest would be to run any reload scripts found in ~/.config/wal/reloa.d/?*.sh, which would help me detect when wal is running and it would help any other peoples update their custom systems and programs.

**Comment by sesar54** [comment]
A naive solution would look like this: 
```python
import glob, os

def anything():
    for file in glob.glob("~/.config/wal/reloa.d/?*.sh"):
        if os.access(file, os.X_OK):
            os.system("/bin/sh '" + file + "'")

anything()
```

**Comment by dylanaraps** [comment]
This can already be done via scripting. Simply create a wrapper that calls `wal` and do everything extra in the wrapper. Closing this issue. Thanks for opening it.
