### ISSUE TITLE
wal colors dont transfer over to new terminals

### ISSUE THREAD

**Issue by darkralts** [dylanaraps/pywal#562]
![image](https://user-images.githubusercontent.com/16366107/98535996-08cab900-2255-11eb-8cc0-9437221f475f.png)

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals

**Comment by darkralts** [comment]
thanks :D
