### ISSUE TITLE
background color and transparency error of polybar

### ISSUE THREAD

**Issue by Tarch1** [dylanaraps/pywal#573]
HI,
I've a problem whit the transparency of polybar, when bspwm start whit this config:

#! /bin/sh
sxhkd &
chmod a+w /sys/class/backlight/intel_backlight/brightness &
setxkbmap -layout it &
numlockx &
xsetroot -cursor_name left_ptr &
#feh --bg-fill --randomize ~/.wallpapers/* &
xautolock -time 5 -locker "gllock" &
./.config/low-battery.sh -n &
wal -i ~/.wallpapers/ &
./.config/polybar/launch.sh &
picom --experimental-backends &
bspc monitor -d I II III IV V

and the polybar relative color

[colors]
background = ${env:color0_alpha}
;background = ${xrdb:color1:#222}
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color3:#222}
alert = ${xrdb:color5:#222}

polybar keep the background black color and I've found this error in /tmp/polybar1.log

polybar|error: Invalid value for "bar/bar1.background", using default value (reason: Environment var ${color0_alpha} does not exist (no fallback set))

but after polybar start if I launch polybar whit this ./.config/polybar/launch.sh in a terminal the transparency and colors is working, but the updated /tmp/polybar1.log still report the same issue, even if color and transparency are correctly setted.
I don't know if this is the right place to post but for now i try here :)

**Comment by Tarch1** [comment]
solved by following this https://github.com/dylanaraps/pywal/issues/132 but instead of putting source and export command in .bashrc put them to polybar launch script

**Comment by Tarch1** [comment]
now another proble is the bspwm config if you use random wallpaper, that use the previous color set  instead of the new generated

**Comment by KiranWells** [comment]
This can be fixed by telling Pywal to delete the color cache before re-applying the color scheme. Pywal automatically caches colors for each file, and if the file name does not change, the colors will not change.
```sh
# clears the cache
wal -c
# resets colors
wal -i /path/to/random/image
```
I had to do this for my setup since I have a script that loads a random photo from Unsplash. I just built a small `run` file that will clear the cache and restart Pywal with my settings.

**Comment by Tarch1** [comment]
thank you!
