### ISSUE TITLE
pywal is working in st terminal

### ISSUE THREAD

**Issue by lapwat** [dylanaraps/pywal#577]
In `st` terminal,

`printf "%b" "\033]11;#ff0000\007"` may not work but pywal does work.

If I run:

```sh
xrdb -remove *
printf "%b" "\033]11;#ff0000\007"
```

The terminal background does NOT turn red.

Nevertheless, running:

```sh
wal -i /path/to/image.jpg
```

Does change my terminal theme as expected.

Should we remove that `pywal` does not work with `st` from the _README_?

**Comment by UmarJ** [comment]
Can confirm

**Comment by veilm** [comment]
Right now, st and other terminals aren't mentioned in the README. If you mean the Installation wiki page - anyone can edit that, right?

**Comment by iritmaximus** [comment]
There are still problems. For example my st loses the new pywal colors after focus is lost. After some research I'm quite certain that the problem is in the exit codes that pywal uses which st doesn't support.

**Comment by justNeto** [comment]
> There are still problems. For example my st loses the new pywal colors after focus is lost. After some research I'm quite certain that the problem is in the exit codes that pywal uses which st doesn't support.

Excuse me, did you manage to find a workaround for this?

**Comment by sashs** [comment]
Pywal works for me, even when the focus is lost. However, it sets the background to a light color instead of a dark color if I try to create a dark scheme. If I create a light color scheme is the opposite (dark background color)

Since I am tmux by default when I start st, it does not matter to me, because there is the right background color.

**Comment by JKP1008shine** [comment]
> There are still problems. For example my st loses the new pywal colors after focus is lost. After some research I'm quite certain that the problem is in the exit codes that pywal uses which st doesn't support.

Did you guys resolve the issue? Please the share the solution.
