### ISSUE TITLE
Add option to stop wal from setting the terminal background colour.

### ISSUE THREAD

**Issue by TNTINC** [dylanaraps/pywal#59]
Just a configurability thing I found myself wanting when wal generated a bit too darky bluey of a background.

Would also be nice if you could pass in/configure a hex value to use for the background :)

**Comment by dylanaraps** [comment]
This is already a feature, `wal -n`. 

I'll look into the other option.  :)

**Comment by TNTINC** [comment]
> This is already a feature, `wal -n`.
That stops it changing the desktop background image, but still sets the terminal emulator background color. 
Apologies if my wording was a bit ambigous there.

The other option would however be brilliant interpreted either way.

**Comment by dylanaraps** [comment]
Oh, my bad!

(I shouldn't reply to issues before I've had a coffee)

**Comment by TNTINC** [comment]
(as explanation for that short spurt of closed-ness, I have a mildly dysfunctional trackpad and I'm very sorry)

**Comment by dylanaraps** [comment]
I've just pushed this to master, you can use `-b "#000000"` to use a custom background color on launch. This will also be saved into the cached scheme by `wal`.

**Comment by TNTINC** [comment]
Works like a charm, and in record time to boot. 
Kudos!
