### ISSUE TITLE
Flatabulous-wal GTK theme not working

### ISSUE THREAD

**Issue by mananapr** [dylanaraps/pywal#61]
I couldn't find the option to open an issue on the Flatabulous-wal repo so I opened an issue here. Hope that's fine.

Here is a screenshot of my directory structure and lxappearnace:

![wal](https://user-images.githubusercontent.com/22202164/28705348-026347a0-738d-11e7-858d-75855317e120.png)

What could be wrong here?

**Comment by dylanaraps** [comment]
Run `lxappearence > wal-log`, set the theme in LXAppearence and paste the contents of that file here. That should tell me what's going on.

**Comment by mananapr** [comment]
[wal-log.txt](https://github.com/dylanaraps/pywal/files/1182207/wal-log.txt)

**Comment by dylanaraps** [comment]
Have you run `wal` since installing the theme? 

LXAppearence is saying that it can't find the `wal` export file.

**Comment by mananapr** [comment]
I got it to work.
I just hadn't updated pywal. Can't believe I made this mistake.
Sorry

**Comment by dylanaraps** [comment]
All good, I'll add a note to the wiki about this. :)
