### ISSUE TITLE
 Where to find current background file path used by pywal?

### ISSUE THREAD

**Issue by iamtalhaasghar** [dylanaraps/pywal#636]
I don't see any command line argument to fetch the current background file path used by `pywal`.
It would be very helpful in certain scenarios to have this option and then one can play around with it in his/her shell scripts.

Of course we can query desktop environment for this purpose but we don't have this facility for window managers like i3wm.

**Comment by alt-romes** [comment]
The background file path used is in "~/.cache/wal/wal", instead of a command line argument you could run something like `cat ~/.cache/wal/wal`
