### ISSUE TITLE
Dual monitor issue

### ISSUE THREAD

**Issue by yungdan1** [dylanaraps/pywal#65]
I am using one 1920x1080 monitor as my primary monitor, and a 1280x1024 monitor as my secondary monitor. Whenever I reboot, the wallpaper switches monitor, meaning the wallpaper scaled for 1280x1024 ends up on the 1920x1080 monitor, and wallpaper scaled for 1920x1080 ends up on the 1280x1024 monitor. Running wal -i fixes the issue, but this means that I need to run pywal every time.

**Comment by dylanaraps** [comment]
Can you send me your config files? (All I need are the `wal ...` parts of them.)

I've got a second monitor so I'll try and see if I can reproduce this with the snippets from your configs.

**Comment by yungdan1** [comment]
So I think I realized what the issue is. I'm using xrandr in my i3 config file to set up my monitors.
`exec --no-startup-id xrandr --output DVI-1 --mode 1280x1024 --output HDMI-0 --mode 1920x1080 --right-of DVI-1`

What I am guessing is happening is that xrandr executes after pywal, which results in my issue. My question now is how do I bypass this issue?

**Comment by dylanaraps** [comment]
You could execute pywal after xrandr in your i3 config, there's no way for me to fix this on my end.

Edit: Another solution is something like this:

```
# -n Makes 'wal' skip setting the wallpaper.
wal -i "$(< "${HOME}/.cache/wal/wal")" -o wal-set -n

# Setup multi-mon.
xrandr --output DVI-1 --mode 1280x1024 --output HDMI-0 --mode 1920x1080 --right-of DVI-1

# Call 'feh' to set the wallpaper.
feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"
```

I'm closing this as it isn't a `pywal` issue nor is it anything I can fix. I will document this inside the wiki somewhere though.
