### ISSUE TITLE
Doesn't work on Dmenu

### ISSUE THREAD

**Issue by hyperboly** [dylanaraps/pywal#658]
I tried to add in the #include /path/to/wal line in dmenu, but it doesn't work. If I try to delete the color definitions in my config.h in my dwm directory, it errors. This might be a patch issue. Is there a patch thats known for overriding pywal for dmenu? Pywal works for me on st and dwm.
Thanks.

**Comment by Damaj301damaj-lol** [comment]
You need to patch Xresources support for dmenu, dwm, st to enable use of pywal on them

**Comment by ghost** [comment]
@Damaj301damaj-lol untrue, however the patches make it more seamless (specifically the xresources-alt patch).

**Comment by Damaj301damaj-lol** [comment]
@speediegq it didn't work for me until i patched it ?

**Comment by ghost** [comment]
@Damaj301damaj-lol That's because you need to #include the generated colors and remove the existing colors.
Like I said, the xresources-alt patch is an alternative, and that's usually what i prefer.

**Comment by emman-penuliar** [comment]
You can check if your theme is working by running **dmenu_run** the terminal. If your theme is working you need to bind your **mod + p** to **dmenu_run** (without some fancy dmenu command) in your **config.h**. 

In your **config.h**, look for this line where the dmenucmd is defined:
`static const char *dmenucmd[] = { "dmenu_run", "-m", dmenumon, "-fn", dmenufont, "-nb", col_gray1, "-nf", col_gray3, "-sb", col_cyan, "-sf", col_gray4, NULL };` 

Then just remove the colors such as col_gray1 until you are left like this:
`static const char *dmenucmd[] = { "dmenu_run", NULL };`

You may also want to **delete/comment** out these lines:
`static const char col_gray1[]       = "#222222";`
`static const char col_gray2[]       = "#444444";`
`static const char col_gray3[]       = "#bbbbbb";`
`static const char col_gray4[]       = "#eeeeee";`
`static const char col_cyan[]        = "#005577";`

**Comment by ghost** [comment]
Do not delete the colors, as they're used in the colors array.

I recommend applying the xresources patch to dmenu and adding the color0-color15 stuff to the Xresources array.
