### ISSUE TITLE
[Question] Multiple background colors

### ISSUE THREAD

**Issue by Passeriform** [dylanaraps/pywal#673]
Hi, does pywal support manual colorscheme tweaking?

I'm thinking of adding another **background** color to my colorscheme but afaik pywal doesn't support manually changing the colors (except changing the source). Would I be right in this assumption? And is there a better way(maybe another fork) to achieve two **background** colors.

**Comment by lofilobzik** [comment]
Check out [wpgtk](https://github.com/deviantfero/wpgtk)

**Comment by Passeriform** [comment]
That does it. Thanks!
