### ISSUE TITLE
VTE: Garbage / Junk / Characters printed to the terminal

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/pywal#69]
# Workaround: Add `-t` to all `wal` commands.

This issue is open to track the issue with VTE based terminals displaying junk when sent an unrecognized escape sequence (in our case `\033]708;#000000\007`). 

The issue has been open on VTE's bug tracker for just over 10 years now with no one willing to fix it.

- https://bugzilla.gnome.org/show_bug.cgi?id=403130

This VTE bug is responsible for the following `wal`/`pywal` issues:

- https://github.com/dylanaraps/pywal/issues/22
- https://github.com/dylanaraps/wal/issues/16
- https://github.com/dylanaraps/wal/issues/58
- https://github.com/dylanaraps/wal/issues/55
- https://github.com/dylanaraps/wal/issues/12

I've written a patch for VTE that works-around the issue by making VTE just ignore the sequence. I've tested the patch in multiple terminal emulators and it works just fine. Now I just need to figure out the right way to submit this upstream. (Any help is appreciated) 

I've based the patch on a pre-existing patch that does the identical to below but for another sequence. You can see the patch my patch was based on here: https://mail.gnome.org/archives/commits-list/2016-July/msg00635.html

The patch:

```diff
From f5e1ff373efc322adc6eddd5d5284b388ec29370 Mon Sep 17 00:00:00 2001
From: Dylan Araps <dylan.araps@gmail.com>
Date: Wed, 2 Aug 2017 15:31:01 +1000
Subject: [PATCH 1/1] emulation: Swallow ursvt OSC 708

Accept OSC 708 but make it a no-op.

This sequence is used in color changing programs and scripts to
change the terminal emulator's border color on the fly. Everytime
this sequence is used it clutters up the vte terminal since it
doesn't ignore unknown escape sequences (bug 403130).

https://bugzilla.gnome.org/show_bug.cgi?id=403130
---
 src/caps.cc        |  2 ++
 src/vteseq-n.gperf |  1 +
 src/vteseq.cc      | 10 ++++++++++
 3 files changed, 13 insertions(+)

diff --git a/src/caps.cc b/src/caps.cc
index 1f9cd1e..5d95114 100644
--- a/src/caps.cc
+++ b/src/caps.cc
@@ -256,6 +256,7 @@ const char _vte_xterm_capability_strings[] =
         ENTRY(OSC "118" BEL, "reset-tek-cursor-color")
         ENTRY(OSC "119" BEL, "reset-highlight-foreground-color")
         ENTRY(OSC "133;%s" BEL, "iterm2-133")
+        ENTRY(OSC "708;%s" BEL, "urxvt-708")
         ENTRY(OSC "777;%s" BEL, "urxvt-777")
         ENTRY(OSC "1337;%s" BEL, "iterm2-1337")
 
@@ -295,6 +296,7 @@ const char _vte_xterm_capability_strings[] =
         ENTRY(OSC "118" ST, "reset-tek-cursor-color")
         ENTRY(OSC "119" ST, "reset-highlight-foreground-color")
         ENTRY(OSC "133;%s" ST, "iterm2-133")
+        ENTRY(OSC "708;%s" ST, "urxvt-708")
         ENTRY(OSC "777;%s" ST, "urxvt-777")
         ENTRY(OSC "1337;%s" ST, "iterm2-1337")
 
diff --git a/src/vteseq-n.gperf b/src/vteseq-n.gperf
index eec89ae..6e0baf8 100644
--- a/src/vteseq-n.gperf
+++ b/src/vteseq-n.gperf
@@ -170,6 +170,7 @@ struct vteseq_n_struct {
 "set-current-directory-uri", VTE_SEQUENCE_HANDLER(vte_sequence_handler_set_current_directory_uri)
 "set-current-file-uri", VTE_SEQUENCE_HANDLER(vte_sequence_handler_set_current_file_uri)
 "set-current-hyperlink", VTE_SEQUENCE_HANDLER(vte_sequence_handler_set_current_hyperlink)
+"urxvt-708", VTE_SEQUENCE_HANDLER(vte_sequence_handler_urxvt_708)
 "urxvt-777", VTE_SEQUENCE_HANDLER(vte_sequence_handler_urxvt_777)
 "iterm2-133", VTE_SEQUENCE_HANDLER(vte_sequence_handler_iterm2_133)
 "iterm2-1337", VTE_SEQUENCE_HANDLER(vte_sequence_handler_iterm2_1337)
diff --git a/src/vteseq.cc b/src/vteseq.cc
index 1391e15..9700d1b 100644
--- a/src/vteseq.cc
+++ b/src/vteseq.cc
@@ -3499,6 +3499,16 @@ vte_sequence_handler_reset_highlight_foreground_color (VteTerminalPrivate *that,
 	that->reset_color(VTE_HIGHLIGHT_FG, VTE_COLOR_SOURCE_ESCAPE);
 }
 
+/* URXVT generic OSC 708 */
+
+static void
+vte_sequence_handler_urxvt_708(VteTerminalPrivate *that, GValueArray *params)
+{
+        /* Accept but ignore this for compatibility when using terminal color
+         * changing scripts.
+         */
+}
+
 /* URXVT generic OSC 777 */
 
 static void
-- 
2.13.3
```

**Comment by forbidden404** [comment]
I've been experiencing garbage numbers being shown in my iTerm 2.

Using -t isn't changing this effect and I'm using the latest version of pywal (0.6.4).
Is this related with this issue or should I file a new one?

<img width="603" alt="screen shot 2017-08-14 at 11 21 02 pm" src="https://user-images.githubusercontent.com/1664145/29299735-515c7300-8147-11e7-8aea-d3d0a86b7390.png">

**Comment by dylanaraps** [comment]
That’s a different issue, what she’ll are you using?

**Comment by dylanaraps** [comment]
@forbidden404, you need to wrap the command in `()` to hide the shell output. (*As is mentioned in the wiki*) So the correct command to use is `(wal -r &)`.

Note: When you're just in the terminal, you can ommit the other syntax and use plain `wal -r`. The `()` and `&` are needed to run `wal` asynchronously so that it doesn't delay the shell startup. The extra syntax is only meant for your `.bashrc` or `.zshrc` files.

**Comment by Metamist** [comment]
When running `wal -r` in urxvt or termite, I get lots of characters printed to my terminal without the colors being set.
```
metamist ~ (master*) $ wal -r -t
\033]10;#E0EAD5\007\033]11;[80]#02080A\007\033]12;#E0EAD5\007\033]13;#E0EAD5\007\033]14;[80]#02080A\007\033]708;[80]#02080A\007\033]4;0;#02080A\007\033]4;1;#418B4B\007\033]4;2;#658F6F\007\033]4;3;#8F986C\007\033]4;4;#76A086\007\033]4;5;#92B292\007\033]4;6;#ABCBA5\007\033]4;7;#E0EAD5\007\033]4;8;#666666\007\033]4;9;#418B4B\007\033]4;10;#658F6F\007\033]4;11;#8F986C\007\033]4;12;#76A086\007\033]4;13;#92B292\007\033]4;14;#ABCBA5\007\033]4;15;#E0EAD5\007%                                                                                                metamist ~ (master*) $ 
```
The only way to get the colors to be set in my terminal is to run `printf $(wal -r -t)`, but in termite that will still print out characters (although much less than before)
```
metamist ~ (master*) $ printf $(wal -r -t) 
]708;[80]#02080A%                                                                                            metamist ~ (master*) $ 
```
While doing this in urxvt does not print out anything.

The original wal did not require the `printf` in urxvt and it worked fine (but in termite, it still printed out characters).

**Comment by dylanaraps** [comment]
What version of `pywal` are you using? I can't reproduce this on `0.6.9`. Can you send me some steps to reproduce this?

**Comment by Metamist** [comment]
@dylanaraps I am also using 0.6.9. The wierd thing is that this does not happen for my brother, on his Termite, which is running almost identical software as me. The only difference is that he uses XMonad rather than i3

Any ideas what could be causing this?

**Comment by dylanaraps** [comment]
Can you send me the contents of the file located at `~/.cache/wal/sequences`? Also, what shell are you using? Does this occur in other shells?

**Comment by Metamist** [comment]
```
\033]10;#E0EAD5\007\033]11;[80]#02080A\007\033]12;#E0EAD5\007\033]13;#E0EAD5\007\033]14;[80]#02080A\007\033]708;[80]#02080A\007\033]4;0;#02080A\007\033]4;1;#418B4B\007\033]4;2;#658F6F\007\033]4;3;#8F986C\007\033]4;4;#76A086\007\033]4;5;#92B292\007\033]4;6;#ABCBA5\007\033]4;7;#E0EAD5\007\033]4;8;#666666\007\033]4;9;#418B4B\007\033]4;10;#658F6F\007\033]4;11;#8F986C\007\033]4;12;#76A086\007\033]4;13;#92B292\007\033]4;14;#ABCBA5\007\033]4;15;#E0EAD5\007
```

I am using Zsh. It also happens in bash.

**Comment by cj360** [comment]
I have simiar out here in bash as well. It's after logout/reboot when I see it the session I run wal -i ~/image -t won't have the garbage text till I reboot and open a new termite window.

Here's my wal/sequences almost seems like one of my fonts is causing broken characters http://ix.io/CKj.

**Comment by dylanaraps** [comment]
The issue has been fixed, `-t` is no longer needed. A new release will be pushed shortly.
