### ISSUE TITLE
generating different colors for bright colors (color8-color15)

### ISSUE THREAD

**Issue by ficok** [dylanaraps/pywal#702]
no matter which backend i use, the resulting colorscheme has the same colors for colors 0-7 and colors 8-15.
meaning, color0 and color8 are the same, color1 and color9 are the same etc.

![colorscheme](https://user-images.githubusercontent.com/65725593/233984645-43b6642c-df8a-4370-a327-75f6ea81e963.png)

is there a way to change this, because i would like them to differ?

**Comment by explosion-mental** [comment]
https://github.com/eylles/pywal16

**Comment by explosion-mental** [comment]
sidenote: as of now, I've added dark16/light16 schemes to [wallust](https://codeberg.org/explosion-mental/wallust/) in v2.2.0 :p
