### ISSUE TITLE
weechat support?

### ISSUE THREAD

**Issue by Iambecomeroot** [dylanaraps/pywal#71]
Is it possible to add a weechat theme? Right now there is horribly low contrast in the bars. Sorry, I don't know much about weechat. I just started using it today.

![image](https://user-images.githubusercontent.com/8503756/28886279-4915e738-778f-11e7-98e6-143edd64f878.png)

**Comment by dylanaraps** [comment]
I don't think a theme is needed here, you can easily fix the issue with the following commands:

```
# Color 66 is set to the value of color0 even when bold.

# Text colors
/set weechat.bar.title.color_fg 66
/set weechat.bar.title.color_fg 66
/set weechat.bar.status.color_delim 66
/set weechat.color.status_time 66
/set weechat.color.status_name 66
```

If we do go down the route of creating a theme it'll live in it's own repo so that users can fork it and set the color they like. Example theme: https://weechat.org/themes/source/crym.theme.html/

Note: I haven't figured out how to change the color of the server side-bar yet. I'll take another look later, I'm hopping on the train now.

**Comment by Iambecomeroot** [comment]
Thanks. How did you get the `[1]` and `[core]` black as well?

![image](https://user-images.githubusercontent.com/8503756/28921689-5aa7a9e8-782d-11e7-8a7d-88874c5b0739.png)

**Comment by dylanaraps** [comment]
My bad! Here's the update list, all that's missing is the server name in the left pane. One we've got a complete list I'll add it to the wiki. 

```
# Color 66 is set to the value of color0 even when bold.

# Text colors
/set weechat.bar.title.color_fg 66
/set weechat.bar.status.color_fg 66
/set weechat.bar.status.color_delim 66
/set weechat.color.status_time 66
/set weechat.color.status_name 66
```

**Comment by Iambecomeroot** [comment]
Thanks. It's looking good now. pywal doesn't generate a colour extremely close to `0` but a little lighter does it? That would be very handy!

**Comment by dylanaraps** [comment]
The closest color to `0` that it generates is color `8` which is almost twice as bright. I'll look into adding a color that's a little brighter than `0`.

**Comment by Iambecomeroot** [comment]
Thanks. `8` is nice for comments but it's way too bright for a background for the input area.
