### ISSUE TITLE
Changing GTK3 colour scheme in Wayland with pywal?

### ISSUE THREAD

**Issue by Ay1tsMe** [dylanaraps/pywal#718]
Is there anyway to generate a colour scheme for GTK3 in Wayland? Ive seen some old guides where people used oomox to generate an Xresources theme but I think you need to manually generate a theme each time you change colour scheme with pywal plus I don't think this works on wayland.

If anyone has insight on how can I can set it up then that would be great!

**Comment by ogabriel** [comment]
@Ay1tsMe https://github.com/deviantfero/wpgtk

then just change all things on `lxappearance` to "flatcolor"

**Comment by Ay1tsMe** [comment]
I ended up using this gtk theme and then creating a scss template to adjust the colourscheme: https://github.com/phocus/gtk
