### ISSUE TITLE
Installation instruction for Gentoo?

### ISSUE THREAD

**Issue by CocolinoFan** [dylanaraps/pywal#723]
Hello,

Is it possible to add installation instructions for Gentoo as well please?
Gentoo is an "externally-managed-environment" and is really not recommended to install things with pip.
```
error: externally-managed-environment

× This environment is externally managed
╰─>
    The system-wide Python installation in Gentoo should be maintained
    using the system package manager (e.g. emerge).

    If the package in question is not packaged for Gentoo, please
    consider installing it inside a virtual environment, e.g.:

    python -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage

    To exit the virtual environment, run:

    deactivate

    The virtual environment is not deleted, and can be re-entered by
    re-sourcing the activate file.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by Minda1975** [comment]
Hello.

 Install it with pipx, or create virtual environment and install it using python3-venv.

Commands:

`python -m venv .pywal_venv`

Then activate it

`source .pywal_venv/bin/activate`

then install it as usual

`pip install pywal`

Deactivate it with

`deactivate`

And copy pywal binary to your path.

**Comment by CocolinoFan** [comment]
Would this work? No way right? The binary that was created needs other stuff to run you can't just use it outside the virtual environment. 
Now I'll be damned, **it works**. I have no idea how python virtual environments work anymore xD
Thank you kind stranger. 

Maybe there should be Gentoo install instructions for smooth brained people like me?

**Comment by Minda1975** [comment]
> Now I'll be damned, **it works**. 

This is the official method used to install packages using pip.
Great that you made it. 

Please, close this issue.
