### ISSUE TITLE
Missing setuptools.

### ISSUE THREAD

**Issue by SethMulti** [dylanaraps/pywal#77]
When I go to install pywal I get this error _"Could not import setuptools which is required to install from a source distribution."_ If I try to manually  I get this _"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ocxvniqa-build/"_ Not sure if im missing something here.

**Comment by dylanaraps** [comment]
A quick fix is:

```sh
pip install -U --user  setuptools
```

I'll investigate why and how to fully fix this, thanks for reporting it.

**Comment by dylanaraps** [comment]
Are you using a `virtualenv` by any chance?

**Comment by dylanaraps** [comment]
Ok, from googling this is an issue with your environment and not `pywal`. `setuptools` should be installed with `pip` by default and if it isn't then that indicates that you either need to reinstall `pip` or manually install `setuptools`. 

My first comment should fix the issue for you.

**Comment by SethMulti** [comment]
Thank you for the help. sorry for not looking more into this before posting here. I had multiple issues, I got them all figured out.
