### ISSUE TITLE
Wallpaper turning black

### ISSUE THREAD

**Issue by westfelia** [dylanaraps/pywal#80]
Hey there,
I've been having an issue where wal seems to change the desktop to an all black image. It changes the colorscheme in the open terminals and vim but the wallpaper gets messed up. It may have to do with a messy install I had, since Python 3.6 doesn't seem to be what pip uses on my system, so I installed it via "sudo -H python3.6 -m pip install pywal". I installed pywal once before and it was working great, but uninstalled and reinstalled it and that's when the issues started. As for my system, I'm running Ubuntu 17.04 with Gnome using the Gnome terminal. The command I'm using for wal is simply "wal -t -i ~/Pictures/Wallpapers/wallpaper.jpg"

**Comment by dylanaraps** [comment]
Can you send me the outputs of these commands?:

```sh
echo "$XDG_CURRENT_DESKTOP"
echo "$DESKTOP_SESSION"
echo "$GNOME_DESKTOP_SESSION_ID
```

**Comment by westfelia** [comment]
Yup!
> echo "$XDG_CURRENT_DESKTOP"
GNOME
> echo "$DESKTOP_SESSION"
gnome
echo "$GNOME_DESKTOP_SESSION_ID
this-is-deprecated

Also, I saw that you added support for python 3.5 so I reinstalled but still have the same issue.

(PS I looked at your github and love your work! :D)

**Comment by dylanaraps** [comment]
Try the latest release (`0.6.1`) and let me know if it fixes the issue. :)

**Comment by westfelia** [comment]
Sadly it didn't fix it :disappointed: It produces this error now
```
 image: Using image Pictures/Wallpapers/Firewatch-4K-Wallpaper-1.jpg
wal: Generating a colorscheme...
wal: Generation complete.
colors: Set terminal colors.
Traceback (most recent call last):
  File "/home/ryan/.local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/__main__.py", line 144, in main
    process_args(args)
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/__main__.py", line 130, in process_args
    wallpaper.change(colors_plain["wallpaper"])
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/wallpaper.py", line 108, in change
    set_desktop_wallpaper(desktop, img)
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/wallpaper.py", line 75, in set_desktop_wallpaper
    "picture-uri", "file://" + urllib.parse.quote(img)])
AttributeError: module 'urllib' has no attribute 'parse'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/ryan/.local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/__main__.py", line 144, in main
    process_args(args)
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/__main__.py", line 130, in process_args
    wallpaper.change(colors_plain["wallpaper"])
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/wallpaper.py", line 108, in change
    set_desktop_wallpaper(desktop, img)
  File "/home/ryan/.local/lib/python3.6/site-packages/pywal/wallpaper.py", line 75, in set_desktop_wallpaper
    "picture-uri", "file://" + urllib.parse.quote(img)])
AttributeError: module 'urllib' has no attribute 'parse'
```


I also updated and checked Python, it's running 3.6 now. The colorscheme of the terminal was generated and changed, but the wallpaper was unaffected.

**Comment by dylanaraps** [comment]
Oops!

I’ll fix this tomorrow, it’s 2am here.

**Comment by westfelia** [comment]
Great! Thanks a bunch :smile:

**Comment by dylanaraps** [comment]
Try the latest release (`0.6.2`). :)

**Comment by westfelia** [comment]
Still black :disappointed: Anything I could do to help reproduce it?

**Comment by dylanaraps** [comment]
Does this command work (*in your terminal*)?

```sh
# Replace the image path with a valid one. (Keep the 'file://')
gsettings set org.gnome.desktop.background picture-uri file:///home/dylan/Pictures/1.jpg
```

**Comment by westfelia** [comment]
It did yes!

**Comment by dylanaraps** [comment]
Hmm, let me install GNOME and see if I can reproduce this.

**Comment by westfelia** [comment]
Thanks! And sorry for the hassle :sweat_smile:

**Comment by dylanaraps** [comment]
Weird.

It works perfectly fine in my GNOME install (*using `GNOME 3.24`*).

**Comment by dylanaraps** [comment]
Does this comand fix the issue?: 

```sh
gsettings set org.gnome.settings-daemon.plugins.background active true
```

(Run the command and then run `wal`)

**Comment by westfelia** [comment]
Yeah that worked!!

**Comment by westfelia** [comment]
Okay now it stopped working :astonished:

**Comment by westfelia** [comment]
Okay, after some checking around I think it might be an issue with gnome.  This command
```
gsettings set org.gnome.desktop.background picture-uri file:///home/dylan/Pictures/1.jpg
```
(but with a real file) no longer worked. It worked just while wal was briefly working but now it doesn't. I believe (though by no means certain) that wal and this may have broken when I gave an image without the full path (ie pic.jpg instead of ~/Pictures/pic.jpg)

**Comment by dylanaraps** [comment]
Try the latest release (`0.6.4`), I've made sure that `pywal` converts shortened paths to the full path.

**Comment by westfelia** [comment]
It's working!! Great :smile:
