### ISSUE TITLE
XTerm vs. UXterm

### ISSUE THREAD

**Issue by Tadly** [dylanaraps/pywal#81]
Some distros, at least arch, include a unicode wrapper for XTerm named UXterm.
This wrapper will be priorities by e.g. `i3-sensible-terminal` which causes the colors for
**foreground**, **background** and **cursorColor** to not be applied.

Using `xterm*` instead of `XTerm*` will solve this problem.
```
xterm*foreground: <color>
xterm*background: <color>
xterm*cursorColor: <color>
```

*Disclaimer* :P
As I'm fairly new to dealing with Xresource files and just now migrated to xterm (due to sixel support) I'm not a 100% sure if this is the proper way of dealing with this issue.

**Comment by Tadly** [comment]
Never mind. Seems like I used `xrdb` wrong.

Than I'd propose to include both, `XTerm` an `UXterm` for the aforementioned colors unless someone knows of a better way to deal with this :)

**Comment by dylanaraps** [comment]
Fixed, thanks!
