### ISSUE TITLE
Wal font generation

### ISSUE THREAD

**Issue by ecly** [dylanaraps/pywal#82]
Since I'm basically using wal's generated files and variables for styling everything, it would be cool if it was possible to also declare a central font that would be exported to css etc. such that I could use for styling everything and thereby allowing for a central font declaration for the entire system.

**Comment by dylanaraps** [comment]
I've opened #85 which implements this. Give the PR a read and let me know if this satisfies your needs. :)

**Comment by ecly** [comment]
Haha, it finally made it in! Cheers @dylanaraps ! I should start using this now!

**Comment by dylanaraps** [comment]
It hasn't made it in... I closed the PR as I feel this is out of scope.

**Comment by ecly** [comment]
@dylanaraps oh hahaha, I was wondering why the issue didn't auto close. Either way, granted that decision, which I think is totally reasonable, then I think it makes sense to close the issue! Thanks for all your work either way @dylanaraps ! Cheers.
