### ISSUE TITLE
Mac Issues

### ISSUE THREAD

**Issue by MattCastellana** [dylanaraps/pywal#84]
Hi there, I just installed the latest version of Pywal on macOS and ran into an issue or two.

---

First was that, when I ran `wal -i image.png`, I'd get an error from line 87 of wallpaper.py.

The error was `TypeError: unsupported operand type(s) for /: 'str' and 'str'`.

It seems there was an error of some sort parsing the `HOME / 'Library...` bit of code.  I fixed it quickly by changing it to be`HOME + '/Library...` instead.   

After that the wallpaper set correctly.

(I'm not overly familiar with python, so I'm not sure exactly how the `/` worked in this scenario, but for some reason it wasn't parsing correctly for me.)

---

Second issue was that, when running the command it iterm2, it would change some font and tab colors, however not the background, foreground and some other main colors.

I looked at iterm's website for the syntax for switching it.  And the example they show is `echo -e "\033]Pg4040ff\033\\"`

Doing some quick debugging, I found that wal was outputting something like: `"\033[Pg4040ff\033\\"`. 

Pretty much the same, the only difference being that the bracket was the other way around (`[`, instead of `]` like the iterm example).  I switched the bracket around on line 16 of sequences.py.  And everything worked correctly going forward.

Now, I'm using the iterm2 beta (3.1.beta.5), so this bracket issue may be a change in syntax they made recently, I'm not too sure.

Anyway, not sure if these issues are effecting other Mac users, but I thought I'd post them here incase they are wider spread issues.

---

Another thing I'd like to mention isn't an issue, but a small thing I've done which might be a cool feature for some users (May only be applicable to iterm users, not sure).  

What I did was add a small bit of text: `echo -e "$(cat ~/.cache/wal/sequences)"` to my `.bash_profile`.  Which allows me to reload the color scheme when reloading my terminal, (As it the colors don't stick in iterm normally).

**Comment by dylanaraps** [comment]
Thanks for the in-depth report! This makes it so much easier for me to fix these issues. :)

> First was that, when I ran wal -i image.png, I'd get an error from line 87 of wallpaper.py.
> The error was TypeError: unsupported operand type(s) for /: 'str' and 'str'.

This was a bug introduced in the move to Python 3.5. **Fixed.**

> Second issue was that, when running the command it iterm2, it would change some font and tab colors, however not the background, foreground and some other main colors.

Same as above. **Fixed.**

> What I did was add a small bit of text: echo -e "$(cat ~/.cache/wal/sequences)" to my .bash_profile. Which allows me to reload the color scheme when reloading my terminal, (As it the colors don't stick in iterm normally).

This is already implemented as `wal -r`.

https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals

**Comment by dylanaraps** [comment]
(Released `0.6.5` with the fixes.)

**Comment by MattCastellana** [comment]
Glad I could help out!

Ohh, awesome!  I've switched over to using wal-r now.  Works great!  Although when I run it, there are a few random characters (Usually a character and some whitespace) before my input area when I first load it up.  Is that normal?

**Comment by dylanaraps** [comment]
This is related to #69 and adding `-t` to all of your `wal` commands should fix the issue.
