### ISSUE TITLE
Mac X11 issue

### ISSUE THREAD

**Issue by MattCastellana** [dylanaraps/pywal#86]
Hi Again,

I've noticed a weird bug with pywal interacting with my Mac's Xquartz (x11) installation.   As far as I can tell, whenever I run the `wal` command, and the xquartz app is not open, the command will freeze when refreshing the environments, and just sit there.

I've tracked down the error specifically to `xrdb` command in `reload.py` (line 19/20ish).   It seems that the xrdb command will freeze on mac and wait for xquartz to open if it isn't open already.

Anyway, I fixed the issue by chaning line 18 of `reload.py`.

I changed
`if shutil.which("xrdb"):` 
to 
`if shutil.which("xrdb") and OS != "Darwin":`)

I also added `OS` to the import from .settings (Line 10), so I could use that variable there.

Once this was added, it bypassed the xrdb command and allowed the env to refresh normally.

(I haven't used python in a few years, so there may be a simpler fix for this, but it worked for me.)

---

I also tested pywal without xquartz installed, and everything worked correctly, so it seems to only happen when Xquartz is installed.

I wish I could help figure out why this issue was happening with Xquartz, but I'm not familiar enough with how X11 works on mac to be able to.

**Comment by dylanaraps** [comment]
Fixed!

Thanks!
