### ISSUE TITLE
Possible to edit the way pywal works with rofi?

### ISSUE THREAD

**Issue by khoacao96** [dylanaraps/pywal#89]
I don't know how to correctly describe this, so I'll try my best:

As you know, when `pywal` generates colorschemes to apply it to `rofi` through .Xresources, the colors are pretty much "absolute" - which means that if the user wants to change any part of `rofi`'s colorscheme, he/she will have to edit by hand the .Xresources file, reload, and even then the colorset will not remain the same the next time that wallpaper is chosen, as each colors are automatically + directly stated in the file by `pywal`; unlike `polybar`, when you can dynamically set e.g. color01, color02, color03... and each bar elements can catch different colors & the way colors are chosen is persistent through wallpapers.

I think it's mostly because `rofi` directly takes the colors in the .Xresources, but I still want to ask: is there any way to edit how `pywal` implements colors for `rofi` so that we can achieve the same mechanics for both `rofi` and `polybar`?

Sorry if there's wordiness because I'm not a native English speaker. Thank you for reading this issue.

**Comment by dylanaraps** [comment]
You can create a custom script to launch `rofi` with custom colors (*This is what I'm currently doing.*). Other than this there's no other way of customizing the `rofi` colors from `pywal`.

I'm trying to come up with a solution that will give the user more control but that's a ways away.

Example script:

```sh
#!/usr/bin/env bash

source "${home}/.cache/wal/colors.sh"

rofi -show run \
     -color-window "$background, $background $color1" \
     -color-normal "$background, $foreground, $background, $color1, $background" \
     -color-active "$background, $foreground, $background, $color1, $background"
```

Basically, if you bind this script to a key it will use whatever colors you set inside of it on every launch.

**Comment by ZodiacFRA** [comment]
Hi, I'm trying to make your script work @dylanaraps, when I launch the script using 
`bindsym $mod+d exec /home/launch_rofi.sh`
with hardcoded colors (#FF0000 etc) everything works as expected, but if I replace one of the hardcoded colors with one imported by `source "${home}/.cache/wal/colors.sh"`  I get the following error displayed in the rofi window:

```
Error while parsing theme: *
{ separatorcolor : ; } 
Parser error: syntax error, unexpected "property close (';')"
```

Any idea on how I could solve this?
Have a good day :)
