### ISSUE TITLE
GTK theme update

### ISSUE THREAD

**Issue by koopa1338** [dylanaraps/pywal#90]
So the issue that I'm having atm is when I update the GTK theme, most application are updated instantly or showing the new color on restart except my gtk of the terminal (urxvt) (not the terminal itself). 

I tried to restart the terminal without any success. It updates on reboot or reapplying the GTK-theme though. Im new to this software and will do some further research. I'm using Archlinux with Gnome-desktop and urxvt with fish shell.

**Comment by dylanaraps** [comment]
Can you send me a screenshot?

**Comment by koopa1338** [comment]
Sorry for my late response. So I tried out different things and had to realize, that it wasn't only the gtk of my terminal but a bunch of different application. My calculator for example just needs a restart and shows the new colors in the gtk theme but other applications like my file browser or email client doesn't. After a relog the new color scheme is applied every where but the reason couldn't be gtk3: `libgtksourceview-3.0.so.1 => /usr/lib/libgtksourceview-3.0.so.1 (0x00007f21bb3f2000)
	libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f21baae2000)`

**Comment by dylanaraps** [comment]
Are the applications that require a restart GTK3 applications? If so then this is caused by the fact that GTK3 applications can't be reloaded on the fly.

**Comment by koopa1338** [comment]
the calculator for example is a gtk3 application and shows the new colorscheme after a restart. But the other applications like my filebrowser or the window decoration of my terminal window i have to logout and log back in. seems really strange to me because my filebrowser is gtk2: `ldd /usr/bin/thunar | grep gtk
	libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007f1f69a4b000)`

**Comment by dylanaraps** [comment]
Thunar not updating on the fly isn't a `pywal` issue but an issue with Thunar itself. There's nothing we can do to fix it.

Basically we can't reload GTK3 programs on the fly nor can some GTK2 elements be reloaded on the fly.
