### ISSUE TITLE
vim colorscheme requires manual intervention

### ISSUE THREAD

**Issue by sphaugh** [dylanaraps/pywal#91]
I have this line in my `~/.i3/config`:

```
exec --no-startup-id wal -i ~/usr/img/wallpaper/koi-to-uso.png
```

After a reboot I see this:
![before](https://user-images.githubusercontent.com/8660255/29631668-01bf84b6-8806-11e7-992d-41ccb456839a.png)

![vim-before](https://user-images.githubusercontent.com/8660255/29631580-be3393b8-8805-11e7-9dd2-6f365897490f.png)

I have to run `wal` again to get the colors right:
![after](https://user-images.githubusercontent.com/8660255/29631706-1e394cee-8806-11e7-860f-872216cff68d.png)

![vim-after](https://user-images.githubusercontent.com/8660255/29631710-208595d4-8806-11e7-80cf-9fce7d854c34.png)

**Comment by dylanaraps** [comment]
Fixed.

(*Update both `pywal` and `wal.vim`*)

**Comment by sphaugh** [comment]
Thanks! :)
