### ISSUE TITLE
Shipping a patched version of pywal for use in wal_steam?

### ISSUE THREAD

**Issue by kotajacob** [dylanaraps/pywal#92]
First of all sorry for spamming in an issue I wasn't quite sure the best way to contact you. Basically I'm currently working on version 1.2.0 of wal_steam and one of the big features is adding windows support due to the massive request for it. Now obviously you don't support seem to support windows with pywal, but wal seems to work and on reddit /u/reeBro [managed to patch pywal for windows support.](https://www.reddit.com/r/pcmasterrace/comments/6v828r/me_and_my_friend_ukotajacob_just_released_our/dm14zcn/) I was wondering if you would be apposed to me possibly shipping wal or pywal with wal_steam for our windows users. It could be done either via downloading it on their request or simply packaging it in the windows download for wal_steam.

**Comment by dylanaraps** [comment]
I'll look into adding Windows support to `pywal`, it shouldn't take much work. (*I'm not hard-coding many paths at all.*) I've got a Windows machine at home so I'll work on this tonight. 

That comment on reddit is a big help too though it gets a number of things wrong. 

Yeah, feel free to package `pywal` for your Windows users. The licence permits it so long as you include the `LICENCE.md` file with your package. :)

**Comment by kotajacob** [comment]
Thanks a bunch that sounds great.
