### ISSUE TITLE
Terminal colors are skewed by wal

### ISSUE THREAD

**Issue by boardfish** [dylanaraps/pywal#95]
When using a Vim plugin such as [Colorizer](/chrisbra/Colorizer) while wal is active, they display inaccurately. This may just be on the occasion that the color in question is in the theme currently being used, which is working against me right now - I'm trying to edit a cached scheme. I'm fairly sure my theory there is right, as entering a totally unrelated color to what is currently displaying results in it displaying accurately.

I logged this here because I have a suspicion it's to do with how wal handles, or terminals themselves handle, dealing with colors this way. I think it's less to do with the vim theme.

If it helps at all, I've toyed with this in gnome-terminal, konsole and xterm (with 256 colors enabled).

**Comment by dylanaraps** [comment]
Yeah, there's no way for me to fix this. 

The only solution I can see is using a true-color supported terminal emulator which bypasses the terminal scheme and displays the exact hex color.

**Comment by boardfish** [comment]
Like I've mentioned in another issue, Konsole is a great card to play here, since you can change color schemes on the fly. If colors are relevant to your work, it's probably a good idea to switch to a different profile for a moment.

**Comment by kotajacob** [comment]
This list of terminals that support true colour may be useful. https://gist.github.com/XVilka/8346728
It's also worth noting you'll probably need a recent build of vim/neovim and `set termguicolors` in your vimrc to enable support.
