### ISSUE TITLE
MacOS Bug with process hang

### ISSUE THREAD

**Issue by Jarvvski** [dylanaraps/pywal#96]
![](http://i.imgur.com/k717jOG.png)

The process sits like this for a long time, seemingly never ending.

I have to close the window to end the process. ^c does nothing

Any idea what's wrong?

**Comment by dylanaraps** [comment]
This is happening in the sequences part of `pywal` and most likely when it sends the sequences to open terminals. 

Can you send me the output of these commands?:

- `ls -l /dev/`
- `ls -l /dev/ttys00[0-9]*`

**Comment by Jarvvski** [comment]
I ended up restarting my system and it worked. I believe it has something to do with how xquartz installs through brew, and requires a restart before `feh` can work correctly
