### ISSUE TITLE
Bug? Colors change in ranger etc, but not urxvt 

### ISSUE THREAD

**Issue by johnabs** [dylanaraps/pywal#99]
Hey, after having a wonderful time figuring out I am incompetent, I am now stuck. You see, the text color in ranger, rofi, and all my other nice things changes after runnign wal, but my foreground color in urxvt either won't budge, or at least is not the same color as the ps1 in ranger (also in urxvt). It may just be my colorblindness, but if it's not, do you have any ideas?  

If you need any files/commands I'm running to make this work, just let me know and I'll include them ASAP. I absolutely love this tool and love experimenting with it, thank you for making it, and for your help!

**Comment by dylanaraps** [comment]
Can I see a screenshot? I can't seem to reproduce this at all.

**Comment by johnabs** [comment]
Actually, I'm just colorblind. I finally saw it changing when I picked a blue background. Sorry for the inconvenience!
